"""
test_FG7e_colour_condensate.py — the colour-magnetic condensate arising within the model
========================================================================================

Verifies `ca-simulation/ca_colour_condensate.py` and
`ca-simulation/derive_colour_condensate.py` (F88): the colour-magnetic
condensate F86 *assumed* is here *derived* from the model's own physics —
the f^abc/eps^abc Yang–Mills self-coupling (F43) and the compactness of the
link variables.

Route 1 — the vacuum is FORCED and FAVOURED to condense:
  CC1  Nielsen–Olesen instability: W_mu = e^{gamma t} psi eps_mu with the
       lowest-Landau-level psi solves the LINEARISED model YM EOM around a
       constant chromomagnetic background EXACTLY iff gamma^2 = +gB (spin
       aligned).  Scalar control (no eps^abc spin term): omega^2 = +gB > 0.
       The instability is generated by the structure constants.  [sympy]
  CC2  Savvidy one-loop potential, Hurwitz-zeta exact: Re dV log coefficient
       = 11/96pi^2 g^2 B^2 (asymptotic freedom); B_min and V_min < 0 in
       closed form for every g > 0; Im V = g^2 B^2/16pi > 0.  [sympy]
  CC3  Lattice tachyon on the model's compact uniform-flux links: the
       spin-aligned charged-gluon tower has min Omega^2 = -phi (ratio -> -1
       as phi -> 0).  In F26 language: the (E,B) rotation rate of this mode
       is imaginary — it grows instead of rotating.
  CC4  Lattice Savvidy: one-loop vacuum energy dE(B) = E(B) - E(0) < 0 for
       every flux tested (finite mode sum, lattice = UV regulator).

Route 2 — WHAT condenses (monopoles from compactness):
  CC5  DeGrand–Toussaint monopole number on compact links: integer
       bit-for-bit, gauge-invariant bit-for-bit, total charge 0 on the
       torus, and EXACTLY +-1 on a constructed Dirac pair.
  CC6  The exact duality identities: Villain/Poisson link identity and the
       Coulomb-gas <-> Gaussian (sine-Gordon) identity, machine-eps.
  CC7  The model's own SU(3) links at strong coupling (Haar) carry a
       non-zero Abelian-projected monopole density (integer-exact charges).
  CC8  3D compact U(1) Monte-Carlo: rho(beta) > 0, monotone decreasing,
       dilute-gas (log-linear) tail; chain rho -> z -> m_D -> v = m_D/e
       hands F86 its condensate VEV: sigma_F86 = 2 pi v^2 > 0, measured.

Modules under test:  ca-simulation/ca_colour_condensate.py,
                     ca-simulation/derive_colour_condensate.py (+ sympy)
Created:             2026-06-04
"""
import sys
import os
import json
import time
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'ca-simulation'))

import ca_colour_condensate as cc       # noqa: E402
import derive_colour_condensate as dcc  # noqa: E402


class _NumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, (np.integer,)):
            return int(obj)
        if isinstance(obj, (np.floating,)):
            return float(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return super().default(obj)


RESULTS = {}
FAILURES = []


def record(name, passed, detail):
    RESULTS[name] = {'pass': bool(passed), **detail}
    status = 'PASS' if passed else 'FAIL'
    print(f'  [{status}] {name}: {detail}')
    if not passed:
        FAILURES.append(name)


# ------------------------------------------------------------------
def test_CC1_nielsen_olesen_exact():
    print('CC1  Nielsen–Olesen instability (sympy, linearised model YM EOM)')
    r = dcc.derive_D1_nielsen_olesen()
    ok_scalar = dcc.derive_D1b_scalar_control()
    passed = (r['aligned'] and r['nonvacuous'] and (not r['anti-aligned'])
              and ok_scalar)
    record('CC1', passed, {
        'aligned_gamma2_gB_exact': r['aligned'],
        'wrong_dispersion_fails': r['nonvacuous'],
        'anti_aligned_does_not_grow': not r['anti-aligned'],
        'scalar_control_omega2_pos_gB': ok_scalar,
        'tier': 1})


def test_CC2_savvidy_exact():
    print('CC2  Savvidy one-loop potential (sympy, Hurwitz zeta)')
    r = dcc.derive_D2_savvidy()
    keys = ('zeta_sum_-11/6', 'log_coeff_11/96pi2', 'B_min_closed_form',
            'V_min_negative', 'Im_V_g2B2_16pi')
    passed = all(r[k] for k in keys)
    record('CC2', passed, {**{k: r[k] for k in keys},
                           'B_min': r['Bmin'], 'V_min': r['Vmin'], 'tier': 1})


def test_CC3_lattice_tachyon():
    print('CC3  Lattice tachyon on compact uniform-flux links')
    Ux, Uy, phi = cc.flux_links_2d(16, 1)
    plaq_res = float(np.abs(cc.plaquette_angles_2d(Ux, Uy) - phi).max())
    rows = []
    for L, q in ((12, 1), (16, 1), (24, 1), (32, 1), (16, 2)):
        o2, ratio, ph = cc.tachyon_certificate(L, q)
        rows.append({'L': L, 'q': q, 'phi': ph, 'min_Omega2': o2,
                     'ratio_to_minus_phi': ratio})
    all_neg = all(r['min_Omega2'] < 0 for r in rows)
    # continuum limit: |ratio + 1| shrinks with phi (compare L=12 vs L=32, q=1)
    err12 = abs(rows[0]['ratio_to_minus_phi'] + 1.0)
    err32 = abs(rows[3]['ratio_to_minus_phi'] + 1.0)
    converges = err32 < err12 and err32 < 1e-2
    passed = (plaq_res < 1e-13) and all_neg and converges
    record('CC3', passed, {
        'plaquette_uniformity_residual': plaq_res,
        'all_min_Omega2_negative': all_neg,
        'ratio_err_L12': err12, 'ratio_err_L32': err32,
        'rows': rows, 'tier': 3})


def test_CC4_lattice_savvidy():
    print('CC4  Lattice Savvidy mode sum: dE(B) < 0')
    scan = cc.savvidy_scan(24, [1, 2, 3, 4, 6, 8], Lz=24)
    rows = [{'q': q, 'B': phi, 'dE_per_site': dE} for q, phi, dE in scan]
    all_neg = all(r['dE_per_site'] < 0 for r in rows)
    monotone = all(rows[i + 1]['dE_per_site'] < rows[i]['dE_per_site']
                   for i in range(len(rows) - 1))
    record('CC4', all_neg and monotone, {
        'all_dE_negative': all_neg, 'monotone_in_B': monotone,
        'rows': rows, 'tier': 3})


def test_CC5_dgt_monopoles():
    print('CC5  DeGrand–Toussaint monopoles: quantisation certificates')
    th = cc.random_compact_links_3d(8, seed=2)
    m = cc.dgt_monopole_field(th)
    int_res = float(np.abs(m - np.rint(m)).max())
    tot = float(abs(m.sum()))
    alpha = np.random.default_rng(5).uniform(-np.pi, np.pi, (8, 8, 8))
    gauge_res = float(np.abs(
        m - cc.dgt_monopole_field(cc.gauge_transform_3d(th, alpha))).max())

    thp, rp, rm = cc.dirac_pair_config(16)
    mp = cc.dgt_monopole_field(thp)
    pair_ok = (float(np.abs(mp).sum()) == 2.0 and float(mp.sum()) == 0.0
               and set(np.unique(mp)) == {-1.0, 0.0, 1.0})
    # charges sit in the cubes containing the constructed endpoints
    locs = {tuple(p) for p in np.argwhere(mp != 0)}
    expected = {tuple(np.floor(rp).astype(int)), tuple(np.floor(rm).astype(int))}
    pair_located = locs == expected
    passed = (int_res == 0.0 and tot == 0.0 and gauge_res == 0.0
              and pair_ok and pair_located)
    record('CC5', passed, {
        'integer_residual': int_res, 'total_charge': tot,
        'gauge_invariance_residual': gauge_res,
        'dirac_pair_charges_pm1': pair_ok,
        'dirac_pair_located': pair_located, 'tier': 1})


def test_CC6_duality_identities():
    print('CC6  Exact duality identities (Villain/Poisson, Coulomb gas)')
    res_v = max(cc.villain_poisson_residual(b, np.linspace(-3, 3, 17))
                for b in (0.3, 1.0, 2.5))
    res_c = cc.coulomb_gas_gaussian_residual()
    res_c2 = cc.coulomb_gas_gaussian_residual(n_sites=4, kappa=0.8,
                                              mass2=1.1, charges=(2, -1, -1, 0))
    passed = res_v < 1e-12 and res_c < 1e-12 and res_c2 < 1e-12
    record('CC6', passed, {
        'villain_poisson_residual': res_v,
        'coulomb_gas_residual_3site': res_c,
        'coulomb_gas_residual_4site': res_c2, 'tier': 2})


def test_CC7_su3_projection():
    print('CC7  Model SU(3) links (strong coupling): monopoles present')
    U = cc.haar_su3((3, 8, 8, 8), seed=4)
    unit_res = float(np.abs(
        np.einsum('...ij,...kj->...ik', U, U.conj()) - np.eye(3)).max())
    t1, t2 = cc.su3_diag_phases(U)
    m1 = cc.dgt_monopole_field(t1)
    m2 = cc.dgt_monopole_field(t2)
    int_res = float(max(np.abs(m1 - np.rint(m1)).max(),
                        np.abs(m2 - np.rint(m2)).max()))
    rho1 = float(np.abs(m1).sum() / 8**3)
    rho2 = float(np.abs(m2).sum() / 8**3)
    passed = unit_res < 1e-12 and int_res == 0.0 and rho1 > 0.1 and rho2 > 0.1
    record('CC7', passed, {
        'su3_unitarity_residual': unit_res, 'integer_residual': int_res,
        'rho_cartan1': rho1, 'rho_cartan2': rho2, 'tier': 1})


def test_CC8_mc_density_and_f86_handoff():
    print('CC8  MC monopole density rho(beta) + F86 hand-off v = m_D/e')
    scan = cc.monopole_density_vs_beta(L=8, betas=(0.6, 1.0, 1.4, 1.8, 2.2),
                                       n_sweeps=300, seed=3)
    betas = np.array([b for b, _ in scan])
    rhos = np.array([r for _, r in scan])
    all_pos = bool((rhos > 0).all())
    decreasing = bool((np.diff(rhos) < 0).all())
    # dilute-gas tail: ln rho vs beta strongly anticorrelated
    corr = float(np.corrcoef(betas, np.log(rhos))[0, 1])
    # hand-off at beta = 1.8 (dilute regime)
    b_star, rho_star = scan[3]
    v, sigma_f86, mD = cc.f86_vev_from_density(b_star, rho_star)
    passed = all_pos and decreasing and corr < -0.95 and v > 0 and sigma_f86 > 0
    record('CC8', passed, {
        'rho_vs_beta': scan, 'all_positive': all_pos,
        'monotone_decreasing': decreasing, 'log_linear_corr': corr,
        'handoff_beta': b_star, 'handoff_rho': rho_star,
        'debye_mass_mD': mD, 'f86_vev_v': v,
        'sigma_F86_2piv2': sigma_f86, 'tier': 3})


# ------------------------------------------------------------------
def main():
    t0 = time.time()
    print('=' * 70)
    print('FG-7e: the colour-magnetic condensate arising within the model')
    print('=' * 70)
    test_CC1_nielsen_olesen_exact()
    test_CC2_savvidy_exact()
    test_CC3_lattice_tachyon()
    test_CC4_lattice_savvidy()
    test_CC5_dgt_monopoles()
    test_CC6_duality_identities()
    test_CC7_su3_projection()
    test_CC8_mc_density_and_f86_handoff()

    dt = time.time() - t0
    n_pass = sum(1 for r in RESULTS.values() if r['pass'])
    print('-' * 70)
    print(f'{n_pass}/{len(RESULTS)} PASS in {dt:.2f} s')
    out = {'suite': 'FG7e_colour_condensate', 'date': '2026-06-04',
           'n_pass': n_pass, 'n_total': len(RESULTS),
           'elapsed_s': dt, 'results': RESULTS}
    out_path = os.path.join(os.path.dirname(__file__), '..', '..', 'test-results',
                            'FG7e_colour_condensate.json')
    with open(out_path, 'w') as f:
        json.dump(out, f, indent=2, cls=_NumpyEncoder)
    print(f'results -> {os.path.normpath(out_path)}')
    sys.exit(0 if not FAILURES else 1)


if __name__ == '__main__':
    main()
