"""
F166 — triple-gluon vertex branch structure: closing audit C3.

The audit (physics-audit-report-2026-06-29, C3) noted that F91's gluon "even"
classification (G1) was proven only for the LINEAR/free propagator: the colour
coupling diag(U+,U-)⊗I commutes with I⊗exp(iθ·T) to 1.1e-16, so the
fermion-gluon vertex is branch-blind. But the SU(3) SELF-coupling (triple and
quartic gluon vertices) was never analysed for branch structure — "if the
nonlinear self-coupling has any chiral component, the even classification would
need revision."

This test answers that: the gluon self-coupling has NO chiral (branch /
gamma5) component, exactly, by construction. The triple-gluon vertex is
generated entirely by the pure-gauge plaquette action S(A), a functional of the
gauge field A^a_mu — which carries (Lorentz mu, colour a) indices and NO branch
(BCC chirality) index. So the vertex lives in (Lorentz (x) colour) only; its
branch-space matrix is the identity I_2, whose gamma5-projection is exactly 0.

  T1 (EXACT, structural): the model's own triple-gluon (AQQ) vertex tensor
     gammaF_tensor_continuum(k,q) is a rank-3 Lorentz tensor (4,4,4), real,
     carrying NO Dirac/branch axis. The lattice 3-gluon vertex extractor
     (ca_lpt_vertex) reads off S(A) with no fermion field present.

  T2 (EXACT, F91-G1 extended): embed the cubic vertex as the operator
     I_branch (x) Gamma in (branch (x) Lorentz) space; its commutator with the
     branch chirality operator gamma5 = diag(+1,-1) (x) I is identically 0 —
     the F91-G1 commutator replayed for the self-coupling.

  T3 (EXACT + CONTRAST): the gamma5-projection of each sector's branch-space
     coupling matrix M, P_gamma5(M) = (1/2)Tr(gamma5.M). Gluon self-coupling
     M = I_2 -> 0 (even forced). Contrast: W coupling M = P_L = diag(1,0) ->
     1/2 (chiral). Photon M = Q.I -> 0 (even). This reproduces the F91
     classification table from the branch-matrix viewpoint and EXTENDS it to
     the cubic vertex.

  T4 (MACHINE): the only nontrivial index structure of the self-coupling is
     colour: a leg colour-swap flips the vertex sign (f^{abc} antisymmetry),
     branch-independently (reuses ca_lpt_vertex.bose_antisymmetry).

Verdict: C3 is UPGRADED. The gluon "even" classification is forced not only at
the free-propagator level but at the interacting (self-coupling) level, because
every pure-gauge gluon vertex is branch-trivial by construction. The remaining
open gluon items (finite d1 / q* digit, F162/F163) concern the MAGNITUDE of the
self-energy, not its branch structure, and are orthogonal to this result.
"""
import math
import os
import sys

import numpy as np

import os as _os, sys as _sys  # noqa: E401
_sys.path.insert(0, _os.path.join(
    _os.path.dirname(_os.path.abspath(__file__)), "..", "..", "src"))

from casim.engine.gauge import bgfield_loop as bg
from casim.engine.gauge import lpt_vertex as lpt

# Branch (BCC chirality) space is 2D: the (+, -) Weyl branches.
GAMMA5 = np.diag([1.0, -1.0])          # the model's branch chirality operator
I2 = np.eye(2)


def p_gamma5(M):
    """Pseudoscalar (chiral) projection of a 2x2 branch-space coupling matrix:
    coefficient of gamma5 in M = a.I + b.gamma5 + (off-diag).  b = (1/2)Tr(g5 M)."""
    return 0.5 * np.trace(GAMMA5 @ M)


def run():
    results = {}
    rng = np.random.default_rng(0)

    # ---- T1: the model's triple-gluon vertex carries no Dirac/branch axis ----
    k = rng.standard_normal(4)
    q = rng.standard_normal(4)
    G = bg.gammaF_tensor_continuum(k, q)
    # rank-3 Lorentz tensor, real, 4x4x4 — no spinor/branch index
    okT1 = (G.ndim == 3 and G.shape == (4, 4, 4)
            and np.allclose(G.imag, 0.0))
    # the lattice extractor reads S(A) with no fermion field: the quadratic
    # term reproduces the gluon propagator (constant to lattice artifacts,
    # informational — the core T1 claim is the absence of a branch axis)
    prop = lpt.propagator_check()
    results["T1_vertex_no_branch_axis"] = dict(
        passed=bool(okT1), vertex_shape=list(G.shape), vertex_ndim=int(G.ndim),
        vertex_real=bool(np.allclose(G.imag, 0.0)),
        dirac_branch_axes=0,
        propagator_ratio_spread_rel=float(prop["ratio_spread_rel"]),
        note="triple-gluon vertex = pure (Lorentz (x) colour); generated by "
             "S(A) which has no fermion field, hence no gamma5 index")

    # ---- T2: F91-G1 commutator extended to the cubic vertex ----
    # The self-coupling acts as I_branch (x) Gamma; gamma5_full = gamma5 (x) I.
    # Use a generic Lorentz block (the contracted vertex on fixed external legs)
    # to stand for Gamma; what matters is the branch factor is I_2.
    Gamma_block = G.reshape(4, 16)              # any Lorentz-space operator
    V_full = np.kron(I2, Gamma_block)           # branch-trivial embedding
    g5_full = np.kron(GAMMA5, np.eye(16))
    # commutator on the square Lorentz part (use G contracted to a square op)
    Gsq = np.einsum('abc,cbd->ad', G, G)        # a real 4x4 Lorentz operator
    V_sq = np.kron(I2, Gsq)
    g5_sq = np.kron(GAMMA5, np.eye(4))
    comm = V_sq @ g5_sq - g5_sq @ V_sq
    comm_norm = float(np.max(np.abs(comm)))
    okT2 = comm_norm == 0.0
    results["T2_branch_commutator_zero"] = dict(
        passed=bool(okT2), commutator_max_abs=comm_norm,
        note="[gamma5 (x) I, I (x) Gamma] = 0 exactly — F91-G1 for the cubic "
             "vertex; branch-blind => even channel forced (F68 argument)")

    # ---- T3: gamma5-projection per sector (exact + contrast) ----
    # gluon self-coupling: branch matrix is the identity (never touches branch)
    M_gluon = I2.copy()
    # photon: M = Q.I (scalar in branch) — take Q=1 representative
    M_photon = 1.0 * I2
    # W: left projector P_L = diag(1,0) in branch space (chiral, the contrast)
    M_W = np.diag([1.0, 0.0])
    pg_gluon = float(np.real(p_gamma5(M_gluon)))
    pg_photon = float(np.real(p_gamma5(M_photon)))
    pg_W = float(np.real(p_gamma5(M_W)))
    okT3 = (pg_gluon == 0.0 and pg_photon == 0.0 and abs(pg_W - 0.5) < 1e-15)
    results["T3_gamma5_projection"] = dict(
        passed=bool(okT3),
        gluon_selfcoupling=pg_gluon, photon=pg_photon, W=pg_W,
        classification=dict(gluon="EVEN (chiral proj = 0)",
                            photon="EVEN (chiral proj = 0)",
                            W="CHIRAL (chiral proj = 1/2)"),
        note="gluon self-coupling chiral projection is EXACTLY 0, same as the "
             "photon; W is the nonzero contrast. Extends F91 table to the vertex")

    # ---- T4: the self-coupling's nontrivial structure is colour only ----
    ba = lpt.bose_antisymmetry()
    okT4 = ba["antisymmetric"]
    results["T4_colour_only_antisymmetry"] = dict(
        passed=bool(okT4), V123=ba["V123"], V_colourswap_12=ba["V_colourswap_12"],
        sum=ba["sum"],
        note="leg colour-swap flips the vertex sign (f^{abc}); the only "
             "nontrivial index of the self-coupling is colour, not branch")

    n = sum(r["passed"] for r in results.values())
    results["summary"] = dict(
        passed=n, total=4, all_pass=(n == 4),
        verdict="C3 UPGRADED: triple-gluon vertex is branch-blind by "
                "construction (no gamma5 component). Gluon 'even' is forced at "
                "the interacting (self-coupling) level, not only free-field.",
        scope="Structural: the gauge sector contains no spinor index, so every "
              "pure-gluon n-point vertex is branch-trivial. Magnitude of the "
              "self-energy (q*/d1, F162/F163) is a separate, orthogonal open item.")
    return results


if __name__ == "__main__":
    import json
    r = run()
    print(json.dumps(r, indent=2, default=str))
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "..", "..", "test-results", "F166_triple_gluon_branch.json")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        json.dump(r, f, indent=2, default=str)
    assert all(r[k]["passed"] for k in
               ("T1_vertex_no_branch_axis", "T2_branch_commutator_zero",
                "T3_gamma5_projection", "T4_colour_only_antisymmetry")), \
        "F166 checks failed"
    print("\nF166: 4/4 PASS")
