#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
baryon_mass_decomposition.py — the Ji-type four-term nucleon-mass decomposition,
built in the model's own sectors, and what the model does and does not support (F402)
=====================================================================================

Answers `docs/theory/notebook-v2/NB2-004-nucleon-mass-field-energy.md`, "New
questions opened" item 2: F122 separates only "quark-mass sum" from "confining
string + kinetic energy" (two terms). The lattice-QCD nucleon-mass decomposition
(Ji 1995; Yang et al., chiQCD, PRL 121, 212001, 2018) has FOUR:

    M = H_E + H_m + H_g + H_a

    H_m  quark-mass term         <N| m psibar psi |N>
    H_E  quark energy            (traceless quark part of T^{00}, less the mass term)
    H_g  gluon field energy      (traceless gluon part of T^{00})
    H_a  trace-anomaly term      (1/4)(M - H_m)      [the trace part]

The construction is fixed by three inputs and two exact identities, so it ports
to any model that supplies them:

  (I1) Trace sum rule at rest (virial: <T^{ii}> = 0 so <T^mu_mu> = M):
           H_m + A = M ,       A = the scale-breaking (anomaly-type) part,
       and Ji's anomaly term is one QUARTER of it:   H_a = (1/4)(M - H_m).
  (I2) The traceless part of T^{00} is 3/4 of the momentum-fraction energy:
           H_E = (3/4)(x_q M - H_m) ,      H_g = (3/4) x_g M ,   x_q + x_g = 1.

  Sum: (3/4)(x_q+x_g)M - (3/4)H_m + H_m + (1/4)(M-H_m) = M  identically.

So the model must supply (a) H_m — a Feynman–Hellmann derivative m dM/dm, and
(b) the momentum fractions x_q, x_g. This module builds them where the model has
them and reports honestly where it does not.

THREE MODEL SECTORS, THREE DIFFERENT VERDICTS
---------------------------------------------
NJL constituent nucleon (F77/F123, M_N = 3 M_c):
    H_m is a real, exact Feynman–Hellmann prediction: sigma_N = 3 m_0 dM_c/dm_0
    (closed form via the implicit gap-equation derivative; verified against a
    finite difference). Dimensional analysis of the gap equation gives the exact
    dilatation identity  M = m_0 dM/dm_0 - 2G dM/dG + Lam dM/dLam  (machine
    precision) — the model's own trace sum rule. The contact term (-2G dM/dG)
    and the regulator term (Lam dM/dLam) are each several times M and OPPOSITE in
    sign, and each depends on whether G or the dimensionless g = G Lam^2 is held
    fixed: neither is meaningful alone. Their sum is Lam dM/dLam at fixed g, which
    Euler's theorem fixes to M - H_m — so the "anomaly-analogue" (M - H_m, 95% of
    M_N) is an IDENTITY, not a dynamical result of the model. Gluons are
    integrated out into G, so x_q = 1, x_g = 0 at the NJL scale Lam_NJL; a gluon
    share can only be generated by evolution (or already be present at Lam_NJL —
    `x_g_start_required` gives how much would be needed).

Momentum-fraction evolution (LO, second moment):
    d x_g/dt = (alpha_s/2pi)[(16/9) x_q - (n_f/3) x_g],  t = ln mu^2, x_q+x_g = 1.
    Closed form x_g(tau) = x_inf (1 - exp(-lam tau)), x_inf = 16/(16+3n_f),
    lam = 16/9 + n_f/3, tau = INT (alpha_s/2pi) d ln mu^2. The model supplies
    alpha_s(mu) (F144 chain, zero free parameters) and a frozen IR coupling
    (F152). Both are compared with the tau the lattice value REQUIRES, for TWO
    lattice targets: (4/3)H_g = 0.49(9) from chiQCD and 0.427(92) from ETMC. The
    starting x_g = 0 at Lam_NJL is the decisive, non-derived input (the classic
    Parisi-Petronzio / Jaffe-Ross low-scale quark-model start).

Cornell three-body string (F122, non-relativistic ECG):
    The only model-native gluon-FIELD energy (string + one-gluon exchange). The
    identities are exact: with <T>, <V_conf>, <V_coul> from the ground vector,
        H_m = 3m - <T>,  H_E = 2<T>,  H_g = <V_conf>/2 + <V_coul>,  H_a = <V_conf>/2,
    Feynman–Hellmann gives m dM/dm = 3m - <T> and sigma dM/dsigma = <V_conf> exactly
    at fixed basis, and the virial theorem 2<T> = <V_conf> - <V_coul> is what makes
    the two constructions (energies vs momentum fractions) agree. The NUMBERS are
    non-relativistic and F122 says so: at its baseline constituent mass the
    quark kinetic energy exceeds the quark mass, so H_m = 3m - <T> < 0 (a
    negative psibar psi — impossible relativistically, psibar psi = m/E > 0).

NOT BUILT: an operator-level H_g / H_a separation (<N|F^2|N> with the running
beta function). That needs a dynamical baryon inside the gauge sector, which is
not in the tree; the model has the beta function (F144) but not that matrix
element. The construction here is the sum-rule + momentum-fraction route.

Exactness: FH / dilatation / virial identities are machine-precision statements;
the mass fractions, sigma term and evolved x_g are quantitative.

Findings: F402.
"""
from __future__ import annotations

import math
from typing import Dict, List

from casim.constants import (G_Lambda2_NJL, Lambda_NJL_GeV, endpoint,
                             m0_current_quark_MeV)
from casim.engine.interactions import running_alpha_s as _RA
from casim.engine.particles import baryon_dynamics as _BAR
from casim.engine.particles import meson as _MES
from casim.numerics import xp

__all__ = [
    "ji_quartet", "lattice_targets", "njl_dI1_dM", "njl_derivatives",
    "njl_nucleon_analog", "cornell_expectations", "cornell_quartet",
    "cornell_fh_residuals", "dglap_asymptote", "x_g_evolved", "tau_required",
    "x_g_start_required",
    "tau_integral", "alpha_s_model", "evolution_scenarios", "report",
]

N_C, N_F = _MES.N_C, _MES.N_F
F122_BASELINE = dict(m=0.785, sigma=1.0, alpha_s=0.5)   # F122 §2 (units of sqrt(sigma))
HALF_RULE = dict(conf_per_pair=0.5, oge_casimir=1.0 / 3.0)   # F122 S6 alternative


# ══════════════════════════════════════════════════════════════════
#  1. The Ji quartet from (M, H_m, x_q) — exact algebra
# ══════════════════════════════════════════════════════════════════

def ji_quartet(M: float, H_m: float, x_q: float) -> Dict[str, float]:
    """H_E, H_m, H_g, H_a from the mass, the mass term and the quark momentum
    fraction. Sums to M identically for any inputs."""
    x_g = 1.0 - x_q
    H_E = 0.75 * (x_q * M - H_m)
    H_g = 0.75 * x_g * M
    H_a = 0.25 * (M - H_m)
    return {"H_E": H_E, "H_m": H_m, "H_g": H_g, "H_a": H_a,
            "sum": H_E + H_m + H_g + H_a, "x_q": x_q, "x_g": x_g, "M": M}


def lattice_targets() -> Dict[str, Dict[str, float]]:
    """Comparison targets, NEVER inputs. Yang et al. (chiQCD), PRL 121, 212001
    (2018), MS-bar 2 GeV, percent of M_N, (stat)(sys) combined in quadrature; H_m
    is u+d+s. Nucleon sigma term (u+d): Hoferichter et al. 2015 and FLAG 2024."""
    def q(a, b):
        return math.hypot(a, b)
    return {
        "H_E_pct": {"value": 33.0, "unc": q(4.0, 4.0)},
        "H_m_pct": {"value": 9.0, "unc": q(2.0, 1.0)},
        "H_g_pct": {"value": 37.0, "unc": q(5.0, 4.0)},
        "H_a_pct": {"value": 23.0, "unc": q(1.0, 1.0)},
        "sigma_piN_hoferichter_MeV": {"value": 59.1, "unc": 3.5},
        "sigma_piN_flag2024_MeV": {"value": 60.9, "unc": 6.5},
        # independent lattice gluon momentum fraction, MS-bar 2 GeV (ETMC,
        # arXiv:2003.08486); the chiQCD-derived value (4/3)H_g is built below
        "x_g_etmc": {"value": 0.427, "unc": 0.092},
    }


# ══════════════════════════════════════════════════════════════════
#  2. NJL constituent nucleon — Feynman–Hellmann and dilatation, closed form
# ══════════════════════════════════════════════════════════════════

def njl_dI1_dM(M: float, Lam: float) -> float:
    """dI1/dM = (M/2pi^2)(Lam/E_Lam - ln((Lam+E_Lam)/M)), closed form."""
    E = math.sqrt(Lam * Lam + M * M)
    return M / (2.0 * math.pi ** 2) * (Lam / E - math.log((Lam + E) / M))


def njl_derivatives(G: float, Lam: float, m0: float) -> Dict[str, float]:
    """M_c and its exact partial derivatives from implicit differentiation of the
    gap equation  M = m0 + 4 G N_c N_f M I1(M)."""
    M = _MES.gap_solve(G, Lam, m0)
    N = N_C * N_F
    I1 = _MES.I1_closed(M, Lam)
    D = 1.0 - 4.0 * G * N * (I1 + M * njl_dI1_dM(M, Lam))
    E = math.sqrt(Lam * Lam + M * M)
    return {
        "M_c": M,
        "dM_dm0": 1.0 / D,
        "dM_dG": 4.0 * N * M * I1 / D,
        "dM_dLam": 4.0 * G * N * M * (Lam * Lam / (2.0 * math.pi ** 2 * E)) / D,
    }


def njl_nucleon_analog(G_Lam2: float = None, Lam: float = None,
                       m0: float = None) -> Dict[str, float]:
    """The NJL analogue of the trace sum rule for M_N = 3 M_c (valence,
    binding neglected as in F123). GeV units."""
    G_Lam2 = float(G_Lambda2_NJL) if G_Lam2 is None else G_Lam2
    Lam = float(Lambda_NJL_GeV) if Lam is None else Lam
    m0 = m0_current_quark_MeV * 1e-3 if m0 is None else m0
    G = G_Lam2 / (Lam * Lam)
    d = njl_derivatives(G, Lam, m0)
    M_N = 3.0 * d["M_c"]
    H_m = 3.0 * m0 * d["dM_dm0"]
    contact = -2.0 * G * 3.0 * d["dM_dG"]       # 2<L_int>, vacuum-subtracted
    regulator = 3.0 * Lam * d["dM_dLam"]        # explicit cutoff dependence
    return {
        **d, "M_N": M_N, "H_m": H_m, "contact": contact, "regulator": regulator,
        "dilatation_sum": H_m + contact + regulator,
        "dilatation_residual": abs(H_m + contact + regulator - M_N) / M_N,
        "H_m_frac": H_m / M_N,
        "anomaly_analogue": M_N - H_m,
        "cancellation_ratio": max(abs(contact), abs(regulator)) / M_N,
    }


# ══════════════════════════════════════════════════════════════════
#  3. Cornell three-body string (F122 engine) — expectation values and identities
# ══════════════════════════════════════════════════════════════════

def _cornell_matrices(basis, m, sigma, alpha_s, conf, oge):
    n = len(basis)
    T = xp.zeros((n, n)); Vc = xp.zeros((n, n)); VC = xp.zeros((n, n))
    S = xp.zeros((n, n))
    for i in range(n):
        for j in range(i, n):
            A, B = basis[i], basis[j]
            C = A + B
            s = _BAR._overlap(C)
            betas = _BAR._beta_pairs(C).values()
            T[i, j] = T[j, i] = _BAR._kinetic_over_S(A, B, C, m) * s
            Vc[i, j] = Vc[j, i] = s * sum(conf * sigma * _BAR._r_over_S(b)
                                          for b in betas)
            VC[i, j] = VC[j, i] = -s * sum(oge * alpha_s * _BAR._inv_r_over_S(b)
                                           for b in betas)
            S[i, j] = S[j, i] = s
    return T, Vc, VC, S


def cornell_expectations(m: float, sigma: float, alpha_s: float, n_mesh: int = 10,
                         conf_per_pair: float = 1.0,
                         oge_casimir: float = 2.0 / 3.0) -> Dict[str, float]:
    """Ground-state E_rel and <T>, <V_conf>, <V_coul> (units of sqrt(sigma)), on a
    non-symmetrised GEM mesh. M = 3m + E_rel."""
    basis = _BAR.make_basis(n1=n_mesh, n2=n_mesh, symmetrize=False)
    T, Vc, VC, S = _cornell_matrices(basis, m, sigma, alpha_s,
                                     conf_per_pair, oge_casimir)
    w, c = _BAR._solve_canonical(T + Vc + VC, S, want_vec=True)
    nrm = c @ S @ c

    def ex(X):
        return float((c @ X @ c) / nrm)

    Tm, Vcm, VCm = ex(T), ex(Vc), ex(VC)
    E = float(w[0])
    return {"E_rel": E, "T": Tm, "V_conf": Vcm, "V_coul": VCm,
            "M": 3.0 * m + E, "m": m, "sigma": sigma, "alpha_s": alpha_s,
            "n_basis": len(basis),
            "energy_partition_residual": abs(E - (Tm + Vcm + VCm))}


def cornell_quartet(ex: Dict[str, float]) -> Dict[str, float]:
    """Ji quartet of the NR string baryon, from the stress-tensor structure of
    the model: string trace 2<V_conf>, Coulomb traceless, NR quark trace m - T."""
    m, T, Vc, VC, M = ex["m"], ex["T"], ex["V_conf"], ex["V_coul"], ex["M"]
    H_m = 3.0 * m - T
    H_E = 2.0 * T
    H_g = 0.5 * Vc + VC
    H_a = 0.5 * Vc
    # momentum-fraction route (I2): x_q from the traceless quark energy
    x_q = (4.0 / 3.0) * (2.25 * m + 1.25 * T) / M
    alt = ji_quartet(M, H_m, x_q)
    return {
        "H_E": H_E, "H_m": H_m, "H_g": H_g, "H_a": H_a,
        "sum_over_M": (H_E + H_m + H_g + H_a) / M,
        "frac": {"H_E": H_E / M, "H_m": H_m / M, "H_g": H_g / M, "H_a": H_a / M},
        "x_q": x_q, "x_g": 1.0 - x_q,
        "virial_residual": (2.0 * T - (Vc - VC)) / M,
        "H_a_vs_quarter_rule": abs(H_a - 0.25 * (M - H_m)) / M,
        "energies_vs_fractions_HE": abs(H_E - alt["H_E"]) / M,
        "H_m_negative": H_m < 0.0,
    }


def cornell_fh_residuals(m: float, sigma: float, alpha_s: float, n_mesh: int = 10,
                         h: float = 1e-4, conf_per_pair: float = 1.0,
                         oge_casimir: float = 2.0 / 3.0) -> Dict[str, float]:
    """Finite-difference vs expectation value:  m dM/dm = 3m - <T>,
    sigma dM/dsigma = <V_conf>, alpha dM/dalpha = <V_coul>, at fixed basis
    (Hellmann–Feynman is exact for a Rayleigh–Ritz eigenvalue)."""
    def M_of(mm, ss, aa):
        return cornell_expectations(mm, ss, aa, n_mesh, conf_per_pair,
                                    oge_casimir)["M"]

    ex = cornell_expectations(m, sigma, alpha_s, n_mesh, conf_per_pair,
                              oge_casimir)
    dm = m * (M_of(m * (1 + h), sigma, alpha_s)
              - M_of(m * (1 - h), sigma, alpha_s)) / (2 * m * h)
    ds = sigma * (M_of(m, sigma * (1 + h), alpha_s)
                  - M_of(m, sigma * (1 - h), alpha_s)) / (2 * sigma * h)
    da = alpha_s * (M_of(m, sigma, alpha_s * (1 + h))
                    - M_of(m, sigma, alpha_s * (1 - h))) / (2 * alpha_s * h)
    M = ex["M"]
    return {
        "m_dM_dm": dm, "expect_3m_minus_T": 3 * m - ex["T"],
        "sigma_dM_dsigma": ds, "expect_V_conf": ex["V_conf"],
        "alpha_dM_dalpha": da, "expect_V_coul": ex["V_coul"],
        "rel_resid_m": abs(dm - (3 * m - ex["T"])) / M,
        "rel_resid_sigma": abs(ds - ex["V_conf"]) / M,
        "rel_resid_alpha": abs(da - ex["V_coul"]) / M,
    }


# ══════════════════════════════════════════════════════════════════
#  4. Momentum-fraction evolution (LO, second moment) and the model's alpha_s
# ══════════════════════════════════════════════════════════════════

def dglap_asymptote(nf: int = 3) -> Dict[str, float]:
    return {"x_g_inf": 16.0 / (16.0 + 3.0 * nf),
            "lam": 16.0 / 9.0 + nf / 3.0}


def x_g_evolved(tau: float, nf: int = 3, x_g0: float = 0.0) -> float:
    """Closed-form LO second-moment evolution of the gluon momentum fraction."""
    a = dglap_asymptote(nf)
    return a["x_g_inf"] + (x_g0 - a["x_g_inf"]) * math.exp(-a["lam"] * tau)


def tau_required(x_g_target: float, nf: int = 3, x_g0: float = 0.0) -> float:
    """The evolution length tau = INT (alpha_s/2pi) d ln mu^2 a given x_g needs."""
    a = dglap_asymptote(nf)
    return -math.log((a["x_g_inf"] - x_g_target) / (a["x_g_inf"] - x_g0)) / a["lam"]


def x_g_start_required(x_g_target: float, tau: float, nf: int = 3) -> float:
    """The gluon share needed at the START scale for evolution length tau to
    reach x_g_target: x_g0 = x_inf + (x_target - x_inf) exp(+lam tau)."""
    a = dglap_asymptote(nf)
    return a["x_g_inf"] + (x_g_target - a["x_g_inf"]) * math.exp(a["lam"] * tau)


def alpha_s_model(mu_GeV: float) -> float:
    """Model alpha_s (F144 chain: g_s = 1/2 at the lattice cutoff, 4-loop MS-bar,
    zero free parameters) at mu, n_f = 3 below m_c and continued upward with
    n_f = 3. NaN below the model's own Landau scale (~0.9 GeV)."""
    ch = _RA.alpha_s_chain(_RA.ALPHA_S_UV, _RA.MU0_GEV, 4)
    return _RA.run_alpha(ch["alpha_mc"], _RA.M_C, mu_GeV, 3, 4)


def tau_integral(alpha_fn, mu0: float, mu1: float, n: int = 400) -> float:
    """INT (alpha_s(mu)/2pi) d ln mu^2 from mu0 to mu1 (trapezoid in ln mu^2)."""
    t0, t1 = math.log(mu0 ** 2), math.log(mu1 ** 2)
    h = (t1 - t0) / n
    vals = [alpha_fn(math.exp(0.5 * (t0 + i * h))) / (2.0 * math.pi)
            for i in range(n + 1)]
    return h * (0.5 * vals[0] + sum(vals[1:-1]) + 0.5 * vals[-1])


def evolution_scenarios(mu_target: float = 2.0, mu_pert_floor: float = 1.0,
                        nf: int = 3) -> Dict[str, object]:
    """Model-native x_g at mu_target, starting from x_g = 0 at Lam_NJL, against
    what the lattice value requires. tau is what the model integrates."""
    lam_njl = float(Lambda_NJL_GeV)
    cache = {}

    def a_model(mu):
        if mu not in cache:
            cache[mu] = alpha_s_model(mu)
        return cache[mu]

    tau_pert = tau_integral(a_model, mu_pert_floor, mu_target)
    a_lo, a_hi = endpoint("alpha_eff_star", "lo"), endpoint("alpha_eff_star", "hi")
    ln_ir = math.log(mu_pert_floor ** 2 / lam_njl ** 2)
    tau_ir = {"lo": a_lo / (2 * math.pi) * ln_ir, "hi": a_hi / (2 * math.pi) * ln_ir}
    lat = lattice_targets()
    targets = {
        "chiqcd": {"value": (4.0 / 3.0) * lat["H_g_pct"]["value"] / 100.0,
                   "unc": (4.0 / 3.0) * lat["H_g_pct"]["unc"] / 100.0},
        "etmc": dict(lat["x_g_etmc"]),
    }
    ln_span = math.log(mu_target ** 2 / lam_njl ** 2)
    tau_model_hi = tau_pert + tau_ir["hi"]
    x_hi = x_g_evolved(tau_model_hi, nf)
    out = {
        "mu0_GeV": lam_njl, "mu_target_GeV": mu_target,
        "tau_perturbative_1_to_2GeV": tau_pert,
        "tau_frozen_IR_band": tau_ir,
        "x_g_perturbative_start_1GeV": x_g_evolved(tau_pert, nf),
        "x_g_with_frozen_IR_lo": x_g_evolved(tau_pert + tau_ir["lo"], nf),
        "x_g_with_frozen_IR_hi": x_hi,
        "targets": {},
        "alpha_s_at_1GeV": a_model(1.0), "alpha_s_at_2GeV": a_model(2.0),
    }
    for name, t in targets.items():
        tr = tau_required(t["value"], nf)
        out["targets"][name] = {
            "x_g": t["value"], "x_g_unc": t["unc"],
            "pull_of_model_hi": (x_hi - t["value"]) / t["unc"],
            "tau_required": tr,
            "mean_alpha_required": tr * 2 * math.pi / ln_span,
            "tau_deficit_factor_hi": tr / tau_model_hi,
            # the gluon share the NJL start would need at Lambda_NJL for the
            # model's own tau to reach the target (x_g0 = 0 is a choice)
            "x_g0_required_at_LamNJL": x_g_start_required(
                t["value"], tau_model_hi, nf),
        }
    # kept for continuity: the chiQCD-derived target as the headline
    out["x_g_lattice"] = out["targets"]["chiqcd"]["x_g"]
    out["x_g_lattice_unc"] = out["targets"]["chiqcd"]["x_g_unc"]
    out["tau_required_lattice"] = out["targets"]["chiqcd"]["tau_required"]
    out["mean_alpha_required"] = out["targets"]["chiqcd"]["mean_alpha_required"]
    out["tau_deficit_factor_hi"] = out["targets"]["chiqcd"]["tau_deficit_factor_hi"]
    out["x_g_start_sensitivity"] = {
        f"x_g0={x0}": x_g_evolved(tau_model_hi, nf, x_g0=x0)
        for x0 in (0.0, 0.1, 0.2, 0.3)}
    return out


# ══════════════════════════════════════════════════════════════════
#  5. The verdict
# ══════════════════════════════════════════════════════════════════

def _pull(model, target):
    return (model - target["value"]) / target["unc"]


def report(n_mesh: int = 10) -> Dict[str, object]:
    lat = lattice_targets()
    nj = njl_nucleon_analog()
    ev = evolution_scenarios()
    sig_MeV = nj["H_m"] * 1e3
    # NJL nucleon at Lam_NJL (x_q=1) and after model-native evolution
    q0 = ji_quartet(nj["M_N"], nj["H_m"], 1.0)
    q_ir = ji_quartet(nj["M_N"], nj["H_m"], 1.0 - ev["x_g_with_frozen_IR_hi"])
    q_pt = ji_quartet(nj["M_N"], nj["H_m"], 1.0 - ev["x_g_perturbative_start_1GeV"])

    def pct(q):
        return {k: 100.0 * q[k] / q["M"] for k in ("H_E", "H_m", "H_g", "H_a")}

    cbase = cornell_expectations(n_mesh=n_mesh, **F122_BASELINE)
    chalf = cornell_expectations(n_mesh=n_mesh, **F122_BASELINE, **HALF_RULE)
    qb, qh = cornell_quartet(cbase), cornell_quartet(chalf)
    return {
        "finding": "F402",
        "lattice_targets": lat,
        "njl": nj,
        "sigma_N_MeV": sig_MeV,
        "sigma_pull_vs_hoferichter": _pull(sig_MeV, lat["sigma_piN_hoferichter_MeV"]),
        "sigma_pull_vs_flag2024": _pull(sig_MeV, lat["sigma_piN_flag2024_MeV"]),
        "njl_quartet_pct_at_LamNJL": pct(q0),
        "njl_quartet_pct_evolved_pert": pct(q_pt),
        "njl_quartet_pct_evolved_frozenIR_hi": pct(q_ir),
        "evolution": ev,
        "cornell_baseline": {**cbase, "quartet": qb},
        "cornell_half_rule": {**chalf, "quartet": qh},
        "H_a_model_pct": 100.0 * 0.25 * (nj["M_N"] - nj["H_m"]) / nj["M_N"],
        "H_a_pull": _pull(100.0 * 0.25 * (nj["M_N"] - nj["H_m"]) / nj["M_N"],
                          lat["H_a_pct"]),
    }


if __name__ == "__main__":       # pragma: no cover — artifact write is guarded
    import json
    print(json.dumps(report(), indent=2, default=str))
