"""Shared text helpers for `casim index` — roadmap C8.1.

Ported verbatim from `tools/regen_indexes.py` rather than rewritten, so the
generated markdown stays byte-comparable across the move. The one rule worth
restating because breaking it breaks every table in the repo:

**Pipes are escaped.** A literal ``|`` in extracted text (``|k|`` for a
magnitude, ``|ψ|²``, absolute-value bars) is the Markdown column delimiter, so
:func:`esc` rewrites it as ``\\|``. CLAUDE.md's rule about writing safe finding
*titles* still applies to hand-written content — this only protects the
generated cells.
"""
from __future__ import annotations

import ast
import os
import re

CAP = 160                      # max summary length in a table cell

HEADER_NOTE = ("*Auto-generated by `casim index` (`casim.index`) — do not edit "
               "by hand.*")


def clean(text: str) -> str:
    text = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', text)    # [txt](url) -> txt
    text = re.sub(r'\[\[([^\]]+)\]\]', r'\1', text)          # [[link]] -> link
    return re.sub(r'\s+', ' ', text).strip()


def truncate(text: str, n: int = CAP) -> str:
    text = text.strip()
    if len(text) <= n:
        return text
    cut = text[:n].rsplit(' ', 1)[0].rstrip(' ,;:.—–-')
    return (cut or text[:n]) + '…'


def esc(text: str) -> str:
    return text.replace("|", "\\|")


def read_head(path: str, nbytes: int = 4000) -> str:
    with open(path, encoding="utf-8", errors="replace") as fh:
        return fh.read(nbytes)


def first_doc_line(path: str) -> str:
    """First line of a module docstring, safe even if the file will not run."""
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            tree = ast.parse(fh.read())
        doc = ast.get_docstring(tree) or ""
    except (SyntaxError, OSError):
        doc = ""
    if not doc:
        return ""
    return truncate(clean(doc.strip().splitlines()[0]))


def md_title(path: str) -> str:
    content = read_head(path, 2000)
    m = re.search(r'^#\s+(.+)', content, re.MULTILINE)
    if m:
        return truncate(clean(m.group(1)))
    for line in content.splitlines():
        line = line.strip()
        if line and not line.startswith(('#', '`', '>', '|', '!', '---')):
            return truncate(clean(line))
    return ""


def repo_root() -> str:
    """Repo root, from this file's location (src/casim/index/common.py)."""
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.dirname(os.path.dirname(os.path.dirname(here)))
