# ===== deprecated/code backup =====================================
# source     : ca-simulation/ca_lattice.py
# migrated   : 2026-07-30 - 13:53
# target     : src/casim/engine/lattice/geometry.py
# manifest   : docs/design/module-migration-manifest.yaml  (id: ca_lattice.py)
# stripped   : (nothing)
# reason     : D6 consolidation; no symbols removed
#
# Everything below this header is BYTE-IDENTICAL to the file as it stood
# before migration. Roadmap C0.5 / D10.
# ==================================================================
"""
ca_lattice.py  —  Lattice configuration and k-grid utilities
=============================================================
Central location for all k-space grid construction.  Every propagator
and stepper should call `make_kgrid_*` here rather than recomputing
fftfreq / meshgrid inline.

Key exports
-----------
LatticeConfig      — dataclass holding shape + cached k-grids
make_kgrid_1d      — 1D k-axis (1D)
make_kgrid_2d      — (KX, KY) meshgrid for a 2D lattice
make_kgrid_3d      — (KX, KY, KZ) meshgrid for a 3D lattice
kgrid_from_shape   — dispatch on ndim (1, 2, or 3)
good_fft_sizes     — return N values near a target with low FFT cost

BCC geometry (F265) — the single source of truth for the real-space BCC
lattice, so that "BCC-ness" is no longer injected only by the momentum-space
`ca_bcc._bcc_uvec`:

BCC_HOP_DIRS       — the 8 nearest-neighbour body diagonals d ∈ {±1}³
BCC_LINK_AXES      — the 4 independent link axes (d and −d share one field)
BCC_PLAQUETTES     — the 6 minimal 4-bond plaquette orientations
BCC_PLAQ_NORMALS   — their ⟨110⟩ normals (one per face-diagonal axis)
BCC_PLAQ_AREA      — 2√2, the |d1 × d2| of every minimal plaquette
BCC_INDEX_IN_Z3    — 4: only 1/4 of the cubic array sites are BCC sites
BCC_BZ_COPIES      — 4: the cube [−π,π)³ holds 4 copies of the true BZ
bcc_site_mask      — boolean mask of genuine BCC sites on a cubic array
bcc_reciprocal_basis — the fcc reciprocal generators π(1,1,0), …
bcc_bz_mask        — mask selecting one true (rhombic-dodecahedral) BZ
make_kgrid_bcc     — k-grid + BZ mask + integration weight

Design note
-----------
For 10× scaling the expensive part is *not* recomputing the k-grid
(that's O(N) trig) but recomputing the full unitary U(k) on every step.
The k-grid and U(k) are fixed once the lattice shape is fixed, so this
module serves as the single source of truth for k-grid construction that
`ca_propagator.py` caches into propagator objects.
"""

import math
import itertools
import numpy as np
from dataclasses import dataclass, field
from typing import Optional, Tuple, Union

from ca_fft import fftfreq, memory_estimate


# ──────────────────────────────────────────────────────────────────
#  Low-level k-grid builders
# ──────────────────────────────────────────────────────────────────

def make_kgrid_1d(L: int) -> np.ndarray:
    """Return the 1D k-axis for a lattice of size L (angular freq units)."""
    return fftfreq(L) * 2.0 * math.pi


def make_kgrid_2d(Lx: int, Ly: int) -> Tuple[np.ndarray, np.ndarray]:
    """
    Return (KX, KY) meshgrid arrays of shape (Lx, Ly).

    k_x runs over  2π·{0, 1/Lx, …, (Lx−1)/Lx, −(Lx/2)/Lx, …, −1/Lx}
    (standard FFT frequency convention).
    """
    kx = fftfreq(Lx) * 2.0 * math.pi
    ky = fftfreq(Ly) * 2.0 * math.pi
    return np.meshgrid(kx, ky, indexing='ij')


def make_kgrid_3d(Lx: int, Ly: int, Lz: int,
                  ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Return (KX, KY, KZ) meshgrid arrays of shape (Lx, Ly, Lz).
    """
    kx = fftfreq(Lx) * 2.0 * math.pi
    ky = fftfreq(Ly) * 2.0 * math.pi
    kz = fftfreq(Lz) * 2.0 * math.pi
    return np.meshgrid(kx, ky, kz, indexing='ij')


def kgrid_from_shape(shape: tuple):
    """
    Dispatch to make_kgrid_1d / _2d / _3d based on len(shape).

    Returns a tuple of ndarray meshgrid components.
    """
    ndim = len(shape)
    if ndim == 1:
        return (make_kgrid_1d(shape[0]),)
    if ndim == 2:
        return make_kgrid_2d(*shape)
    if ndim == 3:
        return make_kgrid_3d(*shape)
    raise ValueError(f"kgrid_from_shape: ndim={ndim} not supported (1–3 only).")


# ══════════════════════════════════════════════════════════════════
#  BCC real-space geometry  (F265)
# ══════════════════════════════════════════════════════════════════
#
# Conventions (all verified in tests/findings/test_F265_bcc_gauge_geometry.py):
#
#   Sites.  Take the conventional cubic cell to have side 2, so the BCC
#   nearest-neighbour hop is the integer vector d ∈ {±1}³ and `np.roll` by d
#   is an *exact* lattice translation.  The lattice generated by the eight d
#   is {n ∈ ℤ³ : n_x ≡ n_y ≡ n_z (mod 2)} — "all components the same parity",
#   which is index 4 in ℤ³.  So on a plain cubic array only **1/4** of the
#   sites are BCC sites (the all-even and all-odd corners); the other 3/4 are
#   not lattice points at all.
#
#   Brillouin zone.  The reciprocal lattice is **fcc**, generated by
#   π(1,1,0), π(1,0,1), π(0,1,1); the true BZ has volume 2π³ = (2π)³/4 and is
#   a rhombic dodecahedron, so the cube [−π,π)³ holds exactly 4 copies of it.
#   (Independently established as F264 row 326.)
#
#   Links and plaquettes.  There are no 3-bond closed loops (three vectors
#   with all-odd components cannot sum to zero), so the minimal gauge loop is
#   a **4-bond rhombus** with sides (d1, d2), d2 ≠ ±d1.  Every such rhombus
#   has |d1 × d2| = 2√2, its normal lies along a ⟨110⟩ face-diagonal axis, and
#   modulo translation there are exactly **6 orientations** forming a single
#   O_h orbit — in bijection with the 6 face-diagonal axes.
#
#   This is what replaces the pre-F265 "6 effective SC links from BCC pairs"
#   construction, whose three ⟨100⟩-plane composite plaquettes are blind to
#   1/3 of the curvature-carrying link degrees of freedom (F265 §K).

BCC_HOP_DIRS: Tuple[Tuple[int, int, int], ...] = tuple(
    itertools.product((1, -1), repeat=3))          # 8 nearest neighbours

#: The 4 independent link axes.  A link field is stored per axis; the
#: opposite direction is recovered by  U_{−d}(x) = U_d(x − d)†, equivalently
#: U_d(x) = U_{−d}(x + d)†.
BCC_LINK_AXES: Tuple[Tuple[int, int, int], ...] = (
    (1, 1, 1), (1, 1, -1), (1, -1, 1), (-1, 1, 1))

#: Only 1/4 of a cubic array's sites are genuine BCC sites.
BCC_INDEX_IN_Z3 = 4
#: The cube [−π,π)³ holds this many copies of the true (fcc-reciprocal) BZ.
BCC_BZ_COPIES = 4
#: |d1 × d2| for every minimal 4-bond plaquette.
BCC_PLAQ_AREA = 2.0 * math.sqrt(2.0)


def _bcc_plaquette_reps():
    """Enumerate the 6 minimal-plaquette orientations modulo translation.

    A rhombus with sides (d1, d2) based at x has the same four corners as the
    rhombus (−d1, d2) based at x+d1, (−d1, −d2) based at x+d1+d2, and
    (d1, −d2) based at x+d2.  Quotienting the 24 non-antipodal pairs by that
    4-fold corner relabelling leaves 6 classes.
    """
    def cls(d1, d2):
        neg = lambda v: tuple(-c for c in v)
        quad = [(d1, d2), (neg(d1), d2), (neg(d1), neg(d2)), (d1, neg(d2))]
        return frozenset(frozenset((a, b)) for a, b in quad)

    seen, reps = set(), []
    for d1, d2 in itertools.combinations(BCC_HOP_DIRS, 2):
        if all(a == -b for a, b in zip(d1, d2)):
            continue                                # antipodal → backtrack
        key = cls(d1, d2)
        if key not in seen:
            seen.add(key)
            reps.append((d1, d2))
    return tuple(reps)


#: The 6 minimal 4-bond plaquette orientations as (d1, d2) side pairs.
BCC_PLAQUETTES: Tuple[Tuple[Tuple[int, int, int], Tuple[int, int, int]], ...] \
    = _bcc_plaquette_reps()

#: Half-normals m = (d1 × d2)/2 of BCC_PLAQUETTES — the 6 ⟨110⟩ axes.
BCC_PLAQ_NORMALS: Tuple[Tuple[int, int, int], ...] = tuple(
    tuple(int(c) for c in np.cross(np.array(d1), np.array(d2)) // 2)
    for d1, d2 in BCC_PLAQUETTES)

#: Labels for the 6 orientations, e.g. 'n110', 'n1m10' (m = minus).
def _nlabel(m):
    return 'n' + ''.join(('m1' if c < 0 else str(c)) for c in m)


BCC_PLAQ_LABELS: Tuple[str, ...] = tuple(_nlabel(m) for m in BCC_PLAQ_NORMALS)


def bcc_site_mask(shape: Tuple[int, int, int]) -> np.ndarray:
    """Boolean mask of genuine BCC sites on a cubic array of `shape`.

    True where all three integer coordinates have the same parity.  Exactly
    1/4 of the entries are True when every extent is even.
    """
    Lx, Ly, Lz = shape
    ix = np.arange(Lx)[:, None, None] % 2
    iy = np.arange(Ly)[None, :, None] % 2
    iz = np.arange(Lz)[None, None, :] % 2
    return (ix == iy) & (iy == iz)


def bcc_reciprocal_basis() -> np.ndarray:
    """The fcc reciprocal-lattice generators, shape (3, 3) — rows are G_i."""
    return math.pi * np.array([[1, 1, 0], [1, 0, 1], [0, 1, 1]], dtype=float)


def bcc_bz_volume() -> float:
    """Volume of the true BCC Brillouin zone: 2π³ = (2π)³/4."""
    return abs(float(np.linalg.det(bcc_reciprocal_basis())))


def bcc_bz_mask(KX: np.ndarray, KY: np.ndarray, KZ: np.ndarray) -> np.ndarray:
    """Mask selecting one true BZ (the rhombic dodecahedron) from a cubic grid.

    On the cubic FFT grid k = 2π n/L the fcc reciprocal lattice reduces to the
    order-4 subgroup of index shifts

        {(0,0,0), (h,h,0), (h,0,h), (0,h,h)}   mod L,   h = L/2,

    because G = π m corresponds to n = mL/2 and only m mod 2 matters (with
    Σm even).  Each of the L³/4 cosets is represented by its member of
    smallest |k| (flat index breaking ties), which is the first-BZ point.
    Hence `bcc_bz_mask(...).sum() == KX.size // BCC_BZ_COPIES` exactly.

    Requires every extent to be even.
    """
    shape = KX.shape
    if any(L % 2 for L in shape):
        raise ValueError(f"bcc_bz_mask: all extents must be even, got {shape}")
    hx, hy, hz = (L // 2 for L in shape)
    shifts = ((0, 0, 0), (hx, hy, 0), (hx, 0, hz), (0, hy, hz))

    d2 = np.round(KX ** 2 + KY ** 2 + KZ ** 2, 9)
    flat = np.arange(KX.size, dtype=np.int64).reshape(shape)

    best_d2, best_flat = None, None
    for s in shifts:
        rd = np.roll(d2, tuple(-c for c in s), axis=(0, 1, 2))
        rf = np.roll(flat, tuple(-c for c in s), axis=(0, 1, 2))
        if best_d2 is None:
            best_d2, best_flat = rd.copy(), rf.copy()
        else:
            better = (rd < best_d2) | ((rd == best_d2) & (rf < best_flat))
            best_d2 = np.where(better, rd, best_d2)
            best_flat = np.where(better, rf, best_flat)
    return (d2 == best_d2) & (flat == best_flat)


def make_kgrid_bcc(Lx: int, Ly: int, Lz: int):
    """Return (KX, KY, KZ, in_bz, weight) for a BCC lattice.

    The grid itself is the ordinary cubic FFT grid — that is what the FFT
    needs — but `in_bz` marks one true (rhombic-dodecahedral) BZ and `weight`
    is the factor that turns a naive cube average into a BZ average.

    Any Brillouin-zone integral for the BCC walk must either restrict to
    `in_bz` or divide by `BCC_BZ_COPIES`; integrating over the full cube and
    treating it as one BZ over-counts by exactly 4 (F265 §Z).
    """
    KX, KY, KZ = make_kgrid_3d(Lx, Ly, Lz)
    return KX, KY, KZ, bcc_bz_mask(KX, KY, KZ), 1.0 / BCC_BZ_COPIES


# ──────────────────────────────────────────────────────────────────
#  LatticeConfig dataclass
# ──────────────────────────────────────────────────────────────────

@dataclass
class LatticeConfig:
    """
    Immutable description of a simulation lattice.

    Parameters
    ----------
    shape : tuple of int
        Lattice dimensions (Lx,) or (Lx, Ly) or (Lx, Ly, Lz).
    cache_kgrid : bool
        If True (default), the k-grid is computed once on init and
        stored in `self.kgrid`.  For very large lattices (L ≥ 512)
        you may want False to avoid allocating the meshgrid unless
        the propagator is building U(k).

    Attributes
    ----------
    shape        : tuple of int
    ndim         : int (1, 2, or 3)
    N            : int  (total number of lattice points)
    kgrid        : tuple of ndarray | None  (cached meshgrid)
    delta_k      : tuple of float  (bin spacing in k per axis)
    """
    shape: Tuple[int, ...]
    cache_kgrid: bool = True
    kgrid: Optional[Tuple] = field(default=None, init=False, repr=False)

    def __post_init__(self):
        self.ndim = len(self.shape)
        self.N = math.prod(self.shape)
        # bin spacings
        self.delta_k = tuple(2.0 * math.pi / L for L in self.shape)
        if self.cache_kgrid:
            self.kgrid = kgrid_from_shape(self.shape)

    # ── convenience constructors ────────────────────────────────────

    @classmethod
    def cubic(cls, L: int, **kwargs) -> 'LatticeConfig':
        """Create an L×L×L cubic 3D lattice."""
        return cls((L, L, L), **kwargs)

    @classmethod
    def square(cls, L: int, **kwargs) -> 'LatticeConfig':
        """Create an L×L square 2D lattice."""
        return cls((L, L), **kwargs)

    # ── memory reporting ─────────────────────────────────────────────

    def memory(self, n_fields: int = 1,
               dtype=np.complex128) -> dict:
        """
        Estimate RAM for `n_fields` spinor component arrays on this lattice.

        Example (3D BCC Dirac — 4 components) ::

            cfg = LatticeConfig.cubic(64)
            cfg.memory(n_fields=4)
            # {'bytes': 67108864, 'MB': 67.1, 'GB': 0.067}
        """
        return memory_estimate(self.shape, n_fields=n_fields, dtype=dtype)

    def propagator_cache_memory(self, n_unitary_blocks: int = 8,
                                dtype=np.complex128) -> dict:
        """
        Estimate RAM for a cached propagator (e.g. 8 complex arrays for
        the BCC Dirac 4×4 unitary split into independent blocks).
        """
        return memory_estimate(self.shape,
                               n_fields=n_unitary_blocks, dtype=dtype)

    # ── scaling helpers ──────────────────────────────────────────────

    def scaled(self, factor: int) -> 'LatticeConfig':
        """Return a new LatticeConfig with all dimensions multiplied by factor."""
        return LatticeConfig(
            tuple(L * factor for L in self.shape),
            cache_kgrid=self.cache_kgrid,
        )

    def __repr__(self) -> str:
        mem = self.memory(n_fields=1)['MB']
        return (f"LatticeConfig(shape={self.shape}, N={self.N}, "
                f"delta_k={tuple(f'{dk:.4f}' for dk in self.delta_k)}, "
                f"~{mem:.1f} MB/field)")


# ──────────────────────────────────────────────────────────────────
#  Good FFT sizes
# ──────────────────────────────────────────────────────────────────

def _fft_cost(n: int) -> float:
    """
    Rough FFT cost proxy: n × log₂(n).  Valid for power-of-2 and smooth
    (only 2, 3, 5, 7 prime factors) sizes that most FFT libraries handle
    efficiently.
    """
    return n * math.log2(n)


def _is_smooth(n: int, primes=(2, 3, 5, 7)) -> bool:
    """Return True if n has no prime factors outside `primes`."""
    for p in primes:
        while n % p == 0:
            n //= p
    return n == 1


def good_fft_sizes(target: int,
                   window: int = 50,
                   primes: tuple = (2, 3, 5, 7)) -> list:
    """
    Return all integers in [target, target+window] whose only prime
    factors are in `primes`, sorted by FFT cost n×log₂(n).

    These are the sizes where FFTW / scipy.fft are fastest.

    Parameters
    ----------
    target : int
        Minimum desired size.
    window : int
        Search range above target.
    primes : tuple
        Allowed prime factors.

    Returns
    -------
    list of int, sorted ascending by cost.

    Example
    -------
    >>> good_fft_sizes(100)
    [100, 108, 112, 125, 128, ...]
    """
    results = [n for n in range(target, target + window + 1)
               if _is_smooth(n, primes)]
    results.sort(key=_fft_cost)
    return results


def next_good_fft_size(target: int,
                       primes: tuple = (2, 3, 5, 7)) -> int:
    """
    Return the smallest integer ≥ target with only prime factors in `primes`.

    Use this to round up lattice dimensions to FFT-optimal sizes.

    Example
    -------
    >>> next_good_fft_size(100)    # → 100 (= 4 × 25 = 2² × 5²)
    100
    >>> next_good_fft_size(101)    # → 108 (= 4 × 27 = 2² × 3³)
    108
    """
    n = target
    while not _is_smooth(n, primes):
        n += 1
    return n


# ──────────────────────────────────────────────────────────────────
#  Scaling table — quick survey for planning
# ──────────────────────────────────────────────────────────────────

def print_scaling_table(base_L: int = 64,
                        factors: tuple = (1, 2, 4, 5, 8, 10)):
    """
    Print a scaling table showing memory and FFT floor for multiples
    of base_L in 3D with a 4-spinor (Dirac) field.

    Usage::

        from ca_lattice import print_scaling_table
        print_scaling_table(64)
    """
    from ca_fft import fft_floor_estimate
    print(f"{'Scale':>7} {'L':>6} {'N (M pts)':>12} "
          f"{'4-spinor RAM':>14} {'FFT floor':>12} "
          f"{'Prop cache (8 blk)':>20}")
    print("-" * 80)
    for fac in factors:
        L = base_L * fac
        shape = (L, L, L)
        N = L ** 3
        mem4 = memory_estimate(shape, n_fields=4)
        mem8 = memory_estimate(shape, n_fields=8)
        floor = fft_floor_estimate(shape)
        print(f"{fac:>7}× {L:>6}  {N/1e6:>10.1f}M "
              f"  {mem4['GB']:>8.2f} GB "
              f"   {floor:>10.1e} "
              f"    {mem8['GB']:>8.2f} GB")


if __name__ == '__main__':
    import sys
    print("=== LatticeConfig demo ===")
    cfg = LatticeConfig.cubic(64)
    print(cfg)
    print(f"  4-spinor: {cfg.memory(4)['MB']:.1f} MB")
    print(f"  prop cache (8 blocks): {cfg.propagator_cache_memory(8)['MB']:.1f} MB")
    print()
    print("=== Scaling table (base L=64) ===")
    print_scaling_table(64)
    print()
    print("=== Good FFT sizes near 320 ===")
    print(good_fft_sizes(300, window=60))
