# ===== deprecated/code backup =====================================
# source     : ca-simulation/derive_colour_condensate.py
# migrated   : 2026-07-30 - 16:06
# target     : src/casim/engine/particles/derive_colour_condensate.py
# manifest   : docs/design/module-migration-manifest.yaml  (id: derive_colour_condensate.py)
# stripped   : (nothing)
# reason     : D6 consolidation; no symbols removed
#
# Everything below this header is BYTE-IDENTICAL to the file as it stood
# before migration. Roadmap C0.5 / D10.
# ==================================================================
"""
derive_colour_condensate.py — the colour-magnetic condensate derived, not assumed (F88)
=======================================================================================

Created: 2026-06-04

F86 (colour-dielectric / dual superconductor) flagged one research risk:
"Colour-magnetic condensate assumed, not derived."  This script closes the
algebraic half of that gap with four sympy-exact derivations, all driven by
the *model's own* ingredients — the Yang–Mills self-coupling through the
structure constants epsilon^{abc} (the SU(2) reduction of F43's f^{abc}) and
the compactness of the link variables.

  D1 — Nielsen–Olesen instability (the vacuum is FORCED to condense).
       Linearising the full Yang–Mills equation of motion around a constant
       chromomagnetic background B (colour-3, symmetric gauge), the charged
       (off-diagonal) gluon with spin aligned along B and the lowest-Landau-
       level profile psi = exp(-gB(x^2+y^2)/4) is an EXACT growing solution

           W_mu(t,x,y) = e^{gamma t} psi(x,y) eps_mu,   gamma^2 = +gB.

       Omega^2 = -gB < 0: in F26 language the (E,B) rotation rate of this
       mode is imaginary — the pair does not rotate, it grows.  The trivial
       (zero-field) vacuum is unstable against condensation.

  D1b — Scalar control: the SAME background and SAME Landau profile for a
       charged *scalar* (no spin term) gives omega^2 = +gB > 0 (stable).
       The difference 2gB between vector and scalar is the anomalous
       chromomagnetic moment (gyromagnetic factor 2) generated by the
       epsilon^{abc} self-coupling — i.e. the instability comes precisely
       from the non-Abelian structure constants F43 validated.

  D2 — Savvidy one-loop energy (condensation is energetically FAVOURED).
       Hurwitz-zeta regularisation of the charged-vector Landau mode sum:

           Re dV(B) = (11/96 pi^2) g^2 B^2 [ ln(gB/mu^2) - 1/2 ]   (SU(2))

       The log coefficient 11/96pi^2 is EXACT (zeta_H(-1,a) = -B_2(a)/2) and
       positive == asymptotic freedom; hence V(B) = B^2/2 + dV(B) has a
       non-trivial minimum B_min > 0 with V(B_min) < 0 for EVERY g > 0.
       The tachyonic level also gives Im V = g^2 B^2/16 pi > 0 (in our
       conventions): the perturbative vacuum literally decays.

  D3 — Dual sine-Gordon scaffolding for the monopole route (what condenses).
       For the dual field chi with L = (kappa/2)(d chi)^2 + 2z(1 - cos chi):
         * Debye / dual-photon mass:  m_D^2 = 2z/kappa            (exact)
         * BPS kink (dual-string) tension: sigma_dual = 8 sqrt(2 kappa z)
           (exact, Bogomolny completion — same trick as F86 CD1)
       With Polyakov's kappa = beta/(4pi^2) for compact U(1)_3 this turns a
       measured monopole density (test battery, CC6/CC7) into the F86
       condensate VEV  v = m_D / e  — the object F86 had to assume.

Run:  python derive_colour_condensate.py
Output: prints each certificate and exits non-zero on any failure.
All results are exact symbolic zeros (Tier 1) unless stated.

Cross-refs: F43 (f^abc dynamical gluons), F86 (dual superconductor, sigma =
2 pi v^2 n), F26 (c = rotation rate), F64 (dielectric mechanism).
"""

import sys
import sympy as sp


# ------------------------------------------------------------------
# shared symbols
# ------------------------------------------------------------------
t, x, y, z = sp.symbols('t x y z', real=True)
g, B = sp.symbols('g B', positive=True)
gamma = sp.Symbol('gamma', positive=True)
ep = sp.Symbol('epsilon')          # linearisation bookkeeping parameter

COORDS = (t, x, y, z)
ETA = sp.diag(1, -1, -1, -1)       # mostly-minus metric

# SU(2) structure constants eps^{abc} (the a,b,c = 1..3 reduction of F43's f^abc)
def eps3(a, b, c):
    return sp.LeviCivita(a, b, c)


# ------------------------------------------------------------------
# D1 / D1b — Nielsen–Olesen instability from the linearised YM EOM
# ------------------------------------------------------------------
def _ym_field_strength(A):
    """F^a_{mu nu} = d_mu A^a_nu - d_nu A^a_mu + g eps^{abc} A^b_mu A^c_nu.

    A: dict a -> [A^a_t, A^a_x, A^a_y, A^a_z] (sympy expressions).
    Returns F as nested dict F[a][mu][nu] (lower indices)."""
    F = {}
    for a in (1, 2, 3):
        F[a] = [[sp.S.Zero] * 4 for _ in range(4)]
        for mu in range(4):
            for nu in range(4):
                expr = sp.diff(A[a][nu], COORDS[mu]) - sp.diff(A[a][mu], COORDS[nu])
                for b in (1, 2, 3):
                    for c in (1, 2, 3):
                        e = eps3(a, b, c)
                        if e != 0:
                            expr += g * e * A[b][mu] * A[c][nu]
                F[a][mu][nu] = expr
    return F


def _ym_eom(A):
    """E^{nu,a} = d_mu F^{mu nu,a} + g eps^{abc} A^b_mu F^{mu nu,c}  (raised
    with eta).  Returns dict a -> [E^{nu=t..z}]."""
    F = _ym_field_strength(A)
    # raise both indices: F^{mu nu} = eta^{mu alpha} eta^{nu beta} F_{alpha beta}
    Fup = {}
    for a in (1, 2, 3):
        Fup[a] = [[ETA[mu, mu] * ETA[nu, nu] * F[a][mu][nu]
                   for nu in range(4)] for mu in range(4)]
    E = {}
    for a in (1, 2, 3):
        E[a] = []
        for nu in range(4):
            expr = sp.S.Zero
            for mu in range(4):
                expr += sp.diff(Fup[a][mu][nu], COORDS[mu])
                for b in (1, 2, 3):
                    for c in (1, 2, 3):
                        e = eps3(a, b, c)
                        if e != 0:
                            expr += g * e * A[b][mu] * Fup[c][mu][nu]
            E[a].append(expr)
    return E


def derive_D1_nielsen_olesen():
    """Exact growing mode of the linearised YM EOM around constant B."""
    psi = sp.exp(-g * B * (x**2 + y**2) / 4)
    grow = sp.exp(gamma * t)

    results = {}
    for spin_sign, label in ((+1, 'aligned'), (-1, 'anti-aligned')):
        # background (colour-3, symmetric gauge) + charged fluctuation.
        # W_mu = (A^1_mu - i A^2_mu)/sqrt2 with polarisation
        #   eps = (0, 1, i*spin_sign, 0)/sqrt2  -> real fields:
        #   A^1_x = e^{gt} psi,  A^2_y = -spin_sign * e^{gt} psi.
        zero = sp.S.Zero
        A = {
            1: [zero, ep * grow * psi, zero, zero],
            2: [zero, zero, -spin_sign * ep * grow * psi, zero],
            3: [zero, -B * y / 2, B * x / 2, zero],
        }
        E = _ym_eom(A)
        # linearise: O(ep) coefficient of every EOM component
        lin = [sp.expand(sp.diff(comp, ep).subs(ep, 0))
               for a in (1, 2, 3) for comp in E[a]]
        # substitute the dispersion gamma^2 = +gB and check exact closure
        residuals = [sp.simplify(c.subs(gamma, sp.sqrt(g * B))) for c in lin]
        closes = all(r == 0 for r in residuals)
        results[label] = closes
        # for the aligned (unstable) mode also verify it does NOT close at a
        # wrong dispersion, so the certificate is non-vacuous
        if spin_sign == +1:
            wrong = [sp.simplify(c.subs(gamma, sp.sqrt(2 * g * B))) for c in lin]
            results['nonvacuous'] = any(w != 0 for w in wrong)
    return results


def derive_D1b_scalar_control():
    """Charged scalar (minimal coupling, no spin term) on the same Landau
    profile: -D^2 psi = +gB psi exactly  ->  omega^2 = +gB > 0 (stable)."""
    psi = sp.exp(-g * B * (x**2 + y**2) / 4)
    Ax = -B * y / 2
    Ay = B * x / 2
    # D_j = d_j - i g Abar_j acting on the charged scalar
    Dx = sp.diff(psi, x) - sp.I * g * Ax * psi
    Dy = sp.diff(psi, y) - sp.I * g * Ay * psi
    lap = (sp.diff(Dx, x) - sp.I * g * Ax * Dx) + (sp.diff(Dy, y) - sp.I * g * Ay * Dy)
    residual = sp.simplify(-lap - g * B * psi)   # -D^2 psi - gB psi == 0
    return residual == 0


# ------------------------------------------------------------------
# D2 — Savvidy one-loop potential via Hurwitz zeta (exact coefficients)
# ------------------------------------------------------------------
def derive_D2_savvidy():
    """Charged-vector Landau sum, zeta_H-regularised.

    Per 2D Landau level of mass^2 M^2 (degeneracy gB/2pi per area) the
    regularised (1+1)D vacuum-energy density carries the universal term
    -(M^2/8pi) ln(mu^2/M^2); summing M^2_{n,s} = gB(2n+1+2s) over n with
    zeta_H(-1, a) = -B_2(a)/2 gives the exact ln(gB) coefficient."""
    n, a = sp.symbols('n a', positive=True)

    # zeta_H(-1, a) = -B_2(a)/2 (Bernoulli)  — sympy closed form
    zH = lambda aa: sp.zeta(-1, aa)
    s_plus = 2 * zH(sp.Rational(3, 2))      # sum over n of (2n+3), s=+1
    s_minus = 2 * zH(sp.Rational(-1, 2))    # sum over n of (2n-1), s=-1
    total = sp.simplify(s_plus + s_minus)
    ok_sum = sp.simplify(total + sp.Rational(11, 6)) == 0   # = -11/6 exactly

    # log coefficient of dV: (g^2 B^2/16 pi^2) * (-(total)) * ln(gB)
    log_coeff = sp.simplify(-(total) / (16 * sp.pi**2))
    ok_coeff = sp.simplify(log_coeff - sp.Rational(11, 96) / sp.pi**2) == 0

    # minimum: V = B^2/2 + c g^2 B^2 (ln(gB/mu^2) - 1/2), c = 11/96pi^2
    c, mu = sp.symbols('c mu', positive=True)
    Bv = sp.Symbol('B_v', positive=True)
    V = Bv**2 / 2 + c * g**2 * Bv**2 * (sp.log(g * Bv / mu**2) - sp.Rational(1, 2))
    dV = sp.diff(V, Bv)
    Bmin = sp.solve(sp.Eq(dV, 0), Bv)
    Bmin = [s for s in Bmin if s != 0][0]
    Vmin = sp.simplify(V.subs(Bv, Bmin))
    # exact: B_min = (mu^2/g) exp(-1/(2 c g^2)), V(B_min) = -c g^2 B_min^2 / ... < 0
    Bmin_expected = (mu**2 / g) * sp.exp(-1 / (2 * c * g**2))
    ok_bmin = sp.simplify(Bmin - Bmin_expected) == 0
    ok_vmin = sp.simplify(Vmin + c * g**2 * Bmin**2 / 2) == 0   # V_min = -c g^2 B_min^2/2 < 0

    # imaginary part from the single tachyonic level (n=0, s=-1, M^2 = -gB):
    # Im e2 = (1/2) * (1/2pi) * Integral sqrt(gB - k^2) over |k|<sqrt(gB) = gB/8
    k = sp.Symbol('k', real=True)
    im_e2 = sp.Rational(1, 2) * sp.integrate(sp.sqrt(g * B - k**2),
                                             (k, -sp.sqrt(g * B), sp.sqrt(g * B))) / (2 * sp.pi)
    imV = sp.simplify(g * B / (2 * sp.pi) * im_e2)
    ok_im = sp.simplify(imV - g**2 * B**2 / (16 * sp.pi)) == 0

    return {'zeta_sum_-11/6': ok_sum, 'log_coeff_11/96pi2': ok_coeff,
            'B_min_closed_form': ok_bmin, 'V_min_negative': ok_vmin,
            'Im_V_g2B2_16pi': ok_im,
            'Bmin': sp.sstr(Bmin), 'Vmin': sp.sstr(Vmin)}


# ------------------------------------------------------------------
# D3 — dual sine-Gordon: Debye mass + BPS dual-string tension
# ------------------------------------------------------------------
def derive_D3_sine_gordon():
    kappa, zfug = sp.symbols('kappa z', positive=True)
    chi = sp.Function('chi')
    xi = sp.Symbol('xi', real=True)

    # (a) mass: expand 2z(1-cos chi) = z chi^2 + O(chi^4); with kinetic
    #     (kappa/2)(d chi)^2 the quadratic Lagrangian is
    #     (kappa/2)[(d chi)^2 + (2z/kappa) chi^2]  ->  m_D^2 = 2z/kappa.
    pot = 2 * zfug * (1 - sp.cos(sp.Symbol('chi_s')))
    quad = sp.series(pot, sp.Symbol('chi_s'), 0, 3).removeO()
    mD2 = sp.simplify(2 * quad / sp.Symbol('chi_s')**2 / kappa)
    ok_mass = sp.simplify(mD2 - 2 * zfug / kappa) == 0

    # (b) BPS kink tension (Bogomolny completion, same trick as F86 CD1):
    #     E = Int (kappa/2) chi'^2 + 2z(1-cos chi)
    #       = Int (1/2)(sqrt(kappa) chi' - sqrt(4z(1-cos chi)))^2
    #         + sqrt(kappa) chi' sqrt(4z(1-cos chi))
    #     square vanishes on the Bogomolny eq; the cross term is a total
    #     derivative: sigma = Int_0^{2pi} sqrt(4 kappa z (1-cos chi)) dchi
    chi_s = sp.Symbol('chi_s')
    integrand = sp.sqrt(4 * kappa * zfug * (1 - sp.cos(chi_s)))
    # half-angle identity 1 - cos = 2 sin^2(chi/2); sin(chi/2) >= 0 on [0,2pi]
    half = sp.sqrt(8 * kappa * zfug) * sp.sin(chi_s / 2)
    ok_halfangle = sp.simplify(integrand**2 - half**2) == 0
    sigma_dual = sp.integrate(half, (chi_s, 0, 2 * sp.pi))
    ok_sigma = ok_halfangle and \
        sp.simplify(sigma_dual - 8 * sp.sqrt(2 * kappa * zfug)) == 0

    # (c) Bogomolny equation closure: chi(xi) = 4 atan(exp(m xi)) solves
    #     sqrt(kappa) chi' = sqrt(4z(1-cos chi)) with m = sqrt(2z/kappa)
    m = sp.sqrt(2 * zfug / kappa)
    kink = 4 * sp.atan(sp.exp(m * xi))
    lhs = sp.sqrt(kappa) * sp.diff(kink, xi)
    rhs = sp.sqrt(4 * zfug * (1 - sp.cos(kink)))
    ok_kink = sp.simplify(sp.trigsimp(lhs - rhs)) == 0

    return {'mD2_2z_over_kappa': ok_mass, 'sigma_dual_8sqrt2kz': ok_sigma,
            'kink_solves_bogomolny': ok_kink}


# ------------------------------------------------------------------
def main():
    failures = []

    print('D1  Nielsen–Olesen instability (linearised model YM EOM) ...')
    r1 = derive_D1_nielsen_olesen()
    print(f"     aligned spin   : gamma^2 = +gB closes exactly : {r1['aligned']}")
    print(f"     non-vacuous    : wrong dispersion fails       : {r1['nonvacuous']}")
    print(f"     anti-aligned   : closes at gamma^2=+gB        : {r1['anti-aligned']} (expected False)")
    if not (r1['aligned'] and r1['nonvacuous'] and not r1['anti-aligned']):
        failures.append('D1')

    print('D1b Charged-scalar control (no spin term) ...')
    ok = derive_D1b_scalar_control()
    print(f"     -D^2 psi = +gB psi exactly (omega^2 = +gB > 0): {ok}")
    if not ok:
        failures.append('D1b')

    print('D2  Savvidy one-loop potential (Hurwitz zeta, exact) ...')
    r2 = derive_D2_savvidy()
    for kk in ('zeta_sum_-11/6', 'log_coeff_11/96pi2', 'B_min_closed_form',
               'V_min_negative', 'Im_V_g2B2_16pi'):
        print(f"     {kk:24s}: {r2[kk]}")
        if not r2[kk]:
            failures.append(f'D2:{kk}')
    print(f"     B_min = {r2['Bmin']}")
    print(f"     V_min = {r2['Vmin']}")

    print('D3  Dual sine-Gordon (Debye mass + BPS dual-string tension) ...')
    r3 = derive_D3_sine_gordon()
    for kk, vv in r3.items():
        print(f"     {kk:24s}: {vv}")
        if not vv:
            failures.append(f'D3:{kk}')

    if failures:
        print('\nFAILURES:', failures)
        sys.exit(1)
    print('\nAll derivations exact. The colour-magnetic condensate is forced'
          ' (D1), favoured (D2), and identified (D3).')


if __name__ == '__main__':
    main()
