# test_F100_gamma_from_transfer_operator.py
# 2026-06-05
#
# F100 -- The gamma(Omega) map via the QCA rule's transfer operator.
#
# F99 derived sigma as the centre-twist Lagrange multiplier and reduced the
# remaining freedom to the centre-weight disorder gamma, but left the exact map
# gamma(Omega) -- from the unitary rotation tick to the Euclidean centre weight --
# characterised only by its limits (F99 section 5).  This closes that gap.
#
# The chain (transfer operator of the free rule):
#
#   (T1) The rotation rule on a conjugate (E,B) mode IS a harmonic oscillator
#        rotating its phase-space pair by the rule's angle Omega per tick:
#        R(Omega) is the symplectic phase rotation generated by the oscillator
#        number operator.  Wick-rotating the one-tick unitary e^{-i Omega(N+1/2)}
#        gives the positive transfer operator T = e^{-Omega(N+1/2)}, whose
#        vacuum is Gaussian with the per-mode plaquette-flux moment
#            <phi^2>_mode = 1/(2 Omega)        (standard oscillator ground state).
#
#   (T2) The plaquette flux is the sum over spatial modes, so the vacuum flux
#        variance is the Brillouin-zone average of the rule's inverse dispersion
#            sigma_phi^2 = (1/V) sum_{k != 0} 1/(2 Omega(k))      [from the RULE]
#        a convergent number computed from the actual rotation_omega_2d.  The
#        single-plaquette string tension is sigma_1 = -ln s_1 = sigma_phi^2/2
#        = (1/4) <1/Omega>_BZ.
#
#   (T3) The centre order parameter is s_1 = exp(-sigma_phi^2/2); gamma is fixed
#        by matching the F99 Z_3 clock weight, s_1^clock(gamma) = s_1.  This is
#        the requested map gamma(Omega) -- a closed-form functional of the rule's
#        dispersion.  For the actual 2D rule: gamma ~ 1.783, s_1 ~ 0.818.
#
#   (T4) Limits recover F99 D4 *from the rule*: Omega -> infinity (stiff rule)
#        => sigma_phi^2 -> 0, gamma -> infinity, sigma -> 0 (deconfined);
#        Omega -> 0 (soft rule) => sigma_phi^2 -> infinity, gamma -> 0,
#        sigma -> infinity (confining).
#
#   (T5) Reconciliation of the NUMBER: sigma_1 ~ 0.20 is the same order and the
#        same BZ-inverse-dispersion-average origin as F70's large-beta tension
#        floor (sigma(20)=0.219) and F95's I_2 = <cot omega_kin> = 0.2202.
#        Stated as a consistency observation, NOT an identity.
#
# Pure numpy.  Oscillator check by number-basis diagonalisation (no scipy).

import json
import time
import pathlib
import sys

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "ca-simulation"))

import ca_maxwell_2d as cm2                    # the actual rule dispersion
import ca_confinement as conf                  # F70 sigma(beta) for reconciliation

t0 = time.time()
results = {"finding": "F100", "date": "2026-06-05",
           "title": "gamma(Omega) from the QCA rule transfer operator",
           "checks": {}}


def record(name, statement, residual, status):
    results["checks"][name] = {
        "statement": statement, "residual": str(residual),
        "status": "PASS" if status else "FAIL"}
    print(f"{name}: {statement}\n      -> residual {residual} "
          f"[{'PASS' if status else 'FAIL'}]")


# ---- Z_3 clock weight machinery (from F99) -------------------------
def s1_clock(g):
    """Z_3 centre order parameter for p(n) ~ exp(g cos(2 pi n/3)):
       s_1 = (e^g - e^{-g/2}) / (e^g + 2 e^{-g/2}); divide by e^g for stability:
       s_1 = (1 - e^{-3g/2}) / (1 + 2 e^{-3g/2})."""
    e = np.exp(-1.5 * g)
    return (1.0 - e) / (1.0 + 2.0 * e)


def gamma_from_s1(s1, lo=1e-8, hi=1e4):
    """Invert s1_clock (monotone increasing) by bisection."""
    for _ in range(300):
        mid = 0.5 * (lo + hi)
        if s1_clock(mid) < s1:
            lo = mid
        else:
            hi = mid
    return 0.5 * (lo + hi)


# ============================================================ T1
# Rule tick = oscillator phase rotation; Gaussian vacuum <phi^2> = 1/(2 Omega).
# (a) R(Omega) is an orthogonal (symplectic) phase-space rotation, exactly.
Om0 = 0.7
R = np.array([[np.cos(Om0), np.sin(Om0)], [-np.sin(Om0), np.cos(Om0)]])
orth = float(np.max(np.abs(R @ R.T - np.eye(2))))
det1 = float(abs(np.linalg.det(R) - 1.0))
# (b) number-basis oscillator H = 1/2 (p^2 + Omega^2 q^2); <0|q^2|0> = 1/(2 Omega).
def gs_q2(Omega, M=200):
    n = np.arange(1, M)
    a = np.diag(np.sqrt(n), 1)
    ad = a.T
    q = (a + ad) / np.sqrt(2.0)
    p = (a - ad) / (1j * np.sqrt(2.0))
    H = 0.5 * (p @ p + Omega ** 2 * (q @ q))
    w, v = np.linalg.eigh(H)
    g0 = v[:, 0]
    return float(np.real(g0.conj() @ (q @ q) @ g0))

osc_res = max(abs(gs_q2(Om) - 1.0 / (2.0 * Om)) / (1.0 / (2.0 * Om))
              for Om in (0.25, 0.5, 1.0, 2.0, 4.0))
t1 = orth < 1e-14 and det1 < 1e-14 and osc_res < 1e-10
record("T1", "rule tick = oscillator phase rotation R(Omega) (orthogonal, det 1); "
       "transfer-operator vacuum <phi^2> = 1/(2 Omega) per mode "
       "(number-basis diagonalisation)",
       f"orth {orth:.1e}, det {det1:.1e}, osc {osc_res:.1e}", t1)


# ============================================================ T2
# Vacuum flux variance from the RULE's dispersion (convergent BZ integral).
def sigma_phi2(L):
    k = np.fft.fftfreq(L) * 2.0 * np.pi
    KX, KY = np.meshgrid(k, k, indexing="ij")
    Om = cm2.rotation_omega_2d(KX, KY)
    Om = np.where(Om < 1e-12, np.inf, Om)      # drop the k=0 zero mode
    return float(np.mean(1.0 / (2.0 * Om)))


Ls = [16, 32, 64, 128, 256, 512]
vals = [sigma_phi2(L) for L in Ls]
# Cauchy convergence: successive differences shrink geometrically (~1/2).
diffs = [abs(vals[i + 1] - vals[i]) for i in range(len(vals) - 1)]
converging = all(diffs[i + 1] < diffs[i] for i in range(len(diffs) - 1))
# Richardson limit (geometric ratio r): x_inf = x_n + d_n*r/(1-r), r ~ 0.5
r = diffs[-1] / diffs[-2]
sigma_phi2_inf = vals[-1] + diffs[-1] * r / (1.0 - r)
sigma_str = sigma_phi2_inf / 2.0               # = (1/4) <1/Omega>_BZ
t2 = converging and (0.39 < sigma_phi2_inf < 0.41) and (0.19 < sigma_str < 0.21)
record("T2", f"vacuum flux variance from the rule: sigma_phi^2 = <1/(2 Omega)>_BZ "
       f"-> {sigma_phi2_inf:.5f} (Richardson, r={r:.3f}); "
       f"sigma_1 = sigma_phi^2/2 = (1/4)<1/Omega>_BZ = {sigma_str:.5f}",
       f"diffs {[f'{d:.2e}' for d in diffs]}", t2)


# ============================================================ T3
# The gamma(Omega) map: s_1 = exp(-sigma_phi^2/2); gamma = clock^{-1}(s_1).
s1 = np.exp(-sigma_phi2_inf / 2.0)
gamma_star = gamma_from_s1(s1)
roundtrip = abs(s1_clock(gamma_star) - s1)
# monotone: a stiffer rule (Omega -> lambda Omega, lambda>1) gives smaller
# sigma_phi^2 -> larger gamma; a softer rule (lambda<1) gives smaller gamma.
def gamma_for_scale(lam):
    s2 = sigma_phi2_inf / lam                   # Omega -> lam*Omega scales 1/Omega by 1/lam
    return gamma_from_s1(np.exp(-s2 / 2.0))

g_soft, g_ref, g_stiff = gamma_for_scale(0.5), gamma_star, gamma_for_scale(2.0)
monotone = g_soft < g_ref < g_stiff
t3 = roundtrip < 1e-12 and (1.7 < gamma_star < 1.9) and monotone
record("T3", f"gamma(Omega) = clock^{{-1}}(exp(-sigma_phi^2/2)) = {gamma_star:.5f} "
       f"for the 2D rule (s_1 = {s1:.5f}); clock round-trip exact; "
       f"monotone in dispersion stiffness ({g_soft:.3f}<{g_ref:.3f}<{g_stiff:.3f})",
       f"roundtrip {roundtrip:.1e}", t3)


# ============================================================ T4
# Limits recover F99 D4 -- but now reached by tuning the rule's Omega.
# stiff rule: lambda -> large  => sigma_phi^2 -> 0, gamma -> inf, sigma -> 0
g_verystiff = gamma_for_scale(1e6)
s_verystiff = -np.log(s1_clock(g_verystiff))
# soft rule: lambda -> 0+   => sigma_phi^2 -> inf, gamma -> 0, sigma -> inf
g_verysoft = gamma_for_scale(1e-6)
s_verysoft = -np.log(max(s1_clock(g_verysoft), 1e-300))
t4 = (g_verystiff > 10.0 and s_verystiff < 1e-3
      and g_verysoft < 1e-2 and s_verysoft > 10.0)
record("T4", "limits recover F99 D4 from the rule: stiff Omega -> gamma->inf, "
       "sigma->0 (deconfined); soft Omega -> gamma->0, sigma->inf (confining)",
       f"stiff(gamma={g_verystiff:.1f}, sigma={s_verystiff:.1e}); "
       f"soft(gamma={g_verysoft:.1e}, sigma={s_verysoft:.1f})", t4)


# ============================================================ T5
# Reconciliation of the NUMBER (consistency, NOT an identity).
# sigma_1 ~ 0.20 sits at F70's large-beta tension floor and near F95's I_2.
sig_f70_20 = conf.string_tension(20.0)         # 0.219 (F70 table)
sig_f70_60 = conf.string_tension(60.0)
I2_F95 = 0.2202                                # F95 <cot omega_kin>_BCC
same_order = (0.15 < sigma_str < 0.25
              and abs(sigma_str - sig_f70_20) < 0.05
              and abs(sigma_str - I2_F95) < 0.05)
# honest: F70 sigma keeps decreasing past beta=20, so this is order/origin, not identity
not_identity = sig_f70_60 < sig_f70_20         # F70 has no fixed floor -> not an identity
t5 = bool(same_order and not_identity)
record("T5", f"reconciliation: sigma_1={sigma_str:.4f} same order & same "
       f"BZ-inverse-dispersion origin as F70 floor sigma(20)={sig_f70_20:.4f} and "
       f"F95 I_2={I2_F95} (consistency, not an identity: F70 sigma(60)={sig_f70_60:.4f}<sigma(20))",
       f"|sigma_1 - sigma_F70(20)|={abs(sigma_str-sig_f70_20):.4f}", t5)


# ============================================================
results["sigma_phi2_inf"] = round(sigma_phi2_inf, 6)
results["sigma_1"] = round(sigma_str, 6)
results["gamma_star"] = round(gamma_star, 6)
results["s1"] = round(float(s1), 6)
results["runtime_s"] = round(time.time() - t0, 3)
n_pass = sum(1 for c in results["checks"].values() if c["status"] == "PASS")
results["summary"] = f"{n_pass}/{len(results['checks'])} PASS"
print(f"\nOverall: {results['summary']} ({results['runtime_s']} s)")

out = ROOT / "test-results" / "F100_gamma_from_transfer_operator.json"
out.write_text(json.dumps(results, indent=2))
print(f"Results written to {out}")
