"""
complex_mass_fork.py — Higgs-free complex-mass Dirac CA fork
=============================================================
2026-05-23

Implements Ludwig's 2007 proposal (physics_notes_0708.pdf pp. 59–60):
**gauge the β matrix** of the Dirac equation to produce chiral SU(2)
without a separate Higgs field.

Core idea (pp. 59–60)
---------------------
The standard Dirac equation (Weyl rep) uses

    β = σ₁ ⊗ I_spin                  (mass matrix)

Ludwig observes that β_g = (U σ₁ U†) ⊗ I with

    U = diag(1, e^{iθ})   ∈ U(1) ⊂ SU(2)

gives the same Clifford relations {α_i, β_g}=0, β_g²=I, so it provides a
valid mass coupling for any θ.  Writing this out:

    β_g = cos θ · σ₁ + sin θ · σ₂      (rotation in the σ₁–σ₂ plane)

If θ = θ(x,t) is position-dependent the Dirac equation keeps its form but
the mass coupling becomes *local*.

The gauge action *only on the left-handed (η) half* of the bispinor is
what ties this to the weak interaction, which is also helicity-selective.

The mass coupling in the QCA propagator for this change is:

    D_k(θ) = [[n W_k,          im e^{iθ(x)} I],
               [im e^{-iθ(x)} I,  n W†_k       ]]

which is unitary for any θ(x) — the dispersion ω_k = arccos(n c_x c_y)
is θ-independent (gauge freedom).  This is the 1-flavour version.

SU(2) doublet (the full chiral SU(2) fork)
-------------------------------------------
For a left doublet (ν_L, e_L) and right doublet (ν_R, e_R), replace the
U(1) phase by U(x) ∈ SU(2):

    mass step:   η_new = cos(m) η + i sin(m) U(x) χ
                 χ_new = i sin(m) U†(x) η + cos(m) χ

where U acts on the isospin index and I₂ on the spin index.

Gauge invariance (the chiral SU(2) claim):
Under the *left-handed only* transformation

    η → V(x) η,    χ → χ  (unchanged — RIGHT-HANDED SINGLET)

combined with  U → V U  the mass step is unchanged:

    η_new → V η_new = V(cos η + i sin U χ)
                     = cos(Vη) + i sin (VU χ)    ✓ (same form with U→VU)

    χ_new → cos χ + i sin (VU)† (Vη)
           = cos χ + i sin U†V†Vη = cos χ + i sin U† η  ✓

So the doublet complex-mass is **chiral SU(2) gauge invariant** with NO
Higgs field.  Mass is generated by the frozen gauge orientation of U, which
is pure-gauge — not a physical scalar condensate.

This contradicts the Standard Model story where the Higgs is required to
produce a gauge-invariant fermion mass.

Split-step implementation
-------------------------
For spatially varying θ(x) / U(x), a Fourier-space D_k is not directly
applicable.  We use Strang splitting:

    step(dt) = kinetic(dt/2) ∘ mass(dt) ∘ kinetic(dt/2)

The kinetic half-step is the exact Weyl QCA from ca_core_exact.py applied
independently to each isospin component (no isospin–kinetics coupling).
The mass step is local in position space.
"""

from __future__ import annotations

import numpy as np
import os
import sys

# ── make parent directory importable ──────────────────────────────────────────
_FORK_DIR  = os.path.dirname(__file__)
_SIM_ROOT  = os.path.abspath(os.path.join(_FORK_DIR, '..'))
sys.path.insert(0, _SIM_ROOT)

import ca_core_exact as _ce
import ca_dirac as _cd


# ══════════════════════════════════════════════════════════════════════════════
#  Part I — 1-Flavour complex mass (U(1) θ-field)
# ══════════════════════════════════════════════════════════════════════════════

def _weyl_half_step(f, g, dt_half, m):
    """
    One kinetic half-step for the Weyl doublet (f, g) using the exact-QCA
    2D unitary.  f → upper spin, g → lower spin.  dt_half is dt/2 in units
    of one full lattice tick; here we use spectral interpolation.
    """
    Lx, Ly = f.shape
    kx = np.fft.fftfreq(Lx) * 2.0 * np.pi
    ky = np.fft.fftfreq(Ly) * 2.0 * np.pi
    KX, KY = np.meshgrid(kx, ky, indexing='ij')
    U_ff, U_fg, U_gf, U_gg = _ce.exact2d_unitary(KX, KY)

    if dt_half == 0.5:
        # Use the exact Bloch-decomposition spectral half-step.
        # U(k, 1/2) = cos(ω/2) I + i sin(ω/2)/sin(ω) · (U(k,1) − cos(ω) I)
        # when ω → 0 we get U(k, 1/2) ≈ I (correctly).
        omega = _ce.exact2d_dispersion(KX, KY)
        cos_w = np.cos(omega)
        sin_w = np.sin(omega)
        cos_h = np.cos(0.5 * omega)
        sin_safe = np.where(np.abs(sin_w) < 1e-14, 1.0, sin_w)
        scale = np.sin(0.5 * omega) / sin_safe
        scale = np.where(np.abs(sin_w) < 1e-14, 0.5, scale)
    else:
        omega = _ce.exact2d_dispersion(KX, KY)
        cos_w = np.cos(omega)
        sin_w = np.sin(omega)
        cos_h = np.cos(dt_half * omega)
        sin_safe = np.where(np.abs(sin_w) < 1e-14, 1.0, sin_w)
        scale = np.sin(dt_half * omega) / sin_safe
        scale = np.where(np.abs(sin_w) < 1e-14, dt_half, scale)

    F = np.fft.fft2(f)
    G = np.fft.fft2(g)
    # Apply the single-tick unitary once to get D|ψ⟩
    F_d = U_ff * F + U_fg * G
    G_d = U_gf * F + U_gg * G
    # Spectral interpolation: U(dt_half)|ψ⟩ = cos(ω·dt) |ψ⟩ + scale·(D|ψ⟩ − cos(ω)|ψ⟩)
    F_new = cos_h * F + scale * (F_d - cos_w * F)
    G_new = cos_h * G + scale * (G_d - cos_w * G)
    return np.fft.ifft2(F_new), np.fft.ifft2(G_new)


def mass_step_1flavor(eta_u, eta_d, chi_u, chi_d, theta, m, dt=1.0):
    """
    Local complex-mass coupling step (1-flavour).

    Parameters
    ----------
    eta_u, eta_d : (Lx, Ly) complex  — left-chirality spinor components
    chi_u, chi_d : (Lx, Ly) complex  — right-chirality spinor components
    theta        : (Lx, Ly) real     — local U(1) mass-angle field
    m            : float             — mass parameter (|m| ≤ 1)
    dt           : float             — time step (default 1 tick)

    Returns
    -------
    Updated (eta_u, eta_d, chi_u, chi_d).

    The local unitary at each site is:

        M(θ) = [[cos(m·dt)·I,   i e^{iθ} sin(m·dt)·I ],
                [i e^{-iθ} sin(m·dt)·I,  cos(m·dt)·I ]]

    Unitarity: M is of the form cos·I + i sin·A where A = [[0, e^{iθ}],[e^{-iθ}, 0]]
    is Hermitian with A² = I, so M†M = I exactly.
    """
    c_m = np.cos(m * dt)
    s_m = np.sin(m * dt)
    phase     = np.exp(1j * theta)        # shape (Lx, Ly)
    phase_conj = np.conj(phase)

    eta_u_new = c_m * eta_u + 1j * s_m * phase      * chi_u
    eta_d_new = c_m * eta_d + 1j * s_m * phase      * chi_d
    chi_u_new = 1j * s_m * phase_conj * eta_u + c_m * chi_u
    chi_d_new = 1j * s_m * phase_conj * eta_d + c_m * chi_d
    return eta_u_new, eta_d_new, chi_u_new, chi_d_new


def complex_mass_step_1flavor(eta_u, eta_d, chi_u, chi_d, theta, m, dt=1.0):
    """
    Full Strang-split step: kinetic(dt/2) → complex_mass(dt) → kinetic(dt/2).

    This is the main 1-flavour complex-mass CA timestep.

    Parameters
    ----------
    eta_u, eta_d : (Lx, Ly) complex  — left Weyl spinor (spin up/down)
    chi_u, chi_d : (Lx, Ly) complex  — right Weyl spinor (spin up/down)
    theta        : (Lx, Ly) real     — local β gauge angle θ(x)
    m            : float             — dimensionless mass (|m| ≤ 1)
    dt           : float             — time step

    Returns
    -------
    Updated (eta_u, eta_d, chi_u, chi_d).
    """
    _cd._check_mass(m)
    # — kinetic half-step ——————————————————————————————————
    eta_u, eta_d = _weyl_half_step(eta_u, eta_d, 0.5 * dt, m)
    chi_u, chi_d = _weyl_half_step(chi_u, chi_d, 0.5 * dt, m)
    # — complex mass full step ——————————————————————————————
    eta_u, eta_d, chi_u, chi_d = mass_step_1flavor(
        eta_u, eta_d, chi_u, chi_d, theta, m, dt)
    # — kinetic half-step ——————————————————————————————————
    eta_u, eta_d = _weyl_half_step(eta_u, eta_d, 0.5 * dt, m)
    chi_u, chi_d = _weyl_half_step(chi_u, chi_d, 0.5 * dt, m)
    return eta_u, eta_d, chi_u, chi_d


def norm_1flavor(eta_u, eta_d, chi_u, chi_d):
    """Total probability norm for the 1-flavour spinor."""
    return float(
        np.sum(np.abs(eta_u)**2 + np.abs(eta_d)**2
               + np.abs(chi_u)**2 + np.abs(chi_d)**2))


# ══════════════════════════════════════════════════════════════════════════════
#  Part II — SU(2) doublet complex mass (chiral SU(2) fork)
# ══════════════════════════════════════════════════════════════════════════════
#
#  State arrays per spin component (all shape (Lx, Ly)):
#    eta_nu_u, eta_nu_d   — left-handed neutrino (isospin up of doublet)
#    eta_e_u,  eta_e_d    — left-handed electron (isospin down of doublet)
#    chi_nu_u, chi_nu_d   — right-handed neutrino
#    chi_e_u,  chi_e_d    — right-handed electron
#
#  SU(2) field U(x) stored as two arrays (a, b) with |a|²+|b|²=1:
#    U = [[a, -b*], [b, a*]]   ∈ SU(2)    shape: a, b each (Lx, Ly) complex
# ══════════════════════════════════════════════════════════════════════════════

def make_su2_field(Lx, Ly, mode='identity'):
    """
    Initialise an SU(2) isospin field U(x) = [[a, -b*],[b, a*]].

    Parameters
    ----------
    mode : str
        'identity'  — U = I everywhere (a=1, b=0)
        'random'    — U(x) uniformly random on SU(2) at each site
        'plane'     — a(x) = cos(π/4), b(x) = sin(π/4)·e^{ikx}  (a test wave)
        'su2_z'     — U = e^{iα σ₃/2}: a=e^{iα/2}, b=0  with random α(x)

    Returns
    -------
    a, b : complex ndarrays of shape (Lx, Ly).
    """
    if mode == 'identity':
        a = np.ones((Lx, Ly), dtype=complex)
        b = np.zeros((Lx, Ly), dtype=complex)
    elif mode == 'random':
        # Sample uniformly from SU(2) via Haar measure: pick unit quaternion.
        rng = np.random.default_rng(seed=42)
        raw = rng.standard_normal((Lx, Ly, 4))
        norms = np.linalg.norm(raw, axis=-1, keepdims=True)
        q = raw / norms       # unit quaternion (q0, q1, q2, q3)
        a = q[..., 0] + 1j * q[..., 3]
        b = q[..., 2] + 1j * q[..., 1]
    elif mode == 'plane':
        theta = np.pi / 4
        a = np.full((Lx, Ly), np.cos(theta), dtype=complex)
        b = np.full((Lx, Ly), np.sin(theta), dtype=complex)
    elif mode == 'su2_z':
        rng = np.random.default_rng(seed=7)
        alpha = rng.uniform(0, 2 * np.pi, (Lx, Ly))
        a = np.exp(0.5j * alpha)
        b = np.zeros((Lx, Ly), dtype=complex)
    else:
        raise ValueError(f"Unknown SU(2) mode: {mode!r}")
    return a, b


def su2_gauge_transform(eta_nu_u, eta_nu_d, eta_e_u, eta_e_d,
                        chi_nu_u, chi_nu_d, chi_e_u, chi_e_d,
                        U_a, U_b,
                        V_a, V_b):
    """
    Apply chiral SU(2) gauge transformation:

        (η_ν, η_e) → V(x) (η_ν, η_e)    [left-handed doublet transforms]
        (χ_ν, χ_e) → (χ_ν, χ_e)         [right-handed doublet UNCHANGED]
        U → V · U                          [coupling field compensates]

    where V = [[V_a, -V_b*],[V_b, V_a*]] and U = [[U_a, -U_b*],[U_b, U_a*]].

    Returns
    -------
    Transformed state: (eta_nu_u, eta_nu_d, eta_e_u, eta_e_d,
                        chi_nu_u, chi_nu_d, chi_e_u, chi_e_d)
    and new coupling:  (U_a_new, U_b_new)
    """
    # V acts on isospin doublet (ν, e):
    #   η'_ν = V_a η_ν + (-V_b*) η_e  =  V_a η_ν - V_b* η_e
    #   η'_e = V_b η_ν + V_a*  η_e
    Va, Vbc = V_a, np.conj(V_b)
    eta_nu_u_new = Va * eta_nu_u - Vbc * eta_e_u
    eta_nu_d_new = Va * eta_nu_d - Vbc * eta_e_d
    eta_e_u_new  = V_b * eta_nu_u + np.conj(V_a) * eta_e_u
    eta_e_d_new  = V_b * eta_nu_d + np.conj(V_a) * eta_e_d

    # χ is unchanged (right-handed singlet — the chiral asymmetry)
    chi_nu_u_new, chi_nu_d_new = chi_nu_u.copy(), chi_nu_d.copy()
    chi_e_u_new,  chi_e_d_new  = chi_e_u.copy(),  chi_e_d.copy()

    # Coupling transforms: U' = V · U
    # [[V_a, -Vb*],[Vb, Va*]] · [[Ua, -Ub*],[Ub, Ua*]]
    #   (1,1): Va·Ua + (-Vb*)·Ub
    #   (1,2): Va·(-Ub*) + (-Vb*)·Ua* = -(Va·Ub* + Vb*·Ua*)
    #   (2,1): Vb·Ua + Va*·Ub
    #   (2,2): Vb·(-Ub*) + Va*·Ua* = -(Vb·Ub* - Va*·Ua*) ... check SU(2) form
    # SU(2) product: a'' = Va·Ua - Vb*·Ub,  b'' = Vb·Ua + Va*·Ub
    U_a_new = Va * U_a - np.conj(V_b) * U_b
    U_b_new = V_b * U_a + np.conj(V_a) * U_b

    return (eta_nu_u_new, eta_nu_d_new, eta_e_u_new, eta_e_d_new,
            chi_nu_u_new, chi_nu_d_new, chi_e_u_new, chi_e_d_new,
            U_a_new, U_b_new)


def mass_step_doublet(eta_nu_u, eta_nu_d, eta_e_u, eta_e_d,
                      chi_nu_u, chi_nu_d, chi_e_u, chi_e_d,
                      U_a, U_b, m, dt=1.0):
    """
    Local SU(2) complex-mass coupling step for the doublet.

    The mass coupling at each site is:

        M = [[cos(m·dt) I₄,          i sin(m·dt) (U⊗I₂)  ],
             [i sin(m·dt) (U†⊗I₂),  cos(m·dt) I₄          ]]

    where U = [[Ua, -Ub*],[Ub, Ua*]] acts on the isospin index and I₂ on spin.

    Unitarity proof:
      A = [[0, U⊗I₂],[U†⊗I₂, 0]] is Hermitian (A† = A).
      A² = [[UU†⊗I₂, 0],[0, U†U⊗I₂]] = [[I₄,0],[0,I₄]] = I₈  (since UU†=I).
      ∴ M = cos·I + i sin·A satisfies M†M = (cos²+sin²)·I = I.

    Parameters
    ----------
    eta_nu_u, eta_nu_d : (Lx,Ly) complex — left-handed ν spinor
    eta_e_u,  eta_e_d  : (Lx,Ly) complex — left-handed e spinor
    chi_nu_u, chi_nu_d : (Lx,Ly) complex — right-handed ν spinor
    chi_e_u,  chi_e_d  : (Lx,Ly) complex — right-handed e spinor
    U_a, U_b           : (Lx,Ly) complex — SU(2) field (|Ua|²+|Ub|²=1)
    m                  : float  — mass (|m| ≤ 1)
    dt                 : float  — timestep

    Returns
    -------
    Updated 8-tuple of spinor arrays.
    """
    c_m = np.cos(m * dt)
    s_m = np.sin(m * dt)
    Ua = U_a; Ub = U_b
    Uac = np.conj(Ua); Ubc = np.conj(Ub)   # a*, b*

    # η_new = cos η + i sin (U ⊗ I₂) χ
    # U·χ on isospin: [Ua -Ub*; Ub Ua*] · [[χ_ν],[χ_e]]
    #   (χ_ν component for η_ν): Ua χ_nu - Ub* χ_e
    #   (χ_e component for η_e): Ub χ_nu + Ua* χ_e
    eta_nu_u_new = c_m * eta_nu_u + 1j * s_m * (Ua * chi_nu_u - Ubc * chi_e_u)
    eta_nu_d_new = c_m * eta_nu_d + 1j * s_m * (Ua * chi_nu_d - Ubc * chi_e_d)
    eta_e_u_new  = c_m * eta_e_u  + 1j * s_m * (Ub * chi_nu_u + Uac * chi_e_u)
    eta_e_d_new  = c_m * eta_e_d  + 1j * s_m * (Ub * chi_nu_d + Uac * chi_e_d)

    # χ_new = i sin (U† ⊗ I₂) η + cos χ
    # U†·η on isospin: [Ua* Ub*; -Ub Ua] · [[η_ν],[η_e]]
    #   (ν component): Ua* η_nu + Ub* η_e
    #   (e component): -Ub η_nu + Ua  η_e
    chi_nu_u_new = 1j * s_m * (Uac * eta_nu_u + Ubc * eta_e_u) + c_m * chi_nu_u
    chi_nu_d_new = 1j * s_m * (Uac * eta_nu_d + Ubc * eta_e_d) + c_m * chi_nu_d
    chi_e_u_new  = 1j * s_m * (-Ub * eta_nu_u + Ua  * eta_e_u) + c_m * chi_e_u
    chi_e_d_new  = 1j * s_m * (-Ub * eta_nu_d + Ua  * eta_e_d) + c_m * chi_e_d

    return (eta_nu_u_new, eta_nu_d_new, eta_e_u_new, eta_e_d_new,
            chi_nu_u_new, chi_nu_d_new, chi_e_u_new, chi_e_d_new)


def complex_mass_step_doublet(eta_nu_u, eta_nu_d, eta_e_u, eta_e_d,
                               chi_nu_u, chi_nu_d, chi_e_u, chi_e_d,
                               U_a, U_b, m, dt=1.0):
    """
    Full Strang-split step for the SU(2) doublet:

        kinetic(dt/2) → SU(2)-mass(dt) → kinetic(dt/2)

    The kinetic step is applied independently to each isospin component.
    The SU(2) mass field U(x) is kept fixed during this step (no gauge
    dynamics — U is a static background or pure gauge).

    Parameters
    ----------
    see mass_step_doublet — same signature + (U_a, U_b) at the end.

    Returns
    -------
    Updated 8-tuple of spinor components.
    """
    _cd._check_mass(m)

    # — kinetic half-step (each isospin component independently) ——————————
    eta_nu_u, eta_nu_d = _weyl_half_step(eta_nu_u, eta_nu_d, 0.5 * dt, m)
    eta_e_u,  eta_e_d  = _weyl_half_step(eta_e_u,  eta_e_d,  0.5 * dt, m)
    chi_nu_u, chi_nu_d = _weyl_half_step(chi_nu_u, chi_nu_d, 0.5 * dt, m)
    chi_e_u,  chi_e_d  = _weyl_half_step(chi_e_u,  chi_e_d,  0.5 * dt, m)

    # — SU(2) complex-mass full step ——————————————————————————————————————
    (eta_nu_u, eta_nu_d, eta_e_u, eta_e_d,
     chi_nu_u, chi_nu_d, chi_e_u, chi_e_d) = mass_step_doublet(
        eta_nu_u, eta_nu_d, eta_e_u, eta_e_d,
        chi_nu_u, chi_nu_d, chi_e_u, chi_e_d,
        U_a, U_b, m, dt)

    # — kinetic half-step ——————————————————————————————————————————————
    eta_nu_u, eta_nu_d = _weyl_half_step(eta_nu_u, eta_nu_d, 0.5 * dt, m)
    eta_e_u,  eta_e_d  = _weyl_half_step(eta_e_u,  eta_e_d,  0.5 * dt, m)
    chi_nu_u, chi_nu_d = _weyl_half_step(chi_nu_u, chi_nu_d, 0.5 * dt, m)
    chi_e_u,  chi_e_d  = _weyl_half_step(chi_e_u,  chi_e_d,  0.5 * dt, m)

    return (eta_nu_u, eta_nu_d, eta_e_u, eta_e_d,
            chi_nu_u, chi_nu_d, chi_e_u, chi_e_d)


def norm_doublet(eta_nu_u, eta_nu_d, eta_e_u, eta_e_d,
                 chi_nu_u, chi_nu_d, chi_e_u, chi_e_d):
    """Total probability norm for the doublet spinor."""
    return float(sum(
        np.sum(np.abs(arr)**2)
        for arr in (eta_nu_u, eta_nu_d, eta_e_u, eta_e_d,
                    chi_nu_u, chi_nu_d, chi_e_u, chi_e_d)))


def gaussian_doublet(shape, sigma=4.0, kind='left_nu', center=None):
    """
    Gaussian initial conditions for the SU(2) doublet.

    kind:
      'left_nu'   — pure η_nu (ν left-handed)
      'left_e'    — pure η_e  (e left-handed)
      'left_both' — equal mix η_nu = η_e = G/√2 (left doublet excited)
      'right_nu'  — pure χ_nu (ν right-handed)
      'right_e'   — pure χ_e  (e right-handed)

    Returns
    -------
    8-tuple: (eta_nu_u, eta_nu_d, eta_e_u, eta_e_d,
              chi_nu_u, chi_nu_d, chi_e_u, chi_e_d)
    """
    Lx, Ly = shape
    cx, cy = center if center is not None else (Lx // 2, Ly // 2)
    x = np.arange(Lx) - cx
    y = np.arange(Ly) - cy
    X, Y = np.meshgrid(x, y, indexing='ij')
    G = np.exp(-(X**2 + Y**2) / (2.0 * sigma**2)).astype(complex)
    z = np.zeros_like(G)

    eta_nu_u = z.copy(); eta_nu_d = z.copy()
    eta_e_u  = z.copy(); eta_e_d  = z.copy()
    chi_nu_u = z.copy(); chi_nu_d = z.copy()
    chi_e_u  = z.copy(); chi_e_d  = z.copy()

    if kind == 'left_nu':
        eta_nu_u = G.copy()
    elif kind == 'left_e':
        eta_e_u = G.copy()
    elif kind == 'left_both':
        eta_nu_u = G / np.sqrt(2.0)
        eta_e_u  = G / np.sqrt(2.0)
    elif kind == 'right_nu':
        chi_nu_u = G.copy()
    elif kind == 'right_e':
        chi_e_u = G.copy()
    else:
        raise ValueError(f"Unknown initial condition kind: {kind!r}")

    return (eta_nu_u, eta_nu_d, eta_e_u, eta_e_d,
            chi_nu_u, chi_nu_d, chi_e_u, chi_e_d)


# ══════════════════════════════════════════════════════════════════════════════
#  Part III — Observable: isospin current & chirality content
# ══════════════════════════════════════════════════════════════════════════════

def chirality_split_doublet(eta_nu_u, eta_nu_d, eta_e_u, eta_e_d,
                            chi_nu_u, chi_nu_d, chi_e_u, chi_e_d):
    """
    Return (N_left, N_right) = total probability in left vs right chirality sectors.
    """
    N_left  = float(sum(np.sum(np.abs(arr)**2)
                        for arr in (eta_nu_u, eta_nu_d, eta_e_u, eta_e_d)))
    N_right = float(sum(np.sum(np.abs(arr)**2)
                        for arr in (chi_nu_u, chi_nu_d, chi_e_u, chi_e_d)))
    return N_left, N_right


def isospin_z_doublet(eta_nu_u, eta_nu_d, eta_e_u, eta_e_d,
                      chi_nu_u, chi_nu_d, chi_e_u, chi_e_d):
    """
    Return ⟨T₃⟩ = (N_ν − N_e) / 2 for left and right sectors separately.

    In SU(2) the isospin-up (ν) component has T₃ = +½ and isospin-down (e)
    has T₃ = −½.  This observable is SU(2)_L invariant only for the
    generator T₃ (the U(1) subgroup).
    """
    N_nu_L = float(sum(np.sum(np.abs(arr)**2) for arr in (eta_nu_u, eta_nu_d)))
    N_e_L  = float(sum(np.sum(np.abs(arr)**2) for arr in (eta_e_u,  eta_e_d)))
    N_nu_R = float(sum(np.sum(np.abs(arr)**2) for arr in (chi_nu_u, chi_nu_d)))
    N_e_R  = float(sum(np.sum(np.abs(arr)**2) for arr in (chi_e_u,  chi_e_d)))

    T3_L = 0.5 * (N_nu_L - N_e_L)
    T3_R = 0.5 * (N_nu_R - N_e_R)
    return T3_L, T3_R


def su2_casimir_left(eta_nu_u, eta_nu_d, eta_e_u, eta_e_d):
    """
    Compute ⟨T²⟩ = T₁² + T₂² + T₃² on the left-handed doublet sector only.

    For an SU(2) doublet state |T=½, T₃=m⟩ the Casimir eigenvalue is
    T(T+1) = ¾.  This function returns the *expectation value* of T² in
    the current left-sector state.

    Using the spin algebra in isospin space:
        T₃ = ½ (|η_ν|² − |η_e|²) / norm
        T+ = sum η_ν* η_e (integrated)
        T- = sum η_e* η_ν (integrated)
        T² = T₃² + ½(T+T- + T-T+)

    The result should be 3/4 if the state is a pure doublet.
    Returns the expectation value (a real float).
    """
    N_nu = float(sum(np.sum(np.abs(arr)**2) for arr in (eta_nu_u, eta_nu_d)))
    N_e  = float(sum(np.sum(np.abs(arr)**2) for arr in (eta_e_u,  eta_e_d)))
    N_total = N_nu + N_e
    if N_total < 1e-30:
        return 0.0

    # T₃² contribution
    T3 = 0.5 * (N_nu - N_e) / N_total
    T3_sq = T3**2

    # T₊ = sum η_ν* η_e (off-diagonal in isospin), T₋ = (T₊)*
    T_plus = (np.sum(np.conj(eta_nu_u) * eta_e_u)
              + np.sum(np.conj(eta_nu_d) * eta_e_d)) / N_total
    T_minus = np.conj(T_plus)

    # ⟨T²⟩ = T₃² + ½(T₊T₋ + T₋T₊) = T₃² + |T₊|²
    T_sq = T3_sq + float(np.abs(T_plus)**2)
    return T_sq
