"""
Fork F52 — GRAVITY AS A SELF-CONSISTENT REST-LEG (CLOCK-RATE) FIELD
==================================================================
Drafted 2026-05-29.  Closes the open loop in Finding 50.

Background / the open loop
--------------------------
F46 showed the exact lattice Dirac dispersion is a right spherical triangle

      cos Ω_Dirac(k,m) = cos Ω_rest(m) · cos ω_kin(k),     Ω_rest = arcsin(m),

so the REST leg Ω_rest is simultaneously (a) the mass term and (b) the local
proper-time clock rate (the zitterbewegung rotation 2·arcsin m per tick at
k = 0).  F50 then showed that in a static curved background gravity enters
ENTIRELY through that rest leg:

      Ω_rest(x) = √A(x) · arcsin(m),     (lapse √A carries the redshift)

with the kinetic leg c_eff = c₀√(A/B) carrying deflection/Shapiro.  BUT F50
*imports* the lapse: it takes an analytic Newtonian potential φ = −GM/r and
feeds it through the gr_fork_E_tensor metric map φ → (A,B).  The coupling
runs one way (mass → potential → leg renormalisation) and the potential is
hand-supplied, not generated by the rest leg itself.

The F52 hypothesis (gravity as a *result* of mass)
--------------------------------------------------
Posit that the clock-rate field is not imported but is the EQUILIBRIUM of a
local lattice field equation in which the rest-leg rotation-rate deficit is
sourced *directly* by rest-mass density ρ(x):

      ∇²_lat Φ(x) = 4πG ρ(x),        s(x) ≡ √A(Φ(x)) = clock-rate field,

i.e. "a clock at a site slows in proportion to the rest-mass it is phase-
coupled to," relaxed to a fixed point on the lattice.  There is NO imported
−GM/r.  The source is ρ.  We then ask three things:

  H1  Loop closure: does the self-consistent Φ reproduce the very −GM/r that
      F50 imports (same 1/r shape, same amplitude GM)?  If yes, F50's lapse is
      recoverable from mass alone.
  H2  Redshift: does the resulting rest leg give the GR factor-1 redshift
      (Δν/ν = Δφ/c²), reproducing F50-G2 without an imported potential?
  H3  Deflection discriminator (the factor-1-vs-2 question flagged in
      Findings 8 and the geodesic work): if gravity is sourced ONLY as the
      rest/clock leg (spatial metric B left flat = 1), the eikonal deflection
      coefficient is the Newtonian 2GM/(bc²) — factor 1.  Recovering Einstein's
      4GM/(bc²) — factor 2 — REQUIRES the spatial metric B to also be sourced
      by mass.  So the rest leg alone gives gravity, but only Newtonian gravity.

What is derived vs posited
--------------------------
Posited: that the clock-deficit Poisson-couples to ρ with coefficient 4πG
(Newton's constant) — this is an input, not derived from the CA update rule.
Derived/tested here: (i) that this single field reproduces F50's imported
lapse (loop closure), (ii) that the rest leg then yields factor-1 redshift,
and (iii) that a rest-leg-ONLY source is necessarily factor-1 in deflection,
pinpointing exactly the extra structure (a sourced spatial metric B) that
Einstein's factor-2 demands.

Interface mirrors gr_fork_F46_dirac / gr_fork_E_tensor.
"""

from __future__ import annotations

import os
import sys

import numpy as np

_THIS = os.path.dirname(__file__)
if _THIS not in sys.path:
    sys.path.insert(0, _THIS)
_SIM = os.path.abspath(os.path.join(_THIS, ".."))
if _SIM not in sys.path:
    sys.path.insert(0, _SIM)

import gr_fork_E_tensor as forkE                 # noqa: E402  metric map φ→(A,B)
from ca_emqg import solve_poisson_3d             # noqa: E402  ∇²φ = 4πGρ (FFT)


# ───────────────────────────────────────────────────────────────────
#  The self-consistent rest-leg potential, sourced by mass directly
# ───────────────────────────────────────────────────────────────────

def restleg_potential_fft(rho, G=1.0):
    """Self-consistent rest-leg potential Φ solving ∇²Φ = 4πG ρ on the lattice
    from the rest-mass density ρ directly (NO imported −GM/r).  Periodic/FFT,
    zero-mean (the additive gauge constant is physically irrelevant: redshift
    depends on differences of √A, deflection on gradients)."""
    return solve_poisson_3d(np.asarray(rho, dtype=np.float64), G=G)


def relax_restleg_potential(rho, G=1.0, n_iter=6000, tol=1e-8, log_every=0):
    """LITERAL fixed point: solve ∇²Φ = 4πG ρ by hand-rolled Jacobi relaxation
    on a 6-neighbour 3D stencil (h = 1) with Φ = 0 Dirichlet boundary (an
    isolated mass, field → 0 far away).

    This is the "relax the clock-rate field to equilibrium" reading of the
    hypothesis, written from scratch (per project practice) rather than via an
    FFT, so we can watch it converge to the same field the spectral solver
    gives.  Returns (Phi, final_residual, iters_run).
    """
    rho = np.asarray(rho, dtype=np.float64)
    src = 4.0 * np.pi * G * rho            # RHS of ∇²Φ = src
    Phi = np.zeros_like(rho)
    res = np.inf
    iters = 0
    for it in range(n_iter):
        # 6-neighbour sum via roll (periodic roll, then re-impose Dirichlet)
        nb = (np.roll(Phi, 1, 0) + np.roll(Phi, -1, 0) +
              np.roll(Phi, 1, 1) + np.roll(Phi, -1, 1) +
              np.roll(Phi, 1, 2) + np.roll(Phi, -1, 2))
        Phi_new = (nb - src) / 6.0
        # Dirichlet Φ=0 on the box faces
        Phi_new[0, :, :] = Phi_new[-1, :, :] = 0.0
        Phi_new[:, 0, :] = Phi_new[:, -1, :] = 0.0
        Phi_new[:, :, 0] = Phi_new[:, :, -1] = 0.0
        res = float(np.max(np.abs(Phi_new - Phi)))
        Phi = Phi_new
        iters = it + 1
        if log_every and (it % log_every == 0):
            print(f"    relax it={it:5d}  max|ΔΦ|={res:.3e}")
        if res < tol:
            break
    return Phi, res, iters


# ───────────────────────────────────────────────────────────────────
#  Rest-leg quantities derived from any potential field
# ───────────────────────────────────────────────────────────────────

def clock_field(phi, c_0, mode="exact_isotropic"):
    """s(x) = √A(φ(x)) — the rest-leg renormalisation = local clock-tick rate."""
    A, _ = forkE.make_fork(mode).metric(np.asarray(phi, dtype=np.float64), c_0)
    return np.sqrt(np.abs(A))


def rest_leg(phi, c_0, m, mode="exact_isotropic"):
    """Ω_rest(x) = √A(x)·arcsin(m).  Identical functional form to F50."""
    return clock_field(phi, c_0, mode) * float(np.arcsin(m))


def refractive_index(phi, c_0, mode="exact_isotropic", sector="rest_only"):
    """Eikonal refractive index n = c₀ / c_eff for a probe ray.

    sector = "rest_only" : ONLY the rest/clock leg is sourced by mass, the
                           spatial metric stays flat (B = 1).  Then
                           c_eff = c₀√A and  n = 1/√A.
    sector = "full"      : the spatial metric B is ALSO sourced (isotropic GR),
                           c_eff = c₀√(A/B) and  n = √(B/A).
    """
    A, B = forkE.make_fork(mode).metric(np.asarray(phi, dtype=np.float64), c_0)
    A = np.abs(A)
    if sector == "rest_only":
        c_eff = c_0 * np.sqrt(A)            # B := 1
    elif sector == "full":
        c_eff = c_0 * np.sqrt(A / B)
    else:
        raise ValueError("sector must be 'rest_only' or 'full'")
    return c_0 / c_eff


def eikonal_deflection(phi_slice, c_0, axis_long=0, axis_perp=1,
                       impact_index=None, window=None, mode="exact_isotropic",
                       sector="rest_only"):
    """Weak-field eikonal deflection of a straight ray through a 2D potential
    slice.  Ray travels along `axis_long` at a fixed transverse offset
    `impact_index` from the source; deflection α = −∫ ∂_⊥ n  dl   (bends toward
    higher n, i.e. toward the mass).  Returns α (radians, small).

    This is the standard weak-deflection integral; for n − 1 = κ·GM/(r c₀²) it
    evaluates to α = 2κ·GM/(b c₀²), so the coefficient K ≡ α b c₀²/(GM) reads
    off 2κ directly (κ = 1 → Newtonian/factor-1, κ = 2 → Einstein/factor-2).
    """
    phi_slice = np.asarray(phi_slice, dtype=np.float64)
    n = refractive_index(phi_slice, c_0, mode=mode, sector=sector)
    # transverse derivative ∂n/∂(perp), central difference, h = 1
    dn = np.gradient(n, axis=axis_perp)
    Lperp = n.shape[axis_perp]
    if impact_index is None:
        impact_index = Lperp // 2 + 6
    # extract the ray line at the chosen transverse offset
    sl = [slice(None), slice(None)]
    sl[axis_perp] = impact_index
    dn_line = dn[tuple(sl)]
    Llong = dn_line.shape[0]
    if window is None:
        lo, hi = 0, Llong
    else:
        c = Llong // 2
        lo, hi = max(0, c - window), min(Llong, c + window)
    alpha = -np.sum(dn_line[lo:hi])        # ∫ dl with dl = 1 lattice cell
    return float(alpha)


# ───────────────────────────────────────────────────────────────────
#  Harness drop-in
# ───────────────────────────────────────────────────────────────────

NAME = "fork_F52_restleg_backreaction"
DESCRIPTION = ("Gravity as a self-consistent rest-leg (clock-rate) field "
               "sourced directly by mass; reproduces F50 lapse + factor-1 "
               "redshift; rest-leg-only deflection is Newtonian factor-1.")
