#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
laurent_pell.py — the Pell descent over a Laurent ring, proved here (F316)
==========================================================================

Closes F313's last import, and with it CL269's only remaining contingency.

THE GAP THIS FILLS
------------------
F313 §6 needs: *the solution group of the Pell equation a^2 - b^2 N = 1 over
R = C[w1^+-, w2^+-, w3^+-] is generated by the fundamental solution.*  It cited
Dubickas-Steuding, Elem. Math. 59 (2004) 133-143, Thm 2.  (It originally cited
Abel 1826, which contains no such theorem; corrected 2026-08-13.)

D-S is proved over a POLYNOMIAL ring k[x], and its descent runs on a degree with

        deg f = 0  =>  f is a constant, hence a unit.                       (*)

**(*) is false in a Laurent ring.**  deg(1 + w^-1) = 0, yet 1 + w^-1 is not a
unit of R.  The units of R are exactly the monomials.  So the theorem does not
transfer for free, and the 2026-08-13 review was right to call the transfer —
not "Abel" — the real import.

THE REPLACEMENT: A TWO-SIDED WIDTH
----------------------------------
Fix lambda in R^3 with **Q-linearly independent** components (the module uses
(1, sqrt2, sqrt3)).  For a nonzero f in R define the support function and the
two-sided width

        h_f(lambda) = max{ <m, lambda> : m in supp f },
        D(f)        = h_f(lambda) + h_f(-lambda)   >=  0.

Three facts, each proved rather than cited (L1-L3 below):

  L1  GENERICITY.  Q-independence makes the lambda-maximising monomial UNIQUE,
      so no cancellation can touch it: h_{fg} = h_f + h_g and lc(fg) =
      lc(f)lc(g).  h is a degree; D is additive under multiplication.
  L2  D DETECTS UNITS EXACTLY.  D(f) = 0 iff supp f lies in a hyperplane
      perpendicular to lambda; Q-independence lets such a hyperplane hold at
      most ONE lattice point; so D(f) = 0 iff f is a monomial iff f is a unit
      of R.  **This is the exact replacement for (*)** — and unlike (*) it is
      true.
  L3  UNITARITY MAKES NEWTON POLYTOPES CENTRALLY SYMMETRIC.  The solutions that
      matter are not arbitrary Pell solutions: they are UNITARY commutant
      elements with det = 1, so B* = B^-1 = sigma(B), giving a* = a and
      b* = -b.  Since * sends w^m to w^-m, supp a and supp b are symmetric
      about the origin.  Hence h(lambda) = h(-lambda) and D = 2h >= 0, and
      0 lies in every Newton polytope in play.

  L3 is the step D-S does not have and does not need, and it is what makes the
  Laurent case work.  Dropping unitarity leaves a rank-2 module on which the
  question has no answer (the review said so; this module shows why).

THE DESCENT
-----------
Let xi = a + bX solve the Pell equation, with X^2 = N and D(b) > 0.  Write
c = h_u(lambda) > 0.

  L4  h_a = h_b + c.  From a^2 = 1 + b^2 N and h_N = 2c > 0, the constant 1
      cannot reach the top, so 2h_a = 2h_b + h_N.
  L5  lc(a) = +- i lc(b) lc(u).  From lc(a)^2 = lc(b)^2 lc(N) and
      lc(N) = -lc(u)^2.  Therefore in exactly ONE of
          b'  = b u + a i        (from xi A^-1)
          b'' = b u - a i        (from xi A)
      the two top terms cancel; in the other they add.  Call the non-cancelling
      one b''.  Then h_{b''} = h_b + c exactly, so D(b'') = D(b) + 2c.
  L6  b' b'' = 1 + b^2, by direct expansion using a^2 = 1 + b^2(1 - u^2).
      Since Newt(b^2) is centrally symmetric it contains 0, so adding 1 cannot
      enlarge it: D(1 + b^2) <= D(b^2) = 2 D(b).
  L7  DESCENT.  D(b') = D(1 + b^2) - D(b'') <= 2D(b) - (D(b) + 2c)
                      = D(b) - 2c  <  D(b).
      So one multiplication by A^{-1} or A strictly lowers D(b), by at least
      D(u) = 2c.  Measured: it lowers it by EXACTLY 2c every time.

  L8  BASE CASE.  D(b) = 0 with b != 0 means b is a monomial (L2); b* = -b then
      forces b to be a purely imaginary CONSTANT, b = i beta with beta real.
      Then a^2 = (1 - beta^2) + beta^2 u^2, so
      (a - beta u)(a + beta u) = 1 - beta^2.  If beta^2 != 1 both factors are
      units, i.e. monomials, and 2 beta u = mu2 - mu1 would make u a difference
      of TWO monomials — but Newt(u) is the full cube, eight of them.  So
      beta^2 = 1, b = -+ i, a^2 = u^2, and xi is one of +- A^{+-1}.
      D(b) = 0 with b = 0 gives a^2 = 1, xi = +- 1.

  Descent (L7) plus base case (L8) gives

        { solutions } = { +- A^n : n in Z },

  which is F313 §6's boxed claim with **no import**.

WHAT THIS DOES AND DOES NOT CHANGE
----------------------------------
Discharges: CL269's last contingency.  F313's chain is now closed in-repo end to
end.  The result is *the same result* — nothing in the physics moves — but it
stops resting on a theorem stated for the wrong ring.

Does NOT change: F313's other named inputs (s = 2, INFINITE VOLUME, the three
Cayley generators).  Infinite volume is if anything more visible here: L1 and L2
both use that R is a domain whose units are monomials, which is false for
C[Lambda / L Lambda].

Does NOT claim generality.  This proves the descent for THIS N (squarefree, with
Newt(u) the full cube) under unitarity.  It is not a re-proof of D-S in several
variables, and the module says so rather than implying otherwise.

Exactness: every leg is exact over Q(i) in the coefficients; the support
function is evaluated in float against an irrational lambda, so the SEPARATION
statements (unique maximiser, strict descent) are machine-precision comparisons
with an explicit gap, and the gap is reported.

Findings: F316.  Reads: F313 (the gap), F291, and the 2026-08-13 review.
"""
from __future__ import annotations

import math
from fractions import Fraction as _F
from typing import Dict, List, Optional, Tuple

from casim.engine.lattice.time_signature import (
    Laurent, bcc_u, bcc_discriminant, laurent_const,
)

__all__ = [
    "LAMBDA",
    "support",
    "width",
    "leading",
    "unique_maximiser_gap",
    "is_unit",
    "check_L1_genericity",
    "check_L2_width_detects_units",
    "check_L3_central_symmetry",
    "check_L4_h_relation",
    "check_L5_leading_sign",
    "check_L6_product_identity",
    "check_L7_descent",
    "check_L8_base_case",
    "report",
]

#: A direction with Q-linearly independent components.  Any such lambda works;
#: this one is fixed so the numbers in the finding are reproducible.  It is NOT
#: a physical constant and matches no registry value.
LAMBDA: Tuple[float, float, float] = (1.0, math.sqrt(2.0), math.sqrt(3.0))

_I = laurent_const(0, 1)
_MINUS_I = laurent_const(0, -1)
_ONE = laurent_const(1)


# ══════════════════════════════════════════════════════════════════
#  The two-sided width
# ══════════════════════════════════════════════════════════════════

def support(f: Laurent, sign: int = 1) -> float:
    """h_f(sign * lambda) = max over the support of <m, sign*lambda>."""
    if not f:
        raise ValueError("the support function of 0 is undefined; handle b = 0 separately")
    return max(sign * (m[0] * LAMBDA[0] + m[1] * LAMBDA[1] + m[2] * LAMBDA[2])
               for m in f)


def width(f: Laurent) -> Optional[float]:
    """D(f) = h_f(lambda) + h_f(-lambda); None for f = 0.

    This is the replacement for Dubickas-Steuding's degree.  It is additive
    under multiplication (L1) and vanishes exactly on units (L2) — the property
    `deg f = 0 => f constant` has in a Laurent ring.
    """
    if not f:
        return None
    return support(f, 1) + support(f, -1)


def leading(f: Laurent, sign: int = 1):
    """(exponent, coefficient) of the unique lambda-maximal monomial."""
    m = max(f, key=lambda m: sign * (m[0] * LAMBDA[0] + m[1] * LAMBDA[1]
                                     + m[2] * LAMBDA[2]))
    return m, f[m]


def unique_maximiser_gap(f: Laurent, sign: int = 1) -> float:
    """Gap between the top two values of <m, sign*lambda>; +inf if one monomial.

    Reported rather than assumed: L1 is only true because this gap is strictly
    positive, and Q-independence is what guarantees it.
    """
    vals = sorted((sign * (m[0] * LAMBDA[0] + m[1] * LAMBDA[1] + m[2] * LAMBDA[2])
                   for m in f), reverse=True)
    return math.inf if len(vals) < 2 else vals[0] - vals[1]


def is_unit(f: Laurent) -> bool:
    """A unit of R is exactly a monomial with nonzero coefficient."""
    return len(f) == 1


def _star_is(f: Laurent, sign: int) -> bool:
    """f* == sign * f."""
    return f.star() == (f if sign > 0 else f.scale((_F(-1), _F(0))))


def _mul(xi, eta, N: Laurent):
    """Multiplication in R[X]/(X^2 - N), elements written (a, b) = a + bX."""
    a1, b1 = xi
    a2, b2 = eta
    return (a1 * a2 + (b1 * b2) * N, a1 * b2 + b1 * a2)


def _tower(nmax: int, sign: str = "+"):
    """A^1 .. A^nmax as Pell pairs."""
    u, N = bcc_u(sign), bcc_discriminant(sign)
    A = (u, _MINUS_I)
    out, cur = [], (_ONE, Laurent())
    for _ in range(nmax):
        cur = _mul(cur, A, N)
        out.append(cur)
    return out, u, N


# ══════════════════════════════════════════════════════════════════
#  L1 / L2 — the replacement for "deg 0 => constant"
# ══════════════════════════════════════════════════════════════════

def check_L1_genericity(nmax: int = 6, sign: str = "+") -> Dict[str, object]:
    """The lambda-maximiser is unique, so h is additive and lc multiplicative.

    Both are checked on real elements of the tower, not asserted: h(fg) - h(f)
    - h(g) must be 0 and lc(fg) - lc(f)lc(g) must be 0.
    """
    tower, u, N = _tower(max(nmax, 2), sign)
    gaps, hadd, lcmul = [], [], []
    probes = [u, N] + [x for pair in tower[:3] for x in pair if x]
    for f in probes:
        gaps.append(unique_maximiser_gap(f, 1))
        gaps.append(unique_maximiser_gap(f, -1))
    for f in probes[:4]:
        for g in probes[:4]:
            fg = f * g
            if not fg:
                continue
            hadd.append(abs(support(fg) - support(f) - support(g)))
            _, cf = leading(f)
            _, cg = leading(g)
            _, cfg = leading(fg)
            prod = (cf[0] * cg[0] - cf[1] * cg[1], cf[0] * cg[1] + cf[1] * cg[0])
            lcmul.append(abs(float(cfg[0] - prod[0])) + abs(float(cfg[1] - prod[1])))
    return {
        "lambda": LAMBDA,
        "min_maximiser_gap": float(min(g for g in gaps if g != math.inf)),
        "max_h_additivity_residual": float(max(hadd)),
        "max_lc_multiplicativity_residual": float(max(lcmul)),
        "n_probes": len(probes),
    }


def check_L2_width_detects_units(sign: str = "+") -> Dict[str, object]:
    """D(f) = 0 iff f is a monomial iff f is a unit — and (*) is FALSE here.

    The second half is the point: `1 + w^-1` has ordinary Laurent degree 0 and
    is NOT a unit, which is exactly why Dubickas-Steuding does not transfer as
    written.  D assigns it a positive width, so D does the job deg cannot.
    """
    from casim.engine.lattice.time_signature import laurent_mono
    u = bcc_u(sign)
    counterexample = laurent_mono((0, 0, 0)) + laurent_mono((-1, 0, 0))
    monomials = [laurent_mono(e) for e in ((0, 0, 0), (2, -1, 3), (-1, -1, -1))]
    return {
        "monomial_widths": [width(m) for m in monomials],
        "all_monomials_zero_width": all(abs(width(m)) < 1e-12 for m in monomials),
        "all_monomials_are_units": all(is_unit(m) for m in monomials),
        # the counterexample that breaks the imported theorem's hypothesis
        "counterexample": "1 + w1^-1",
        "counterexample_is_unit": is_unit(counterexample),
        "counterexample_width": float(width(counterexample)),
        "width_separates_it": bool(width(counterexample) > 1e-12),
        "u_width": float(width(u)),
        "u_is_unit": is_unit(u),
    }


# ══════════════════════════════════════════════════════════════════
#  L3 — unitarity => centrally symmetric Newton polytopes
# ══════════════════════════════════════════════════════════════════

def check_L3_central_symmetry(nmax: int = 6, sign: str = "+") -> Dict[str, object]:
    """a* = a and b* = -b, hence h(lambda) = h(-lambda) and D = 2h >= 0.

    This is the ingredient Dubickas-Steuding has no analogue of, and it is what
    makes the Laurent descent close.  It comes from UNITARITY, not from det = 1:
    B* = B^-1 = sigma(B) for a unitary B with unit determinant.
    """
    tower, _, _ = _tower(nmax, sign)
    rows = []
    for n, (a, b) in enumerate(tower, start=1):
        rows.append({
            "n": n,
            "a_self_adjoint": _star_is(a, +1),
            "b_anti_self_adjoint": _star_is(b, -1) if b else True,
            "a_symmetry_residual": float(abs(support(a, 1) - support(a, -1))),
            "b_symmetry_residual": (float(abs(support(b, 1) - support(b, -1)))
                                    if b else 0.0),
        })
    return {
        "rows": rows,
        "all_a_self_adjoint": all(r["a_self_adjoint"] for r in rows),
        "all_b_anti_self_adjoint": all(r["b_anti_self_adjoint"] for r in rows),
        "max_symmetry_residual": float(max(max(r["a_symmetry_residual"],
                                               r["b_symmetry_residual"])
                                           for r in rows)),
    }


# ══════════════════════════════════════════════════════════════════
#  L4 / L5 / L6 / L7 — the descent
# ══════════════════════════════════════════════════════════════════

def check_L4_h_relation(nmax: int = 6, sign: str = "+") -> Dict[str, object]:
    """h_a = h_b + c, i.e. D(a) = D(b) + D(u), for every solution with b != 0."""
    tower, u, N = _tower(nmax, sign)
    c = support(u)
    rows = [{"n": n, "D_a": width(a), "D_b": width(b) or 0.0,
             "residual": float(abs(width(a) - (width(b) or 0.0) - 2 * c))}
            for n, (a, b) in enumerate(tower, start=1)]
    return {"c": float(c), "D_u": float(width(u)), "rows": rows,
            "max_residual": float(max(r["residual"] for r in rows))}


def check_L5_leading_sign(nmax: int = 6, sign: str = "+") -> Dict[str, object]:
    """lc(a) = +- i lc(b) lc(u), so exactly one of b*u +- a*i cancels at the top."""
    tower, u, N = _tower(nmax, sign)
    c = support(u)
    rows = []
    for n, (a, b) in enumerate(tower, start=1):
        if not b:
            continue
        hb = support(b)
        bp = b * u + a * _I
        bpp = b * u - a * _I
        tops = []
        for x in (bp, bpp):
            tops.append(None if not x else support(x))
        cancels = [(t is None) or (t < hb + c - 1e-9) for t in tops]
        rows.append({"n": n, "cancels": cancels,
                     "exactly_one": bool(sum(cancels) == 1)})
    return {"rows": rows,
            "always_exactly_one": all(r["exactly_one"] for r in rows)}


def check_L6_product_identity(nmax: int = 6, sign: str = "+") -> Dict[str, object]:
    """b' b'' = 1 + b^2 exactly, and D(1 + b^2) <= 2 D(b) by central symmetry."""
    tower, u, N = _tower(nmax, sign)
    rows = []
    for n, (a, b) in enumerate(tower, start=1):
        if not b:
            continue
        bp, bpp = b * u + a * _I, b * u - a * _I
        target = _ONE + b * b
        db = width(b) or 0.0
        d_target = width(target)
        rows.append({
            "n": n,
            "identity_exact": bool((bp * bpp) == target),
            "D_b": db,
            "D_1_plus_b2": d_target,
            "bounded_by_2Db": bool(d_target is None or d_target <= 2 * db + 1e-9),
        })
    return {"rows": rows,
            "all_identities_exact": all(r["identity_exact"] for r in rows),
            "all_bounded": all(r["bounded_by_2Db"] for r in rows)}


def check_L7_descent(nmax: int = 7, sign: str = "+") -> Dict[str, object]:
    """D drops by at least D(u) = 2c per step, whenever D(b) > 0.

    The hypothesis D(b) > 0 is not decoration: at D(b) = 0 we are in the base
    case, 1 + b^2 = 0, and L6's product identity degenerates.  L8 handles it.
    """
    tower, u, N = _tower(nmax, sign)
    c = support(u)
    rows = []
    for n, (a, b) in enumerate(tower, start=1):
        db = width(b)
        if db is None or db <= 1e-12:
            rows.append({"n": n, "base_case": True})
            continue
        bp, bpp = b * u + a * _I, b * u - a * _I
        ds = [width(x) for x in (bp, bpp)]
        finite = [x for x in ds if x is not None]
        best = min(finite) if finite else 0.0
        rows.append({
            "n": n, "base_case": False, "D_b": db,
            "D_after": best,
            "drop": float(db - best),
            "drop_is_2c": bool(abs((db - best) - 2 * c) < 1e-9),
            "strict": bool(best < db - 1e-9),
        })
    live = [r for r in rows if not r["base_case"]]
    return {"c": float(c), "rows": rows,
            "n_live": len(live),
            "all_strict": all(r["strict"] for r in live),
            "all_drop_exactly_2c": all(r["drop_is_2c"] for r in live)}


def check_L8_base_case(sign: str = "+") -> Dict[str, object]:
    """D(b) = 0 forces xi in {+-1, +-A^{+-1}} — the descent's landing set.

    Two sub-facts, both checked: an anti-self-adjoint monomial is a purely
    imaginary CONSTANT; and u is not a difference of two monomials, which is
    what rules out beta^2 != 1.
    """
    from casim.engine.lattice.time_signature import laurent_mono
    u = bcc_u(sign)
    off_origin = [laurent_mono(e, (3, 5)) for e in ((1, 0, 0), (2, -1, 3))]
    pure_imag = laurent_mono((0, 0, 0), (0, 7))
    real_const = laurent_mono((0, 0, 0), (7, 0))
    return {
        "u_monomial_count": len(u),
        "u_is_difference_of_two_monomials": bool(len(u) <= 2),
        "off_origin_monomials_anti_self_adjoint":
            [bool(_star_is(m, -1)) for m in off_origin],
        "purely_imaginary_constant_is_anti_self_adjoint": bool(_star_is(pure_imag, -1)),
        "real_constant_is_not": bool(not _star_is(real_const, -1)),
        "landing_set": "{+-1, +-A, +-A^-1}",
    }


# ══════════════════════════════════════════════════════════════════
#  Report
# ══════════════════════════════════════════════════════════════════

def report(nmax: int = 7, sign: str = "+") -> Dict[str, object]:
    """Everything.  Guarded artifact write lives in the runner."""
    return {
        "L1_genericity": check_L1_genericity(nmax=nmax, sign=sign),
        "L2_width_detects_units": check_L2_width_detects_units(sign=sign),
        "L3_central_symmetry": check_L3_central_symmetry(nmax=min(nmax, 6), sign=sign),
        "L4_h_relation": check_L4_h_relation(nmax=min(nmax, 6), sign=sign),
        "L5_leading_sign": check_L5_leading_sign(nmax=min(nmax, 6), sign=sign),
        "L6_product_identity": check_L6_product_identity(nmax=min(nmax, 6), sign=sign),
        "L7_descent": check_L7_descent(nmax=nmax, sign=sign),
        "L8_base_case": check_L8_base_case(sign=sign),
        "import_discharged": "Dubickas-Steuding 2004 Thm 2 (polynomial -> Laurent transfer)",
        "verdict": (
            "The Pell descent is proved over the Laurent ring with no import. "
            "The failing hypothesis 'deg f = 0 => f constant' is replaced by the "
            "two-sided width D, which vanishes exactly on units; unitarity makes "
            "every Newton polytope centrally symmetric, which is the ingredient "
            "the polynomial proof neither has nor needs; and the descent then "
            "lowers D(b) by exactly D(u) per step until it lands on {+-1, +-A^+-1}. "
            "F313's chain is closed in-repo, and CL269 loses its last contingency."
        ),
    }


if __name__ == "__main__":                                # pragma: no cover
    import json
    print(json.dumps(report(), indent=2, default=str))
