#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
time_single_generator.py — the "+1" closes: no second candidate generator (F326)
==================================================================================

F291 §7 named the missing step: *"a genuine derivation of the '+1' would have
to explain why the Cayley-graph/update split is not itself a choice."* F313
computed the split's ANATOMY (the commutant of the update A splits by det into
exactly the shift lattice and exactly the powers of A) and that survives its
own 2026-08-13 remediation intact (§§3-7 / C1-C4). What the remediation
withdrew was different: an $s$-general formula (§8, numerology) and the claim
that $d_\text{space}=3$ falls OUT of that same computation (§5, circular).

Neither withdrawal touches the question this module closes, which F313 never
asked: **why is there only one candidate generator $A$ to take the commutant
OF, in the first place?** F313 assumed a first flow and asked what else
commutes with it. This module asks where that first flow comes from, and
answers it from two facts already load-bearing everywhere else in the tree —
recomputing neither.

THE ARGUMENT
------------
1. **BDPT uniqueness is not new here — it is the theorem the whole model
   already stands on.** F291 §1 opens by citing it: fixing the axioms
   (linearity, unitarity, locality, homogeneity, isotropy) and the minimal
   cell $s=2$, the walk solving them is UNIQUE **in each dimension**, up to
   conjugation and the two-branch (chirality) sign. There is no family of
   inequivalent solutions at $(s,d)=(2,3)$ to choose a SECOND one from — the
   axioms this project already adopted for every other reason (F291's own
   selectors lean on founding decisions 1 and 2, which presuppose the walk)
   pin down one operator, not a two-parameter family.
2. **F313 §§3-4 (undisturbed by the remediation) show that ANYTHING
   commuting with that one operator is already accounted for**: the
   local-homogeneous-unitary commutant of $A$ is exactly 2-dimensional,
   $\mathrm{span}\{\mathbb I,\ \boldsymbol\sigma\cdot\tilde{\mathbf n}\}$, and
   splits by $\det$ into the shift lattice (space, already counted by F291)
   and the powers of $A$ itself (the one time direction already have). A
   putative second, INDEPENDENT commuting generator would have to be an
   element of that same 2-dimensional space — there is no third piece to be
   one.
3. Combining 1 and 2: there is no second candidate generator EITHER because
   BDPT's uniqueness theorem does not hand one to start from, OR because, if
   one is proposed as commuting with $A$, F313's own closed commutant result
   has already exhausted the space it could live in. Both routes are already
   in the tree; nothing above re-derives either.

WHAT REMAINS OPEN, NAMED RATHER THAN HIDDEN
--------------------------------------------
Steps 1-2 both take as given that the model's dynamics is **one map iterated**
— a single local, homogeneous, unitary operator $A$ applied synchronously to
the whole lattice once per tick, generating a $\mathbb Z$-action. That is not
an extra assumption bolted onto the BDPT axioms; it is what "cellular
automaton" already means in the literature this project cites
(`references/qca-papers-1-4-overview.md`: *"The discrete time T comes from
the automaton's update steps"* — Paper 1's own account of where time comes
from at all) and in the founding statement of this project (`CLAUDE.md`
"Core Idea": *a cellular automaton, modelled on a computer*). No route in this
tree derives "the dynamics is generated by iterating a single map" from
anything more primitive, any more than "local," "homogeneous," or "unitary"
are derived from anything more primitive — they, too, are BDPT's axioms, not
its conclusions.

**What a genuine alternative would look like, and why it is not attempted
here.** A theory built from TWO independent generators from the start — not
derived as symmetries of a first one, but posited jointly — is a real
category in the physics literature: Itzhak Bars' two-time physics program
(I. Bars, "Survey of two-time physics," *Class. Quantum Grav.* **18** (2001)
3113, arXiv:hep-th/0008164) takes a literal second timelike dimension
seriously and shows that consistency (removing the extra direction's
negative-norm / ghost content) requires an additional local $Sp(2,\mathbb
R)$ gauge symmetry — under which the physically observable dynamics reduces
to an ordinary ONE-time theory again, the second direction surviving only as
gauge redundancy ("shadows" of one 2T theory). In the one place a genuine
second time direction is taken seriously and made to work, it is not an
additional physical direction — it is the same one-time dynamics with extra
redundancy. This is cited as informed CONTRAST, not as a theorem about this
model: this project has not built (and this module does not attempt) an
$Sp(2,\mathbb R)$-gauged extension of the BCC walk to check whether the same
collapse happens here. It is offered as the reason single-generator dynamics
is the economical, non-pathological starting point, on the same footing as
every other adopted axiom.

TWO NEW GROUNDING CHECKS
-------------------------
The argument above cites established results; it does not re-derive them.
What IS new here is checking that the running engine actually embodies the
"one map, iterated" premise it is built on, at two levels:

  G1  ``check_engine_single_global_clock`` — `casim.engine.core.clock.Clock`
      carries exactly one persisted time field (`tick`); `Channel` carries
      none; and a live multi-channel `Simulation`, including a channel whose
      native `dt` is finer than the global tick (`n_sub > 1`), advances by
      exactly one `Clock.tick` per `step()` call while every channel's finer
      stepping is a DETERMINISTIC subdivision of that same call, not an
      independently free-running counter.
  G2  ``check_dirac_composite_single_generator`` — on the model's own $s=4$
      COUPLED composite (both BDPT chirality branches, non-zero mass — the
      exact object F313 §9 / F315 studied), iterating the production stepper
      `dirac_step_3d_bcc_splitstep` $n$ times from a single Fourier mode
      reproduces $D_k^n$ applied once to that mode's amplitude, to machine
      precision, for a single SHARED integer $n$ — the stepper's signature
      admits one `dt` for the whole four-component object, not an
      independent one per branch. Coupling the two chirality branches (F27's
      inter-branch mass step, needed for $d\ge3$ per F291 §4) does not
      introduce a second tick; it produces one matrix with off-diagonal
      structure, iterated once.

**What G2 is, and is not, evidence for (added 2026-08-20, review pass).**
`dirac_step_3d_bcc_splitstep` and `build_D_k_matrix` both bottom out in the
same primitives (`_kinetic_n(m)`, `bcc.bcc_unitary`) — one applies them
per-tick in real/Fourier space, the other assembles them once into a $4\times
4$ matrix. That the two agree to machine precision after $n$ applications is
therefore close to a tautology of *any* stateless linear per-tick map, single-
or multi-generator alike — it is a code self-consistency check (the
production stepper does not secretly carry two independently-clockable
rates, per ``stepper_has_no_branch_local_dt``), not independent physical
evidence that a second generator cannot exist. G2's real evidentiary weight
is the signature-inspection leg; the ${\sim}10^{-16}$ residual mainly confirms
FFT round-trip fidelity. §2 of the finding does not lean on G2 for the
uniqueness argument — only G1 and the signature check carry real
independence.

Findings: F326. Reads: F291 (§§1, 6, 7 — uniqueness, the residual, its
named price), F313 (§§3-7, C1-C4, undisturbed by its own remediation; §8/§5
withdrawn and NOT reused here), F316 (closes F313's own last import; not
re-derived here), F318 (the dispersive-clock criterion, cited not reused).
Does not touch F291 S1/S2, F292, or F313 C1-C4's own machinery.
"""
from __future__ import annotations

import dataclasses
import inspect
from typing import Dict, Tuple

from casim.numerics import xp, fft as _fft
from casim.constants import c_lat

from casim.engine.core.clock import Clock
from casim.engine.core.channel import Channel
from casim.engine.core.simulation import Simulation, LatticeSpec
from casim.engine.lattice.geometry import make_kgrid_3d
from casim.engine.particles.dirac_bcc import (
    dirac_step_3d_bcc_splitstep, build_D_k_matrix,
)

__all__ = [
    "check_engine_single_global_clock",
    "check_dirac_composite_single_generator",
    "check_all",
]


# ══════════════════════════════════════════════════════════════════
#  G1 — the engine's OWN time bookkeeping is one integer, not two
# ══════════════════════════════════════════════════════════════════

class _ProbeChannel(Channel):
    """A trivial channel used only to exercise the engine's step loop.

    Records how many times ``step`` was actually called on it within a
    single ``Simulation.step()`` call — the thing G1 needs to see directly,
    not infer.
    """
    type_name = "time_single_generator_probe"

    def __init__(self, name=None, dt_native=1.0, **config):
        super().__init__(name=name, dt_native=dt_native, **config)
        self.dt_native = dt_native
        self.calls = 0

    def init_state(self, lattice, rng):
        return {"calls": 0}

    def step(self, state, lattice, context=None, rng=None):
        self.calls += 1
        return {"calls": self.calls}

    def energy(self, state) -> float:
        return float(state["calls"])


def check_engine_single_global_clock(n_ticks: int = 3) -> Dict[str, object]:
    """The engine has exactly one persisted time counter, and nothing hides a second.

    Three legs, all asserted:

      (a) ``Clock`` (`casim.engine.core.clock`) persists exactly one
          time-bookkeeping field, ``tick``; ``time`` is a *derived* property
          (``tick * dt``), not independent state. ``timings`` is per-channel
          RECONCILIATION data (how many sub-steps each channel takes within
          one tick), not a second clock.
      (b) ``Channel`` (`casim.engine.core.channel`) carries no field that
          tracks elapsed time on its own — no channel can drift out of step
          with the engine's one counter because none HAS a counter.
      (c) A live two-channel ``Simulation``, one channel at the native
          resolution and one at twice it (``dt_native`` half the global
          ``dt``, forcing ``n_sub == 2``), is stepped ``n_ticks`` times.
          ``Simulation.tick`` advances by exactly ``n_ticks``, and the finer
          channel's own call count is exactly ``2 * n_ticks`` — a fixed,
          engine-determined multiple of the SAME outer count, not a
          separately advancing number.
    """
    clock_fields = {f.name for f in dataclasses.fields(Clock)}
    # `resolved_mode` and `mode` are configuration, not elapsed-time state;
    # `timings` is reconciliation data (leg (a)'s point); `tick` is the one
    # elapsed-time counter.
    time_state_fields = {"tick"}
    non_time_fields = clock_fields - time_state_fields - {
        "mode", "resolved_mode", "timings", "dt"}

    # Channel exposes several *unrelated* optional hooks (T_munu, block_spin,
    # consumes/provides for the bus, etc.) -- G1's claim is narrower and
    # sharper than "Channel has no other attributes": none of those hooks is
    # a TIME-tracking field, i.e. none of the names an independent clock
    # would need is present on the class at all.
    _time_like_names = {"tick", "time", "clock", "n_sub", "step_count",
                         "elapsed", "t", "dt_elapsed"}
    channel_stray_time_fields = _time_like_names & set(dir(Channel))

    lattice = LatticeSpec(L=4, dims=3, topology="cubic", c_lat=c_lat)
    fast = _ProbeChannel(name="fast", dt_native=0.5)
    slow = _ProbeChannel(name="slow", dt_native=1.0)
    # mode="strict" is what actually turns on sub-cycling (n_sub > 1); the
    # default "auto" mode falls back to "legacy" (forces n_sub=1,
    # desynchronised) precisely to stay bit-identical to pre-P3.2 runs, which
    # would hide the very thing G1(c) needs to see.
    sim = Simulation(lattice=lattice, channels=[slow, fast], seed=0,
                      name="G1-single-clock-probe", clock={"mode": "strict"})
    sim.step(n_ticks)

    fast_calls = sim.states["fast"]["calls"]
    slow_calls = sim.states["slow"]["calls"]
    n_sub_fast = sim.clock.n_sub("fast")

    out = {
        "clock_dataclass_fields": sorted(clock_fields),
        "clock_has_exactly_one_time_state_field": time_state_fields <= clock_fields
        and len(time_state_fields) == 1,
        "clock_stray_fields": sorted(non_time_fields),
        "channel_carries_no_time_field": channel_stray_time_fields == set(),
        "channel_stray_fields": sorted(channel_stray_time_fields),
        "n_ticks_requested": n_ticks,
        "sim_tick_after": sim.tick,
        "n_sub_fast": n_sub_fast,
        "slow_calls": slow_calls,
        "fast_calls": fast_calls,
        "fast_calls_is_deterministic_multiple":
            fast_calls == n_sub_fast * n_ticks,
        "slow_calls_equals_tick": slow_calls == sim.tick,
    }
    assert out["clock_has_exactly_one_time_state_field"], (
        f"Clock carries more than one persisted time-state field: {out}")
    assert out["channel_carries_no_time_field"], (
        f"Channel exposes its own time-tracking attribute(s): {out}")
    assert out["sim_tick_after"] == n_ticks, (
        f"Simulation.tick did not advance by exactly n_ticks: {out}")
    assert out["slow_calls_equals_tick"], (
        "the slow (native-resolution) channel's own call count drifted from "
        f"the single global tick counter: {out}")
    assert out["fast_calls_is_deterministic_multiple"], (
        "the finer channel's sub-stepping is NOT a deterministic multiple of "
        f"the one global tick — it would be a second, free-running clock: {out}")
    return out


# ══════════════════════════════════════════════════════════════════
#  G2 — the coupled two-branch composite is one matrix, iterated
# ══════════════════════════════════════════════════════════════════

def check_dirac_composite_single_generator(
        L: int = 4, n: int = 4, m: float = 0.37, sign: str = "+",
        mode_index: Tuple[int, int, int] = (1, 1, 0),
        direct_n_offset: int = 0,
) -> Dict[str, object]:
    """Iterating the production stepper n times == D_k^n applied once.

    This is F313 sec.9's own setting (mass != 0, both chirality branches
    coupled — the composite whose SECOND commuting flow V is what F315
    killed) but a different question: not "what else commutes with the
    joint object" but "is the joint object's own history the power series
    of ONE matrix". A single mode is isolated exactly (a plane wave is a
    delta in Fourier space), so the comparison is between two INDEPENDENT
    computations of the same number: the engine's real-space stepper run
    n times and FFT'd, versus `build_D_k_matrix` applied directly n times
    to the initial Fourier amplitude.

    CAVEAT (review pass, 2026-08-20): "independent" here means independently
    *coded* (real-space split-step vs. an explicit matrix build), not
    independent at the level of physical primitives -- both functions call
    the same `_kinetic_n`/`bcc.bcc_unitary` machinery underneath. The
    residual mainly certifies that this module's FFT round-trip and the
    stepper's own bookkeeping are correct; the part of this check that
    actually bears on "is this a single generator" is
    `stepper_has_no_branch_local_dt` (the signature has no per-branch dt),
    not the small residual by itself.
    """
    assert abs(m) < 1.0, "need a genuinely massive (coupled) composite"
    KX, KY, KZ = make_kgrid_3d(L, L, L)
    ix, iy, iz = mode_index
    kx, ky, kz = float(KX[ix, iy, iz]), float(KY[ix, iy, iz]), float(KZ[ix, iy, iz])

    # An arbitrary complex amplitude at that one mode, all four components
    # populated so both chirality branches start nonzero (chi is genuinely
    # excited too, not just carried passively by the mass coupling).
    psi0 = xp.array([1.0 + 0.3j, -0.4 + 0.2j, 0.15 - 0.6j, 0.5 + 0.1j],
                     dtype=complex)

    # -- independent computation 1: the algebraic matrix, iterated directly
    D = build_D_k_matrix(kx, ky, kz, m, sign=sign)
    unitarity_residual = float(
        xp.max(xp.abs(D.conj().T @ D - xp.eye(4, dtype=complex))))
    psi_direct = psi0.copy()
    # `direct_n_offset` (control only): deliberately iterate D_k a DIFFERENT
    # number of times than the engine actually ticks, so the comparison below
    # is exercised against a genuine mismatch rather than trivially agreeing
    # regardless of n.
    n_direct = max(n + direct_n_offset, 0)
    for _ in range(n_direct):
        psi_direct = D @ psi_direct

    # -- independent computation 2: the production real-space stepper
    def _delta_field(amp):
        F = xp.zeros((L, L, L), dtype=complex)
        F[ix, iy, iz] = amp
        return _fft.ifftn(F)

    eta_u = _delta_field(psi0[0])
    eta_d = _delta_field(psi0[1])
    chi_u = _delta_field(psi0[2])
    chi_d = _delta_field(psi0[3])
    for _ in range(n):
        eta_u, eta_d, chi_u, chi_d = dirac_step_3d_bcc_splitstep(
            eta_u, eta_d, chi_u, chi_d, m=m, dt=1.0, sign=sign)

    psi_engine = xp.array([
        _fft.fftn(eta_u)[ix, iy, iz],
        _fft.fftn(eta_d)[ix, iy, iz],
        _fft.fftn(chi_u)[ix, iy, iz],
        _fft.fftn(chi_d)[ix, iy, iz],
    ])

    residual = float(xp.max(xp.abs(psi_engine - psi_direct)))

    # The stepper's own signature admits one shared dt/tick for the whole
    # four-component object -- no per-branch dt parameter exists to give
    # eta and chi independent rates.
    sig = inspect.signature(dirac_step_3d_bcc_splitstep)
    param_names = set(sig.parameters)
    branch_local_time_params = {p for p in param_names
                                 if p not in ("eta_u", "eta_d", "chi_u",
                                              "chi_d", "m", "dt", "sign")}

    out = {
        "mode": (kx, ky, kz), "n": n, "m": m, "sign": sign,
        "D_unitarity_residual": unitarity_residual,
        "off_diagonal_coupling_nonzero": bool(abs(m) > 0
                                               and xp.max(xp.abs(D[0:2, 2:4])) > 0),
        "psi_direct": [complex(x) for x in psi_direct],
        "psi_engine": [complex(x) for x in psi_engine],
        "max_residual": residual,
        "stepper_params": sorted(param_names),
        "stepper_has_no_branch_local_dt": branch_local_time_params == set(),
    }
    assert out["D_unitarity_residual"] < 1e-10, out
    assert out["off_diagonal_coupling_nonzero"], (
        f"mass coupling between branches is not actually engaged: {out}")
    assert out["max_residual"] < 1e-8, (
        "iterating the production stepper n times does not reproduce D_k^n "
        f"applied once -- the joint object is NOT a single generator: {out}")
    assert out["stepper_has_no_branch_local_dt"], (
        "the production stepper exposes a per-branch time parameter, which "
        f"would make eta and chi independently clockable: {out}")
    return out


# ══════════════════════════════════════════════════════════════════
#  Report
# ══════════════════════════════════════════════════════════════════

def check_all(n_ticks: int = 3, n_dirac: int = 4, m: float = 0.37,
              break_single_clock: bool = False,
              break_composite_single_generator: bool = False) -> Dict[str, object]:
    """Registry entry point.

    ``break_single_clock`` (control): forces the probe channel's own call
        counter to be read against a WRONG multiple of the tick count
        (``n_ticks`` instead of ``n_sub * n_ticks``), which must go red
        whenever ``n_sub != 1`` -- exercising exactly the failure mode G1
        exists to catch (a channel silently running on its own clock).
    ``break_composite_single_generator`` (control): compares the engine's
        n-tick result against ``D_k`` applied only ``n-1`` times, which must
        go red -- a sanity check that G2's comparison is not vacuously
        passing regardless of n.
    """
    out = {}
    if break_single_clock:
        try:
            g1 = check_engine_single_global_clock(n_ticks=n_ticks)
            # If n_sub happens to be 1 the control cannot separate; force a
            # mismatched read directly instead of relying on the assertion.
            assert g1["fast_calls"] == n_ticks, (
                "CONTROL break_single_clock: asserting the WRONG relation "
                f"(fast_calls == n_ticks) which must fail when n_sub != 1: {g1}")
            out["G1_engine_single_global_clock"] = g1
        except AssertionError as exc:
            raise AssertionError(f"[control break_single_clock RED, as required] {exc}")
    else:
        out["G1_engine_single_global_clock"] = check_engine_single_global_clock(
            n_ticks=n_ticks)

    if break_composite_single_generator:
        # Deliberately compare n ticks of the engine's own stepper against
        # n-1 applications of D_k -- the check's own internal assertion
        # (max_residual < 1e-8) must go RED. If it didn't, the comparison
        # would be vacuous (agreeing regardless of n).
        try:
            out["G2_dirac_composite_single_generator"] = (
                check_dirac_composite_single_generator(
                    n=n_dirac, m=m, direct_n_offset=-1))
        except AssertionError as exc:
            raise AssertionError(
                f"[control break_composite_single_generator RED, as required] {exc}")
        else:
            raise AssertionError(
                "CONTROL break_composite_single_generator: comparing n engine "
                "ticks against n-1 applications of D_k did NOT go red -- the "
                "comparison is vacuous and proves nothing about n")
    else:
        out["G2_dirac_composite_single_generator"] = (
            check_dirac_composite_single_generator(n=n_dirac, m=m))

    out["n_checks"] = 2
    out["verdict"] = (
        "No second candidate generator exists to close the '+1' against: "
        "BDPT uniqueness (cited, not re-derived) leaves no second solution "
        "to start from, and F313 Sec.3-4's own commutant closure (cited, not "
        "re-derived) leaves no room for one to hide as a symmetry of the "
        "first. The one remaining input -- that the dynamics is a single "
        "map iterated -- is the same posit that defines a QCA at all, "
        "grounded here in the live engine (G1) and in the model's own "
        "coupled two-branch composite (G2, F313 sec.9's own object)."
    )
    return out


if __name__ == "__main__":                                # pragma: no cover
    import json
    print(json.dumps(check_all(), indent=2, default=str))
