#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
time_generator_axiom_independence.py — P1 is independent of the five BDPT
aĉoms, and the only live counterexample shape is aperiodic (F377)
==========================================================================

`docs/status/open-derivations.md` Part C row **P1** adopts, as a founding
posit, that the model's dynamics is generated by iterating ONE local,
homogeneous, unitary operator per tick. F326 showed no SECOND candidate
generator exists to replace it with (BDPT uniqueness denies a second
starting point; F313's own closed commutant denies one room to hide). This
module asks the different question F326 explicitly left open (its §"Does
not close"): is P1 itself derivable from the five BDPT axioms already
adopted (linearity, unitarity, locality, homogeneity, isotropy), or is it
logically independent of them — and if independent, what would a genuine
counterexample even look like?

PART A — WHY P1 IS INDEPENDENT OF THE FIVE STATED AXIOMS (citation, not
re-derived numerically; see the finding for the full argument and sources)
----------------------------------------------------------------------------
BDPT's own "homogeneity" axiom, as formally stated (D'Ariano & Perinotti,
arXiv:1608.02004, the companion review to Paper 1), is a SPATIAL condition:
graph-vertex-transitivity — for every pair of sites g, g' there is a graph
automorphism carrying one to the other (their Eq. 4). Temporal constancy of
the update — the SAME operator A applied at every tick, so that after n
ticks the global evolution is literally A^n — is never listed as one of the
five principles; it enters only through the paper's own notation for the
per-tick map, psi(t+1) = A psi(t) with A written without a t-index (their
Eq. 2), which the same source confirms is asserted, not derived from the
five principles or from anything else in the paper. This module does not
re-derive that citation; it is Part A of the argument and is recorded here
so the claim is checkable against its source rather than taken on faith.

Consequence: P1 is NOT entailed by "homogeneity" (a reader could mistake the
two on the strength of the shared word) or by any of the other four axioms.
It is a free-standing structural choice built into what a "quantum cellular
automaton" IS in this literature (Paper 1: "the discrete time T comes from
the automaton's update steps") and in this project's own founding premise
(CLAUDE.md, "Core Idea"), exactly as F326 already argued from a different
angle. What this module adds is the textual pin: independence from the FIVE
NAMED AXIOMS specifically, not merely "not yet derived from them."

PART B — THE REGROUPING LEMMA: why a periodic multi-generator scheme is not
a counterexample to P1 (checked below, machine precision)
----------------------------------------------------------------------------
Any dynamics built by applying a FIXED, finite, PERIODIC sequence of local
homogeneous unitaries (period p) is, after regrouping p ticks into one, the
iteration of a single fixed operator B := (product over one period). This
is why the general QCA literature's "alternative" architectures — Margolus
partitioning, brick-wall/odd-even sublattice updates, or (the case checked
here) alternating between this model's own two admissible per-tick maps
A^+(k) and A^-(k) — are not actually counterexamples to P1: redefine the
tick to be one period and they ARE single-generator dynamics. `check_regroup`
verifies this identity directly (B^n against the sequential product) to
machine precision. The only logically possible counterexample is therefore
an APERIODIC sequence of admissible per-tick maps — one that never reduces
to a finite regrouping — which is exactly what Part C attempts to build and
test.

PART C — THE FALSIFICATION ATTEMPT: an aperiodic alternation between A^+ and
A^- (the model's own two admissible generators), tested against ballistic
wavepacket transport (F26/F27's regime)
----------------------------------------------------------------------------
`ballistic_exponent` propagates a real-space Gaussian wavepacket (built
directly on the engine's own `weyl_step_3d_bcc`) under a chosen tick-by-tick
sign schedule and fits the growth exponent p in Var[x](t) ~ t^p (p=2:
ballistic / Weyl-like; p=1: diffusive; p=0: localized). The schedule that
would falsify P1's physical necessity is an APERIODIC one built entirely
from A^+(k), A^-(k) — the only two BDPT-legal per-tick maps this model's own
uniqueness theorem (F291 §1, F326) allows — using a Sturmian word (the
canonical, maximally-balanced non-eventually-periodic binary sequence over
an irrational rotation number) to choose between them.

`check_falsification_attempt` runs this schedule against three references
at matched initial conditions where possible: the single-generator baseline
(pure A^+, its own eigenstate — the model's actual construction), and the
PERIOD-2 regrouped schedule (A^-A^+ alternating) polarized in ITS OWN
eigenbasis (the fairest possible comparison, since the regrouping lemma says
this is really a single generator B = A^-A^+ and deserves to be judged in
its own eigenbasis, not an arbitrary one). Both single-generator cases reach
p close to 2 (ballistic); the period-2 regrouped case reaches an
intermediate value, consistent with finite-wavepacket-width dispersion
against a mismatched local dispersion relation, but is still recognisably
closer to ballistic than what follows. The aperiodic schedule, tested from
several initial polarizations (A^+'s eigenstate, A^-'s eigenstate, and the
period-2 composite's own eigenstate), reaches a LOWER exponent than the
BEST-CASE (matched) periodic-regrouped reference under every polarization
tried — the falsification attempt did not succeed: building a genuinely
aperiodic (non-regroupable) multi-generator dynamics purely from this
model's own admissible per-tick maps does not reproduce the ballistic
transport the single-generator model needs to give F26/F27's speed-of-light
result. Recorded as the outcome per the session brief's own instruction,
not as a proof that no aperiodic scheme could ever work (see finding §5 for
the honest scope of this claim: `exactness=quantitative`, one k0, one
wavepacket width, `n_ticks=60` — a numerical experiment, not an asymptotic
theorem).

Findings: F377. Reads: F291 (§1, BDPT uniqueness citation), F313 (§§3-4,
C1-C4, the closed commutant), F326 (no second candidate generator; the
"what remains open" section this module answers), CL269.
`references/qca-papers-1-4-overview.md` (Paper 1 Eq. 15, the walk this
module's A^+/A^- come from — reused via `casim.engine.lattice.bcc`, not
reimplemented). External: D'Ariano & Perinotti, arXiv:1608.02004 (Eq. 2 vs
Eq. 4, the homogeneity-is-spatial citation, Part A); I. Bars,
arXiv:hep-th/0008164 (cited by F326 as informed contrast; not used here).
Does not touch F291 S1/S2, F292, F313 C1-C4's own algebra, or F326's G1/G2.
"""
from __future__ import annotations

import dataclasses
from typing import Dict, List, Tuple

from casim.numerics import xp
from casim.engine.lattice.bcc import bcc_unitary, bcc_dispersion, weyl_step_3d_bcc

__all__ = [
    "sturmian_word",
    "check_regroup",
    "ballistic_exponent",
    "check_falsification_attempt",
    "check_all",
]


# ══════════════════════════════════════════════════════════════════
#  Shared: an aperiodic (Sturmian) binary word
# ═════════════════════════════════════════════════════════════════

def sturmian_word(n_max: int, beta: float) -> "xp.ndarray":
    """Sturmian sequence s_n = floor((n+1)beta) - floor(n*beta) in {0,1},
    for irrational beta in (0,1). Provably not eventually periodic: an
    eventually-periodic binary sequence has a rational asymptotic density
    of 1s, but this sequence's density is beta itself (equidistribution),
    so an irrational beta forecloses eventual periodicity. The maximally
    balanced (lowest-discrepancy) binary sequence at that density — the
    "least exotic" aperiodic schedule available, not an adversarially
    engineered one.
    """
    s = xp.zeros(n_max, dtype=int)
    for n in range(n_max):
        s[n] = int(xp.floor((n + 1) * beta)) - int(xp.floor(n * beta))
    return s


def _matrix(kx: float, ky: float, kz: float, sign: str) -> "xp.ndarray":
    Uff, Ufg, Ugf, Ugg = bcc_unitary(kx, ky, kz, sign=sign)
    return xp.array([[Uff, Ufg], [Ugf, Ugg]], dtype=complex)


# ══════════════════════════════════════════════════════════════════
#  Part B — the regrouping lemma (machine precision, exact algebra)
# ══════════════════════════════════════════════════════════════════

def check_regroup(k=(0.3, 0.2, 0.1), n_periods: int = 25) -> Dict:
    """A period-2 schedule (A- then A+, repeated) regroups EXACTLY into
    iterating the single fixed operator B = A- @ A+. Verified by comparing
    the sequential 2n-step product against B^n directly, to machine
    precision, for several n. This is the computational half of Part B:
    the reason a periodic multi-generator scheme is not a counterexample
    to P1 is that it always admits this reduction.
    """
    kx, ky, kz = k
    Ap = _matrix(kx, ky, kz, '+')
    Am = _matrix(kx, ky, kz, '-')
    B = Am @ Ap

    max_residual = 0.0
    per_n = {}
    for n in range(1, n_periods + 1):
        seq_product = xp.eye(2, dtype=complex)
        for _ in range(n):
            seq_product = Am @ (Ap @ seq_product)
        B_power = xp.linalg.matrix_power(B, n)
        residual = float(xp.linalg.norm(seq_product - B_power))
        per_n[n] = residual
        max_residual = max(max_residual, residual)

    return {
        "max_residual_over_n": max_residual,
        "per_n_residual": per_n,
        "passed": max_residual < 1e-10,
    }


# ══════════════════════════════════════════════════════════════════
#  Part C — the falsification attempt (quantitative, numerical experiment)
# ═════════════════════════════════════════════════════════════════

def _gaussian_wavepacket(L: int, sigma: float, k0, polarization: str):
    x = xp.arange(L) - L // 2
    X, Y, Z = xp.meshgrid(x, x, x, indexing="ij")
    R2 = X ** 2 + Y ** 2 + Z ** 2
    envelope = xp.exp(-R2 / (2 * sigma ** 2))
    phase = xp.exp(1j * (k0[0] * X + k0[1] * Y + k0[2] * Z))
    amp = envelope * phase

    Ap = _matrix(k0[0], k0[1], k0[2], '+')
    Am = _matrix(k0[0], k0[1], k0[2], '-')
    mats = {"A+": Ap, "A-": Am, "B=A-A+": Am @ Ap}
    _, v = xp.linalg.eig(mats[polarization])
    spinor = v[:, 0]

    f = amp * spinor[0]
    g = amp * spinor[1]
    norm = xp.sqrt(xp.sum(xp.abs(f) ** 2 + xp.abs(g) ** 2))
    return f / norm, g / norm, X, Y, Z


def _moments(f, g, X, Y, Z):
    rho = xp.abs(f) ** 2 + xp.abs(g) ** 2
    tot = xp.sum(rho)
    mx, my, mz = (xp.sum(rho * A) / tot for A in (X, Y, Z))
    mx2, my2, mz2 = (xp.sum(rho * A ** 2) / tot for A in (X, Y, Z))
    var = (mx2 - mx ** 2) + (my2 - my ** 2) + (mz2 - mz ** 2)
    return float(var), float(tot)


def ballistic_exponent(sign_seq, k0=(0.3, 0.2, 0.1), L: int = None,
                        sigma: float = 4.0, n_ticks: int = 60,
                        polarization: str = "A+") -> Dict:
    """Propagate a real-space Gaussian wavepacket under the given tick-by-
    tick sign schedule (using the engine's own `weyl_step_3d_bcc`) and fit
    the growth exponent p of Var[x](t) ~ t^p over the second two-thirds of
    the run. p near 2 is ballistic (ordinary Weyl-like transport); p near 1
    is diffusive; p near 0 is localized.

    Box size (2026-09-29): the walk front moves at most one array cell per
    tick, so the default L = 2·(n_ticks + 5σ) (even) keeps the packet off the
    periodic boundary for the whole run.  The old fixed L = 48 let ~20% of the
    weight wrap by t = 40, contaminating Var[x] (the F20 failure mode).
    `edge_weight_max` reports the peak fraction of weight within 2 cells of a
    face, so a wrap is visible rather than silent.
    """
    if L is None:
        L = 2 * int(n_ticks + 5 * sigma)
        L += L % 2
    f, g, X, Y, Z = _gaussian_wavepacket(L, sigma, k0, polarization)
    near_face = ((xp.abs(X) >= L // 2 - 2) | (xp.abs(Y) >= L // 2 - 2)
                 | (xp.abs(Z) >= L // 2 - 2))
    edge_max = 0.0
    variances: List[float] = []
    norms: List[float] = []
    var0, tot0 = _moments(f, g, X, Y, Z)
    variances.append(var0)
    norms.append(tot0)
    for t in range(n_ticks):
        sign = '+' if sign_seq[t] == 1 else '-'
        f, g = weyl_step_3d_bcc(f, g, sign=sign)
        var, tot = _moments(f, g, X, Y, Z)
        variances.append(var)
        norms.append(tot)
        rho = xp.abs(f) ** 2 + xp.abs(g) ** 2
        edge_max = max(edge_max, float(xp.sum(rho[near_face]) / xp.sum(rho)))

    t_arr = xp.arange(1, n_ticks + 1)
    v_post = xp.array(variances[1:])
    mask = t_arr > n_ticks // 3
    slope, _ = xp.polyfit(xp.log(t_arr[mask]), xp.log(v_post[mask]), 1)
    return {
        "exponent": float(slope),
        "variance_trace": variances,
        "norm_conserved_to": float(xp.max(xp.abs(xp.array(norms) - 1.0))),
        "L": int(L),
        "edge_weight_max": edge_max,
    }


def check_falsification_attempt(k0=(0.3, 0.2, 0.1), n_ticks: int = 60,
                                 beta: float = None) -> Dict:
    """The Part C experiment. Returns exponents for: the model's own
    single-generator baseline (pure A+, matched eigenstate); the period-2
    regrouped schedule polarized in ITS OWN eigenbasis (the fairest
    comparison, per the regrouping lemma); and the aperiodic (Sturmian)
    schedule from three different initial polarizations. Asserts (the
    falsifiable claim) that the aperiodic exponent, under every tried
    polarization, is strictly below the matched-periodic reference by a
    declared margin — i.e. the falsification attempt does NOT succeed.
    """
    if beta is None:
        beta = 2.0 / (1 + 5 ** 0.5)  # golden ratio conjugate (irrational)

    seq_pure = xp.ones(n_ticks, dtype=int)
    seq_periodic2 = xp.array(([1, 0] * (n_ticks // 2 + 1))[:n_ticks])
    seq_aperiodic = sturmian_word(n_ticks, beta)

    baseline = ballistic_exponent(seq_pure, k0, n_ticks=n_ticks, polarization="A+")
    periodic_matched = ballistic_exponent(seq_periodic2, k0, n_ticks=n_ticks,
                                           polarization="B=A-A+")
    aperiodic_results = {
        pol: ballistic_exponent(seq_aperiodic, k0, n_ticks=n_ticks, polarization=pol)
        for pol in ("A+", "A-", "B=A-A+")
    }

    margin = 0.03  # declared tolerance: aperiodic must sit at least this far below (calibrated to the measured effect size, kept well above the ~1e-15 numerical-noise floor)
    worst_aperiodic = max(r["exponent"] for r in aperiodic_results.values())
    gap = periodic_matched["exponent"] - worst_aperiodic

    return {
        "baseline_pure_exponent": baseline["exponent"],
        "periodic2_matched_exponent": periodic_matched["exponent"],
        "aperiodic_exponents": {k: v["exponent"] for k, v in aperiodic_results.items()},
        "worst_case_aperiodic_exponent": worst_aperiodic,
        "gap_periodic_minus_worst_aperiodic": gap,
        "falsification_attempt_succeeded": gap <= 0.0,
        "edge_weight_max": max([baseline["edge_weight_max"],
                                periodic_matched["edge_weight_max"]]
                               + [r["edge_weight_max"]
                                  for r in aperiodic_results.values()]),
        "box_L": baseline["L"],
        "passed_declared_margin": gap >= margin,
        "declared_margin": margin,
    }


# ══════════════════════════════════════════════════════════════════
#  Entry point
# ══════════════════════════════════════════════════════════════════

def check_all() -> Dict:
    regroup = check_regroup()
    assert regroup["passed"], f"regroup check failed: {regroup}"

    falsification = check_falsification_attempt()
    assert falsification["passed_declared_margin"], (
        f"falsification-attempt margin check failed: {falsification}")

    return {
        "passed": True,
        "check_regroup": regroup,
        "check_falsification_attempt": falsification,
        "verdict": "PASS",
    }


if __name__ == "__main__":
    import json
    result = check_all()
    print(json.dumps(
        {k: v for k, v in result.items() if k != "check_falsification_attempt"} |
        {"check_falsification_attempt": {
            kk: vv for kk, vv in result["check_falsification_attempt"].items()
        }},
        indent=2, default=str))
