#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
qi_so3_kinematic_gap.py — the model's emergent CONTINUOUS SO(3) is the wrong
KIND of object to supply Anastopoulos's Postulate 1 (completeness row A9,
continuing F330)
============================================================================

2026-09-10

F330 abandoned a lattice-native belt-trick derivation with a stated reason
(Sec.3): the discrete point group $O_h$ is finite and "carries no
fundamental-group content of its own that could stand in for" $\\pi_1(SO(3))$,
and the rotor's $\\Omega(\\mathbf k)$ is a *dynamical* (temporal) rotation rate,
not a *kinematic* (parallel-transport) one. The one route F330 explicitly left
open (see its own text): maybe the model's continuum-limit machinery — F129/
F130's block-spin RG (rubric A12, MACHINE: the dispersion becomes an isotropic
IR fixed point) or F344's exact leading-order covariance of the BCC Weyl walk
under all 48 elements of $O_h$ — recovers a genuinely CONTINUOUS $SO(3)$ (not
merely the finite $O_h$) that could supply Postulate 1 where the discrete
point group could not.

**This module tests that route directly, and closes it — for a reason that
generalises F330's diagnosis rather than merely extending it.**

The primary source, read directly (this session fetched the PDF, quant-ph/
0110169v3, rather than relying on F330's paraphrase). Anastopoulos's own
**Postulate 1** (his Sec.4.2, verbatim):

    "In combination of two identical systems, each characterised by a
    symmetry group G, it should be possible to obtain the permutation (3.3)
    by smooth transformations along the orbits of the diagonal action of G
    on Gamma_S."

with three explicit conditions: (i) G acts TRANSITIVELY by symplectomorphisms
on the CLASSICAL PHASE SPACE Gamma (S^2 for a single spin — no Hamiltonian
anywhere in the statement); (ii) two one-parameter subgroups realise the
positional exchange as paths that avoid the diagonal; (iii) the LIFT of that
action to the prequantising bundle composes correctly to the exchange phase.
Anastopoulos states explicitly that his whole construction lives at the level
of **prequantisation — "before constructing the physical Hilbert space"**
(Sec.1, point iii; Sec.4.3 opens "We proceed to study the possible
consequences... with respect to the REMAINING part of the... procedure",
i.e. after Postulate 1 is already assumed) and separately flags, discussing
group actions generally (Sec.3): "Symmetries are generated by a Hamiltonian
flow, but this is the case for dynamics only if time-translation is a
symmetry" — i.e. his own G-action is NOT presented as, and need not be, a
statement about any Hamiltonian's symmetry group at all.

**This is the key fact this module turns into a closed argument.** Postulate
1 is a claim about the CLASSICAL PHASE SPACE Gamma of the internal (spin)
degree of freedom and a transitive symplectic G-action on it — a fact of
representation theory (for spin: SO(3)/SU(2) acting transitively on S^2,
Sec.4.1, needing only the standard Hopf-bundle integrability condition
s=n/2) that is true for ANY spin-1/2 system whatsoever, model or no model,
Hamiltonian or no Hamiltonian. F129/F130/F344's "emergent SO(3)" results are
all claims of a DIFFERENT kind: that the model's own TIME EVOLUTION (the
dispersion relation, the leading-order Weyl Hamiltonian H_W = sigma.k/sqrt3)
becomes covariant under a continuous rotation group in a limit — a DYNAMICAL
(Hamiltonian-symmetry) fact. Since Postulate 1's content is stated, by the
paper's own architecture, strictly BEFORE any Hamiltonian is introduced, no
fact about the model's dynamics — however large the recovered symmetry group,
however exactly or emergently it is derived — can bear on it. Supplying an
emergent CONTINUOUS SO(3) where F330 found only a discrete O_h therefore
answers a question one logical layer downstream of the one Postulate 1 asks.

What is machine-verified below (K1-K3), and what it is NOT claimed to do
-------------------------------------------------------------------------
K1  The idealised leading-order Weyl Hamiltonian H_W(k) = k.sigma/sqrt(3)
    (cited from F26/F344's own title) is covariant under the FULL continuous
    SO(3) — not merely the 48 elements F344 checked — using literally the
    SAME rotor function (`su2_rotor` / `qi_spin_statistics._rotor_for_
    physical_angle`) that F289/F330 use for the spin-statistics argument
    itself.  This is a genuine, additive extension of F344 (which verified
    exactly 48 elements) to the continuous group, and it identifies the
    model's "emergent SO(3)" object with the spin-statistics rotor as the
    SAME mathematical object, not merely an analogous one.
K2  The ACTUAL shipped BCC dispersion (`bcc._bcc_uvec`, F344's own object,
    same p=(+1,-1,+1) branch convention) obeys the SAME continuous-rotation
    covariance law at leading order, with the covariance defect shrinking
    LINEARLY in |k| (relative to |n|) for a GENERIC continuous rotation not
    restricted to O_h — extending F344's leg C8 (which measured this only
    for the specific C3 body-diagonal rotation) to a swept family of generic
    axes and angles.
K3  CONTROL. Applying an UNCORRELATED rotor (spin transported via a
    DIFFERENT rotation than the one applied to momentum) breaks K1's identity
    at O(1) — confirming K1 is a genuine "same rotation, not some other
    unitary" statement (Postulate 1's own language, Sec.4, "rather than via
    some other, uncorrelated unitary" per F330's paraphrase) and not a
    vacuous SU(2)-closure fact.

**None of K1-K3 derives Postulate 1.** They positively confirm that the
model's continuum limit supplies a genuine, exact, machine-checked continuous
SO(3) acting jointly on (momentum, spin) via the identical rotor object used
throughout F289/F330/F344 — i.e. the DYNAMICAL half of "emergent SO(3)" is
real and is now extended from 48 elements to the full continuous group. What
closes the row is the structural argument above: this dynamical fact answers
a question that sits one logical layer downstream of Postulate 1's own
architecture (which needs a fact about the classical phase space Gamma and
the abstract exchange map on Gamma_S = (Gamma x Gamma - Delta)/S_2, defined
with NO reference to G's action, still less to a Hamiltonian). F330's own
diagnosis ("O_h is finite, Omega(k) is dynamical") generalises: it is not
that this model's specific emergent symmetry happens to be the wrong SIZE
(finite vs continuous); it is that ANY dynamical symmetry fact, of any size,
discrete or continuous, fundamental or emergent, is categorically the wrong
KIND of object, because Postulate 1 lives at the prequantisation level,
logically prior to any Hamiltonian whatsoever. Anastopoulos's own
Introduction (Sec.1) states the residual persists "in virtue of standard
quantum theory" -- i.e. independent of which specific quantum theory or
model is used, before any of the geometric construction is even built.

A second, deeper layer (found under review, see the finding's Sec.3): even a
genuinely KINEMATIC SO(3) action -- exact, transitive, on the classical phase
space, the correct KIND of object -- is still not enough on its own.
Anastopoulos's own Sec.4.1 worked example has exactly this (an exact
transitive symplectic SO(3) on S^2) and still needs Postulate 1's condition
(iii) -- the lift of the exchange path to the prequantising bundle -- as a
further, separate, ad hoc ingredient. So a future kinematic (rather than
dynamical) construction from this model's own structure would not close the
row merely by supplying a group action; it would still owe condition (iii).

What K1/K2 are, honestly stated: standard SU(2)-adjoint identities and their
Taylor-consistency corollaries, true for any correctly-parametrised rotor --
not new dynamics. Their genuine content is confirming these hold for THIS
model's actual rotor and dispersion code (both branches), not the abstract
"continuous vs discrete" generalisation by itself.

Cross-references: F330 (the belt-trick residual and its abandonment reason,
Sec.3), F289 (the rotor, R(2pi)=-1), F344 (the exact 48-element leading-order
covariance this module extends to the continuous group), F129/F130 (rubric
A12, the RG isotropy this module shows is the wrong kind of fact), F291
(the "lattice's isotropy group is a premise" weak link -- narrowed by F344,
now shown insufficient even in its continuous/emergent form). External:
Anastopoulos, quant-ph/0110169v3 ("Spin-Statistics Theorem and Geometric
Quantisation", published Int. J. Mod. Phys. A 19, 655 (2004)) -- Postulate 1,
Sec.4.2, and the prequantisation framing of Sec.1/Sec.3, fetched and read
directly this session, pages 1-16 + Appendix A/B.
"""
from __future__ import annotations

import math
from typing import Any, Dict, List, Tuple

from casim.numerics import xp as np

from casim.engine.interactions.qi_entanglement import su2_rotor, SX, SY, SZ
from casim.engine.interactions.qi_spin_statistics import _rotor_for_physical_angle
from casim.engine.lattice.bcc import _bcc_uvec

__all__ = [
    "rodrigues",
    "idealized_weyl_continuous_covariance",
    "shipped_walk_continuous_covariance_decades",
    "uncorrelated_rotor_control",
    "check_so3_kinematic_gap",
    "summary",
]

# ======================================================================
# Deterministic sampling (house convention: no RNG — Fibonacci-sphere axes,
# as in F289's rotor_phase_axis_independence / F330's _fibonacci_axes).
# ======================================================================
def _fibonacci_axes(n: int):
    golden = math.pi * (3.0 - math.sqrt(5.0))
    axes = []
    for i in range(n):
        z = 1.0 - 2.0 * (i + 0.5) / n
        r = math.sqrt(max(0.0, 1.0 - z * z))
        th = golden * i
        axes.append((r * math.cos(th), r * math.sin(th), z))
    return axes


def _generic_angles(n: int):
    """Angles deliberately offset from O_h's own characteristic angles
    (0, pi/2, pi, 3pi/2, 2pi/3, 4pi/3, ...) so the sweep tests CONTINUOUS
    rotations genuinely outside the discrete point group, not a relabelling
    of its 48 elements."""
    return [2.0 * math.pi * (j + 0.5) / n + 0.193723 for j in range(n)]


def rodrigues(axis, angle: float) -> np.ndarray:
    """The SO(3) rotation matrix for a continuous (axis, angle) pair —
    deliberately independent of O_h; any real axis and any real angle."""
    n = np.asarray(axis, dtype=float)
    n = n / np.linalg.norm(n)
    K = np.array([[0.0, -n[2], n[1]],
                  [n[2], 0.0, -n[0]],
                  [-n[1], n[0], 0.0]])
    I3 = np.eye(3)
    return I3 + math.sin(angle) * K + (1.0 - math.cos(angle)) * (K @ K)


def _dot_sigma(v) -> np.ndarray:
    return v[0] * SX + v[1] * SY + v[2] * SZ


# ======================================================================
# K1 — idealised H_W = k.sigma/sqrt(3): EXACT continuous SO(3) covariance,
#      via the SAME rotor object F289/F330 use.
# ======================================================================
def idealized_weyl_continuous_covariance(n_axes: int = 8, n_angles: int = 7,
                                         n_k: int = 5) -> Dict[str, Any]:
    """U(R) (k.sigma) U(R)^dagger == (Rk).sigma, for CONTINUOUS R (Rodrigues,
    not restricted to O_h's 48 elements), using su2_rotor(angle/2, axis) —
    F289/F330's own rotor function. An exact SU(2)-adjoint identity: should
    hold at the round-off floor for every swept (axis, angle, k), including
    axes/angles well outside O_h."""
    axes = _fibonacci_axes(n_axes)
    angles = _generic_angles(n_angles)
    k_axes = _fibonacci_axes(n_k)
    worst = 0.0
    n_checked = 0
    for axis in axes:
        for angle in angles:
            R = rodrigues(axis, angle)
            U = _rotor_for_physical_angle(angle, axis)
            for kdir in k_axes:
                k = np.asarray(kdir, dtype=float) * 0.37   # fixed nonzero |k|
                lhs = U @ _dot_sigma(k) @ U.conj().T
                rhs = _dot_sigma(R @ k)
                worst = max(worst, float(np.linalg.norm(lhs - rhs)))
                n_checked += 1
    return {"n_axes": n_axes, "n_angles": n_angles, "n_k": n_k,
            "n_checked": n_checked, "worst_residual": worst}


# ======================================================================
# K2 — the ACTUAL shipped BCC walk (bcc._bcc_uvec), extending F344's
#      48-element leg C8 to a swept family of GENERIC continuous rotations.
# ======================================================================
def shipped_walk_continuous_covariance_decades(
        axis=(0.4082482905, 0.4082482905, -0.8164965809),
        angle: float = 1.1071487178,
        decades: Tuple[float, ...] = (1e-1, 1e-2, 1e-3, 1e-4),
        branch: str = '+') -> Dict[str, Any]:
    """F344 Sec.3-4: the shipped leading-order n(k) is n = S k/sqrt(3) + O(k^2)
    with S = diag(p), p = (+1, -1, +1) on the '+' branch (F344's own
    convention). Hence for a continuous rotation R (not merely an O_h
    element), n(Rk) = (S R S^-1) n(k) + O(k^2) — pure linear algebra once the
    branch bookkeeping is applied, the SAME mechanism F344 verified only for
    the discrete C3 rotation (its leg C8). This function sweeps k down four
    decades at one fixed GENERIC (non-O_h) axis/angle and measures the
    relative defect ||n(Rk) - (S R S^-1) n(k)|| / |n(k)|, which F344's own
    closed-form argument (O(k^2) absolute, O(k) relative) predicts shrinks
    linearly in |k| — i.e. decade ratios converging to 10, exactly as F344's
    leg C8 found for its one (discrete) rotation."""
    # F344 Sec.3: p = (+1, -s, +1), s = +1 on '+' (giving diag(1,-1,1)) and
    # s = -1 on '-' (giving diag(1,1,1), the identity) -- NOT diag(-1,1,-1),
    # which was this module's own bug until the F379 review caught it
    # (branch='-' failed at O(1), never exercised by the gate's default).
    S = np.diag([1.0, -1.0, 1.0]) if branch == '+' else np.diag([1.0, 1.0, 1.0])
    R = rodrigues(axis, angle)
    Rp = S @ R @ S  # S^-1 = S for a diagonal +-1 matrix
    ax = np.asarray(axis, dtype=float) / np.linalg.norm(axis)
    defects = []
    for mag in decades:
        k = ax * mag
        kR = R @ k
        _, nx, ny, nz = _bcc_uvec(k[0], k[1], k[2], sign=branch)
        n_k = np.array([nx, ny, nz])
        _, nx2, ny2, nz2 = _bcc_uvec(kR[0], kR[1], kR[2], sign=branch)
        n_Rk = np.array([nx2, ny2, nz2])
        predicted = Rp @ n_k
        defect = float(np.linalg.norm(n_Rk - predicted))
        rel = defect / max(float(np.linalg.norm(n_k)), 1e-300)
        defects.append({"mag": float(mag), "defect_abs": defect,
                        "defect_relative": rel})
    ratios = [defects[i]["defect_relative"] / defects[i + 1]["defect_relative"]
              for i in range(len(defects) - 1)]
    return {"axis": tuple(float(a) for a in ax), "angle": float(angle),
            "branch": branch, "decades": defects, "decade_ratios": ratios}


# ======================================================================
# K3 — CONTROL: an UNCORRELATED spin rotation breaks K1's identity at O(1).
# ======================================================================
def uncorrelated_rotor_control(axis=(0.0, 0.0, 1.0), angle: float = 1.7,
                               wrong_axis=(1.0, 0.0, 0.0),
                               wrong_angle: float = 0.4) -> Dict[str, Any]:
    """Rotate k by R(axis, angle) but transport spin via an UNCORRELATED
    rotor U(wrong_axis, wrong_angle) instead of U(axis, angle). Demonstrates
    K1 is a real "same rotation" statement (Postulate 1's own "rather than
    some other, uncorrelated unitary") and not a vacuous SU(2)-closure fact
    that would pass for any pair of unitaries."""
    k = np.array([0.11, 0.23, -0.17])
    R = rodrigues(axis, angle)
    U_correct = _rotor_for_physical_angle(angle, axis)
    U_wrong = _rotor_for_physical_angle(wrong_angle, wrong_axis)
    rhs = _dot_sigma(R @ k)
    lhs_correct = U_correct @ _dot_sigma(k) @ U_correct.conj().T
    lhs_wrong = U_wrong @ _dot_sigma(k) @ U_wrong.conj().T
    return {"residual_correct_rotor": float(np.linalg.norm(lhs_correct - rhs)),
            "residual_uncorrelated_rotor": float(np.linalg.norm(lhs_wrong - rhs))}


# ======================================================================
# The registry entry point
# ======================================================================
def check_so3_kinematic_gap(use_uncorrelated_rotor: bool = False,
                            n_axes: int = 8) -> Dict[str, Any]:
    """The gate record.

    Declared control (D9): ``--param use_uncorrelated_rotor=true`` transports
    spin via a rotation DIFFERENT from the one applied to momentum in K1's
    own sweep geometry (axis=(0,0,1), angle=1.7 vs the wrong-rotor
    (1,0,0)/0.4) — K1 goes red at O(1), confirming the identity is a genuine
    "same rotation" statement, not a tautology of SU(2) closure.
    """
    checks: List[Tuple[str, bool, Any]] = []

    if use_uncorrelated_rotor:
        ctl = uncorrelated_rotor_control()
        ok1 = ctl["residual_uncorrelated_rotor"] < 1e-12
        checks.append(("K1 idealised H_W continuous SO(3) covariance "
                       "(same rotor, sweep)", ok1,
                       ctl["residual_uncorrelated_rotor"]))
    else:
        k1 = idealized_weyl_continuous_covariance(n_axes=n_axes)
        ok1 = k1["worst_residual"] < 1e-12
        checks.append(("K1 idealised H_W continuous SO(3) covariance "
                       "(same rotor, sweep)", ok1, k1["worst_residual"]))

    k2_plus = shipped_walk_continuous_covariance_decades(branch='+')
    k2_minus = shipped_walk_continuous_covariance_decades(branch='-')
    ratios_plus = k2_plus["decade_ratios"]
    ratios_minus = k2_minus["decade_ratios"]
    ok2 = (all(abs(r - 10.0) < 0.5 for r in ratios_plus) if ratios_plus else False) \
        and (all(abs(r - 10.0) < 0.5 for r in ratios_minus) if ratios_minus else False)
    checks.append(("K2 shipped walk: covariance defect shrinks linearly in "
                   "|k| for a GENERIC continuous rotation (decade ratio ~10, "
                   "BOTH branches)", ok2,
                   {"branch_plus": ratios_plus, "branch_minus": ratios_minus}))

    ctl3 = uncorrelated_rotor_control()
    ok3 = (ctl3["residual_correct_rotor"] < 1e-12
           and ctl3["residual_uncorrelated_rotor"] > 1e-3)
    checks.append(("K3 control: correct rotor exact, uncorrelated rotor "
                   "fails at O(1)", ok3,
                   (ctl3["residual_correct_rotor"],
                    ctl3["residual_uncorrelated_rotor"])))

    rows = [{"name": nm, "ok": bool(ok), "value": val} for nm, ok, val in checks]
    return {"checks": rows,
            "passed": all(r["ok"] for r in rows),
            "n_pass": sum(1 for r in rows if r["ok"]),
            "n_total": len(rows),
            "params": {"use_uncorrelated_rotor": use_uncorrelated_rotor,
                       "n_axes": n_axes},
            "summary": summary()}


def summary() -> Dict[str, Any]:
    k1 = idealized_weyl_continuous_covariance()
    k2_plus = shipped_walk_continuous_covariance_decades(branch='+')
    k2_minus = shipped_walk_continuous_covariance_decades(branch='-')
    k3 = uncorrelated_rotor_control()
    return {
        "F379_idealized_worst_residual": k1["worst_residual"],
        "F379_idealized_n_checked": k1["n_checked"],
        "F379_shipped_decade_relative_defects_plus":
            [d["defect_relative"] for d in k2_plus["decades"]],
        "F379_shipped_decade_ratios_plus": k2_plus["decade_ratios"],
        "F379_shipped_decade_relative_defects_minus":
            [d["defect_relative"] for d in k2_minus["decades"]],
        "F379_shipped_decade_ratios_minus": k2_minus["decade_ratios"],
        "F379_control_correct_rotor": k3["residual_correct_rotor"],
        "F379_control_uncorrelated_rotor": k3["residual_uncorrelated_rotor"],
    }


if __name__ == "__main__":
    import json
    import os
    from casim.engine.particles._results_path import results_path

    res = check_so3_kinematic_gap()
    for c in res["checks"]:
        print(f"  [{'PASS' if c['ok'] else 'FAIL'}] {c['name']}  -> {c['value']}")
    print(f"\n  {res['n_pass']}/{res['n_total']} PASS")
    out = results_path("F379_so3_kinematic_gap.json")
    with open(out, "w") as fh:
        json.dump(res, fh, indent=2, default=str)
    print("wrote", os.path.basename(out))
