#!/usr/bin/env python3
"""DEPRECATED shim — the inventory is generated by `casim index` (roadmap C8.3).

P1.5 shipped this as an honest partial: it could classify 147 of 530
residual-bearing entries, because the exactness vocabulary in the artifacts was
not standardised, and it said so rather than emitting a confident table with 383
silent holes.

C8.4 closes that. `casim.index.exactness` keeps this file's rule as rule 1 and
adds two more — the owning test-registry record's `expect.exactness` (D9, a
closed vocabulary by construction) and the numerical signature the inventory
document itself defines — recording per row which rule fired. Coverage is 530 of
530, reported per rule rather than as one number.

Use:

    casim index --only exactness
    casim index --check

This shim stays until C9. It forwards; it re-implements nothing.
"""
from __future__ import annotations

import os
import sys
import warnings

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_REPO, "src"))


def main() -> int:
    warnings.warn(
        "tools/gen_exactness_inventory.py has moved to `casim index` "
        "(casim.index.exactness, roadmap C8.4); this shim is removed at C9.",
        DeprecationWarning, stacklevel=2)
    print("[gen_exactness_inventory] deprecated — forwarding to "
          "`casim index --only exactness`\n")
    from casim.cli import main as cli_main
    argv = ["index", "--only", "exactness"]
    if "--check" in sys.argv[1:]:
        argv.append("--check")
    return cli_main(argv)


if __name__ == "__main__":
    raise SystemExit(main())
