#!/usr/bin/env python3
"""DEPRECATED shim — the indexes are generated by `casim index` (roadmap C8.3).

This file used to be the generator: a filesystem scrape that matched result
artifacts to tests by filename prefix, capped the match list at two, and left
104 of 339 rows in `tests-index.md` empty. C7 made the mapping *declared*
(`tests/registry/*.yaml`) and C3 made module metadata *declared*
(`casim.engine.registry`), so the scrape had nothing left to be right about.

The real implementation is `src/casim/index/` — one module per target, each
reading a registry. Use:

    casim index               # regenerate
    casim index --check       # exit 1 if stale (this is what `make gate` runs)
    casim index --only tests  # one target

This shim stays until C9 deletes it, so that any script or habit still typing
`python3 tools/regen_indexes.py` keeps working and says where to go instead.
It intentionally does NOT re-implement anything: it forwards to the package.
"""
from __future__ import annotations

import os
import sys
import warnings

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_REPO, "src"))


def main() -> int:
    warnings.warn(
        "tools/regen_indexes.py has moved to `casim index` (casim.index, "
        "roadmap C8); this shim is removed at C9.",
        DeprecationWarning, stacklevel=2)
    print("[regen_indexes] deprecated — forwarding to `casim index`\n")
    from casim.cli import main as cli_main
    return cli_main(["index"] + sys.argv[1:])


if __name__ == "__main__":
    raise SystemExit(main())
