#!/usr/bin/env python3
"""Regenerate the repo's compact AI-context indexes.

Run from the repo root:  python3 tools/regen_indexes.py

Builds (all at repo root):
  findings-index.md        one line per findings/F*.md
  project-status-index.md  one line per docs/status/project-status.md entry
  tests-index.md           one line per test/runner: suite, findings, summary, results JSON
  code-index.md            one line per ca-simulation module + casim subpackage
  docs-index.md            one line per docs/, papers/, references/ markdown file

INDEX.md (the master directory map) is hand-maintained — not touched here.
Pipes in extracted text are escaped (`|` -> `\\|`) so |k|-style notation
doesn't break the tables.
"""
import ast
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
os.chdir(ROOT)

CAP = 160  # max summary length

HEADER_NOTE = "*Auto-generated by `tools/regen_indexes.py` — do not edit by hand.*"


def clean(text):
    text = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', text)   # [txt](url) -> txt
    text = re.sub(r'\[\[([^\]]+)\]\]', r'\1', text)         # [[link]] -> link
    return re.sub(r'\s+', ' ', text).strip()


def truncate(text, n=CAP):
    text = text.strip()
    if len(text) <= n:
        return text
    cut = text[:n].rsplit(' ', 1)[0].rstrip(' ,;:.—–-')
    return (cut or text[:n]) + '…'


def esc(text):
    return text.replace("|", "\\|")


def read_head(path, nbytes=4000):
    with open(path, encoding="utf-8", errors="replace") as f:
        return f.read(nbytes)


# ---------------------------------------------------------------- findings
def gen_findings_index():
    findings_dir = "findings"

    def extract_summary(content, fname):
        title_m = re.search(r'^#\s+(.+)', content, re.MULTILINE)
        if title_m:
            title = clean(title_m.group(1))
            parts = re.split(r'\s*[—–]\s*|:\s+', title, maxsplit=1)
            if len(parts) > 1 and parts[1].strip():
                return truncate(parts[1].strip())
            if title:
                return truncate(title)
        sum_m = re.search(r'##\s+Summary\s*\n+(.*?)(?=\n##|\Z)', content, re.DOTALL)
        if sum_m:
            text = clean(sum_m.group(1))
            if text:
                return truncate(re.split(r'(?<=[.!?])\s', text)[0])
        for line in content.splitlines():
            line = line.strip()
            if not line or line.startswith(('#', '**', '`', '>', '-', '|', '$', '!', '*', '=', '[')):
                continue
            if re.match(r'^\d{4}-\d{2}-\d{2}', line):
                continue
            return truncate(clean(line))
        return fname

    entries = []
    for fname in sorted(os.listdir(findings_dir)):
        if not fname.endswith(".md"):
            continue
        content = read_head(os.path.join(findings_dir, fname), 2000)
        m = re.match(r'(F\d+)', fname)
        fnum = m.group(1) if m else "?"
        summary = extract_summary(content, fname)
        test_m = re.search(r'(\d+)/(\d+)\s*PASS', content)
        tests = f"{test_m.group(1)}/{test_m.group(2)} PASS" if test_m else ""
        entries.append((fnum, fname.replace('.md', ''), summary, tests))

    with open("findings-index.md", "w") as out:
        out.write("# Findings Index\n\n" + HEADER_NOTE + "\n")
        out.write("*One line per finding; full files in `findings/`.*\n\n")
        out.write("| # | File | Summary | Tests |\n|---|------|---------|-------|\n")
        for fnum, slug, summary, tests in entries:
            out.write(f"| {fnum} | `{slug}` | {esc(summary)} | {tests} |\n")
    return len(entries)


# ---------------------------------------------------------- project status
def gen_project_status_index():
    src = "docs/status/project-status.md"
    with open(src, encoding="utf-8") as f:
        content = f.read()
    entries = re.findall(r'^## (.+)$', content, re.MULTILINE)
    with open("project-status-index.md", "w") as out:
        out.write("# Project Status Index\n\n" + HEADER_NOTE + "\n")
        out.write(f"*One line per entry; full narrative in `{src}`.*\n\n")
        out.write("| Date | Summary |\n|------|---------|\n")
        for e in entries:
            parts = e.split(" — ", 1)
            if len(parts) == 2:
                date, desc = parts
                out.write(f"| {date.strip()} | {esc(desc.strip()[:140])} |\n")
            else:
                out.write(f"| — | {esc(e[:140])} |\n")
    return len(entries)


# ------------------------------------------------------------------- tests
def first_doc_line(path):
    """First line of the module docstring (safe even if the file won't exec)."""
    try:
        tree = ast.parse(open(path, encoding="utf-8", errors="replace").read())
        doc = ast.get_docstring(tree) or ""
    except SyntaxError:
        doc = ""
    if not doc:
        return ""
    return truncate(clean(doc.strip().splitlines()[0]))


def gen_tests_index():
    suites = [
        ("findings", "tests/findings", "finding verification"),
        ("priority", "tests/priority", "GR/QM/QFT priority battery"),
        ("casim", "tests/casim", "casim package suite (default pytest)"),
        ("runners", "tests/runners", "standalone run scripts"),
    ]
    results = set(os.listdir("test-results")) if os.path.isdir("test-results") else set()
    rows = []
    for suite, d, _ in suites:
        if not os.path.isdir(d):
            continue
        for fname in sorted(os.listdir(d)):
            if not fname.endswith(".py") or fname == "conftest.py":
                continue
            path = os.path.join(d, fname)
            doc = first_doc_line(path)
            finds = sorted(set(re.findall(r'\bF\d{2,3}\b', fname + " " + doc)),
                           key=lambda s: int(s[1:]))
            # result JSON heuristic: stem without leading test_, exact or prefixed
            stem = re.sub(r'^test_', '', fname[:-3])
            res = [r for r in results
                   if r.endswith(('.json', '.md')) and r.startswith(stem)]
            res_s = ", ".join(f"`{r}`" for r in sorted(res)[:2])
            rows.append((suite, fname, " ".join(finds), doc, res_s))
    with open("tests-index.md", "w") as out:
        out.write("# Tests Index\n\n" + HEADER_NOTE + "\n")
        out.write("*One line per test/runner. Suites: findings (test_F*), priority "
                  "(GR/QM/QFT battery), casim (package suite — default `pytest` target), "
                  "runners (standalone). Specs for future falsification tests live in "
                  "`tests/falsification/` (see its ROADMAP.md).*\n\n")
        out.write("| Suite | File | Findings | Summary | Results |\n"
                  "|-------|------|----------|---------|---------|\n")
        for suite, fname, finds, doc, res in rows:
            out.write(f"| {suite} | `{fname}` | {finds} | {esc(doc)} | {res} |\n")
    return len(rows)


# -------------------------------------------------------------------- code
def gen_code_index():
    rows = []
    sim = "ca-simulation"
    for fname in sorted(os.listdir(sim)):
        if not fname.endswith(".py"):
            continue
        rows.append(("ca-simulation", fname, first_doc_line(os.path.join(sim, fname))))
    forks = os.path.join(sim, "forks")
    if os.path.isdir(forks):
        for fname in sorted(os.listdir(forks)):
            if fname.endswith(".py"):
                rows.append(("ca-simulation/forks", fname,
                             first_doc_line(os.path.join(forks, fname))))
    pkg = "src/casim"
    for entry in sorted(os.listdir(pkg)):
        sub = os.path.join(pkg, entry)
        if os.path.isdir(sub) and os.path.exists(os.path.join(sub, "__init__.py")):
            rows.append(("casim", entry + "/", first_doc_line(os.path.join(sub, "__init__.py"))))
        elif entry.endswith(".py") and entry != "__init__.py":
            rows.append(("casim", entry, first_doc_line(sub)))
    with open("code-index.md", "w") as out:
        out.write("# Code Index\n\n" + HEADER_NOTE + "\n")
        out.write("*One line per kernel module (`ca-simulation/`) and casim "
                  "subpackage (`src/casim/`); summaries are first docstring lines.*\n\n")
        out.write("| Layer | Module | Summary |\n|-------|--------|---------|\n")
        for layer, mod, doc in rows:
            out.write(f"| {layer} | `{mod}` | {esc(doc)} |\n")
    return len(rows)


# -------------------------------------------------------------------- docs
def md_title(path):
    content = read_head(path, 2000)
    m = re.search(r'^#\s+(.+)', content, re.MULTILINE)
    if m:
        return truncate(clean(m.group(1)))
    for line in content.splitlines():
        line = line.strip()
        if line and not line.startswith(('#', '`', '>', '|', '!', '---')):
            return truncate(clean(line))
    return ""


def gen_docs_index():
    groups = [
        ("docs/theory", "internal theory derivations & key decisions"),
        ("docs/roadmaps", "active roadmaps & next steps"),
        ("docs/status", "project status, changelog, exactness inventory"),
        ("docs/audits", "one-off reviews & audits"),
        ("docs/design", "internal design docs"),
        ("papers", "the paper series"),
        ("references", "summaries of external papers (PDFs alongside)"),
    ]
    with open("docs-index.md", "w") as out:
        out.write("# Docs Index\n\n" + HEADER_NOTE + "\n")
        out.write("*One line per document. PDFs in `references/` are listed by "
                  "their markdown summaries only.*\n\n")
        n = 0
        for d, blurb in groups:
            if not os.path.isdir(d):
                continue
            out.write(f"\n## {d}/ — {blurb}\n\n| File | Title |\n|------|-------|\n")
            for fname in sorted(os.listdir(d)):
                if not fname.endswith(".md") or fname == "README.md":
                    continue
                out.write(f"| `{fname}` | {esc(md_title(os.path.join(d, fname)))} |\n")
                n += 1
    return n


if __name__ == "__main__":
    print(f"findings-index.md        {gen_findings_index()} entries")
    print(f"project-status-index.md  {gen_project_status_index()} entries")
    print(f"tests-index.md           {gen_tests_index()} entries")
    print(f"code-index.md            {gen_code_index()} entries")
    print(f"docs-index.md            {gen_docs_index()} entries")
    sys.exit(0)
